// The file an agent reads before it touches anything in a worktree.
//
// An agent arriving in a checkout it did not provision assumes the defaults:
// port 3000, the database on 54322, `localhost:3000` in a browser. In a
// worktree every one of those reaches a DIFFERENT branch's app or another
// session's data, and the mistake is invisible — the page loads, the query
// works, the answer is about the wrong branch.
//
// So the plan is written down in prose, in the checkout, where reading costs
// nothing and running a command is not required. This is the file the project's
// own AGENTS.md points at, and the cutover that replaced the Bash provisioner
// stopped writing it: the instruction stayed, its target vanished, and a
// confidently wrong pointer is worse than no pointer at all.
//
// Generated, never edited: `ax worktree setup` overwrites it, and it is
// gitignored, so the copy in a checkout always describes that checkout.

/** Where the file goes. Gitignored by `ax init`, so it never reaches a diff. */
export const CONTEXT_PATH = '.agent/worktree-context.local.md';

/**
 * The context file's contents, from a plan.
 *
 * Ordered by what a cold reader needs first: the address to open, then the
 * database it is talking to, then the commands. Every value comes from the plan
 * rather than being re-derived, so this file cannot describe a worktree the rest
 * of the tooling would describe differently.
 */
export function renderContext({ plan, config, main }) {
  const { identity, port, urls, supabase, worktreePath } = plan;
  const web = config.apps.web;

  const lines = [
    `# ${identity.name}`,
    '',
    `Generated by \`ax worktree setup\`, local to this worktree and gitignored.`,
    '**Read this before starting the dev server, running browser tests, or opening a page here** —',
    'the port and the database differ per worktree, so a hardcoded `localhost:3000` reaches another',
    "branch's app or another session's data.",
    '',
    '## This worktree',
    '',
    `| | |`,
    `|---|---|`,
    `| Branch | \`${identity.branch ?? '(detached)'}\` |`,
    identity.issue ? `| Issue | #${identity.issue} (${identity.issueSource}) |` : undefined,
    `| Path | \`${worktreePath}\` |`,
    `| Primary checkout | \`${main}\` |`,
    '',
    '## Addresses',
    '',
    `| | |`,
    `|---|---|`,
    `| **Open this** | ${urls.publishedUrl} |`,
    urls.publishedUrl === urls.directUrl ? undefined : `| Direct (always works) | ${urls.directUrl} |`,
    urls.tailnetUrl ? `| From a phone | ${urls.tailnetUrl} |` : undefined,
    `| Dev port | ${port.port} |`,
    '',
    ...database({ supabase }),
    '## Commands',
    '',
    '```bash',
    `pnpm --dir ${web} dev              # this worktree's own port`,
    'ax doctor                          # is this checkout still coherent?',
    'ax worktree ls                     # every checkout, and what it holds',
    '```',
    '',
    'Every database command goes through `ax supabase …`. Calling the `supabase` binary',
    'directly bypasses the guard that keeps a migration or a reset off the shared database.',
    '',
  ];

  return `${lines.filter(line => line !== undefined).join('\n')}`;
}

/**
 * The database half, which is the one an agent gets wrong most expensively: a
 * `db reset` against a shared stack rewrites the data every other session is
 * reading, and nothing about the command says so.
 */
function database({ supabase }) {
  if (supabase.mode !== 'isolated') {
    return [
      '## Database — SHARED',
      '',
      "This worktree talks to the primary checkout's local database. A migration, a reset or a",
      'typegen here rewrites the data every other session is reading.',
      '',
      'It is promoted to its own isolated stack automatically the first time `ax supabase …`',
      'would write. The database port changes then, so restart the dev server afterwards.',
      '',
    ];
  }

  return [
    '## Database — ISOLATED',
    '',
    `| | |`,
    `|---|---|`,
    `| Project | \`${supabase.projectId}\` |`,
    `| Port block | +${supabase.offset} |`,
    `| API | http://127.0.0.1:${supabase.ports.api} |`,
    `| Postgres | 127.0.0.1:${supabase.ports.db} |`,
    `| Studio | http://127.0.0.1:${supabase.ports.studio} |`,
    `| Mail | http://127.0.0.1:${supabase.ports.inbucket} |`,
    '',
    'Migrations and resets here affect nothing else. Stop it with `ax worktree clean`.',
    '',
  ];
}
