// `ax triage publish` — the one place a triage verdict reaches the tracker.
//
// A triage child writes a draft and mutates nothing, so the mutation has to
// happen somewhere. Leaving it to the operator's own `gh` calls is not a smaller
// surface, it is an untested one — and it is precisely the failure this whole
// noun is paid for: on 2026-08-10 four issues landed with three empty label
// groups each, because applying five groups by hand is data entry and data entry
// gets skipped.
//
// So this verb is narrow and unfriendly on purpose:
//
//   * it applies EXACTLY what the draft names, and refuses a draft that names
//     nothing — it never composes, never guesses a missing group
//   * it reads every draft before the first `gh` call, so a batch cannot land
//     half applied
//   * it NEVER closes an issue. A child may recommend wontfix; closing is the
//     one gesture the reporter is owed by a human
//   * a `custom` job is not publishable at all, by name: its draft is a report
//     to you, not a tracker mutation

import { existsSync, writeFileSync } from 'node:fs';
import { repoPaths } from '../config.mjs';
import { bad, dim, fix, note, raw, section } from '../log.mjs';
import { redactSecrets } from '../redact.mjs';
import { defaultExec } from '../worker/release.mjs';
import { readDraft } from './draft.mjs';

const USAGE = 'ax triage publish --issue N [--issue M …] [--job triage|brief] [--repo <owner/repo>] [--dry-run]';

/** The disclaimer every AI-written comment on the tracker has to carry. */
const DISCLAIMER = '> *This was generated by AI during triage.*';

export function publish(argv = [], { exec = defaultExec, env = process.env, cwd = process.cwd() } = {}) {
  const usageError = message => {
    process.stderr.write(`ax triage publish: ${message}\n${USAGE}\n`);
    return 2;
  };
  const refuse = (message, repair) => {
    bad(redactSecrets(message));
    if (repair) fix(redactSecrets(repair));
    return 1;
  };

  const issues = [];
  let job = 'triage';
  let repo = '';
  let dry = false;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const value = () => argv[(i += 1)] ?? '';
    if (arg === '--issue') issues.push(value());
    else if (arg === '--job') job = value();
    else if (arg === '--repo') repo = value();
    else if (arg === '--dry-run') dry = true;
    else if (arg === '-h' || arg === '--help') return (raw(`${USAGE}\n`), 0);
    else return usageError(`unknown argument "${arg}"`);
  }

  if (issues.length === 0) return usageError('no --issue given');
  for (const issue of issues) {
    if (!/^[1-9][0-9]*$/.test(issue)) return usageError(`--issue expects a number, got "${issue}"`);
  }
  if (job === 'custom') {
    return refuse(
      'a custom job is not publishable: its draft is a report to you, not a tracker mutation — it names a finding, not a label set',
      'read the draft, and if it concluded something the tracker should carry, run a triage or brief job for it',
    );
  }
  if (!['triage', 'brief'].includes(job)) return usageError(`--job expects triage|brief, got "${job}"`);

  const paths = repoPaths(cwd);
  if (!paths.root) return refuse('not inside a git repository — the drafts live in this checkout');
  const gh = args => exec('gh', args, paths.root);
  const slug = repo || resolveRepo(gh);
  if (slug === '') return refuse('could not resolve the current repository', 'ax triage publish --repo <owner>/<repo>');

  // ── every draft read before the first mutation ────────────────────────────
  section(`drafts — ${slug} (job: ${job})`);
  const ready = [];
  let blocked = false;
  for (const issue of issues) {
    const draft = readDraft(paths.root, { job, repo: slug, issue });
    if (!draft.ok) {
      bad(`#${issue} ${draft.reason}`);
      if (existsSync(draft.path)) fix(`edit ${draft.path} # then re-run: publish applies exactly what it names`);
      blocked = true;
      continue;
    }
    note(`#${issue} ${draft.labels.length} label(s) ${dim(draft.labels.join(', '))}`);
    if (draft.close) note('  ^ this draft recommends closing — publish applies the labels and the comment, and leaves the issue OPEN');

    // Free text never touches argv. A verdict is multi-line prose written by an
    // agent and edited by a human — quotes, backticks, code fences and all — and
    // argv is the one channel that mangles exactly that. So the body is rendered
    // to a file and handed over as a path.
    //
    // It is rendered HERE, in the loop that can still refuse: a render that fails
    // after `gh issue edit` has run leaves the labels applied and the comment
    // missing, which is the half-landed state this batch is ordered to avoid.
    const labels = ['issue', 'edit', issue, '--repo', slug, ...draft.labels.flatMap(label => ['--add-label', label])];
    const bodyPath = `${draft.path.slice(0, -'.md'.length)}.body.md`;
    const body = `${DISCLAIMER}\n\n${draft.body}\n`;
    if (!dry) {
      try {
        writeFileSync(bodyPath, body);
      } catch (error) {
        bad(`#${issue} the comment could not be rendered to ${bodyPath}: ${String(error.code ?? error.message ?? error)}`);
        blocked = true;
        continue;
      }
    }
    ready.push({ issue, draft, labels, bodyPath, lines: body.split('\n').length });
  }
  if (blocked) return refuse('nothing was published — one draft per issue, complete and rendered, before the first gh call');

  // ── the mutation, per issue, labels and comment together ──────────────────
  let failed = 0;
  for (const { issue, draft, labels, bodyPath, lines } of ready) {
    section(`issue #${issue}`);

    if (dry) {
      note(`would run: gh ${labels.join(' ')}`);
      note(`would post ${lines} line(s), rendered from ${draft.path}`);
      continue;
    }

    const applied = gh(labels);
    if (applied.error || applied.status !== 0) {
      bad(`#${issue} labels refused — ${firstLine(applied.stderr) || `exit ${applied.status}`}`);
      fix(`gh ${labels.join(' ')} # nothing was posted for this issue`);
      failed = 1;
      continue;
    }
    // The comment goes second, and only after the labels landed: a comment
    // whose label set never applied reads to the next human as a finished pass.
    const posted = gh(['issue', 'comment', issue, '--repo', slug, '--body-file', bodyPath]);
    if (posted.error || posted.status !== 0) {
      bad(`#${issue} labels applied, comment refused — ${firstLine(posted.stderr) || `exit ${posted.status}`}`);
      fix(`gh issue comment ${issue} --repo ${slug} --body-file ${bodyPath} # the labels are already on`);
      failed = 1;
      continue;
    }
    note(`published — ${draft.labels.length} label(s) and one comment`);
    if (draft.close) note('the draft recommended closing: that is yours to do, and this verb never does it');
  }
  return failed;
}

const firstLine = text => String(text ?? '').split('\n')[0].trim();

function resolveRepo(gh) {
  const out = gh(['repo', 'view', '--json', 'nameWithOwner', '-q', '.nameWithOwner']);
  if (out.error || out.status !== 0) return '';
  return String(out.stdout ?? '').trim().split('\n')[0] ?? '';
}
