// `ax triage publish` — the one place a triage verdict reaches the tracker.
//
// A triage child writes a draft and mutates nothing, so the mutation has to
// happen somewhere. Leaving it to the operator's own `gh` calls is not a smaller
// surface, it is an untested one — and it is precisely the failure this whole
// noun is paid for: on 2026-08-10 four issues landed with three empty label
// groups each, because applying five groups by hand is data entry and data entry
// gets skipped.
//
// So this verb is narrow and unfriendly on purpose:
//
//   * it applies EXACTLY what the draft names, and refuses a draft that names
//     nothing — it never composes, never guesses a missing group
//   * it reads every draft before the first `gh` call, so a batch cannot land
//     half applied
//   * it grades each directive against what the issue ALREADY CARRIES, read on
//     that same tracker read: a `Labels:` name in the PROVENANCE group the
//     issue already wears, or a `Remove labels:` name it does not wear, is a
//     directive that changes nothing and it refuses the batch rather than
//     dropping the name — dropping would be composing (#101)
//   * it asks the TRACKER whether this publication already landed there, and
//     refuses a second one unless `--republish` says so out loud (ofmchat #98)
//   * it NEVER closes an issue. A child may recommend wontfix; closing is the
//     one gesture the reporter is owed by a human
//   * a `custom` job is not publishable at all, by name: its draft is a report
//     to you, not a tracker mutation

import { existsSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRunner, resolveOrca, runtimeReady } from '../orca-bin.mjs';
import { loadCheckoutConfig, repoPaths } from '../config.mjs';
import { bad, dim, fix, note, section, warn } from '../log.mjs';
import { redactSecrets } from '../redact.mjs';
import { defaultExec } from '../exec.mjs';
import { repoSlug } from '../gh.mjs';
import { defaultStore, dispatchIndex, handlesByRequest, report } from '../worker/record.mjs';
import { paneVerdict, terminalInventory } from '../worker/pane.mjs';
import { draftDirFor, passesIn, readDraft, requestFor } from './draft.mjs';
import { carriedClasses, declaredCarried, declaredProvenance, sameLabel } from './provenance.mjs';
import { REFINE_REMOVED, READY_LABEL } from './spec.mjs';

const USAGE = 'ax triage publish --issue N [--issue M …] [--job triage|brief] [--pass N] [--repo <owner/repo>] [--republish] [--dry-run]';

/**
 * The disclaimer every AI-written comment carries, per job — and, since
 * goodluckagency/ofmchat#98, the marker this verb reads BACK off the tracker to
 * see whether its own publication already landed.
 *
 * That is the reason the two wordings differ by job instead of by decoration.
 * One shared line would make a landed Agent Brief indistinguishable from a
 * landed verdict, and the only guard left would be COUNTING comments — which
 * cannot hold: a corrected pass 2 is a legitimate second AI comment, so an
 * arithmetic gate would refuse a first brief on a twice-triaged issue and call
 * it a duplicate. Each job recognizes exactly its own publication and nothing
 * else.
 *
 * A comment published BEFORE this version carries the triage wording whatever
 * job wrote it, so the marker alone leaves one hole: a second brief over an old
 * brief. Measured on goodluckagency/ofmchat, 2026-08-29, at the reporter's
 * request rather than left to be sized later — 14 such briefs, one each on
 * #50-#61, #98 and #100. That hole is
 * closed by `verbatim` below instead of by rewriting 14 published comments: a
 * per-repository history migration is not something a package's correctness may
 * depend on, and the next consuming repo would owe the same one.
 */
const DISCLAIMER_BY_JOB = {
  triage: '> *This was generated by AI during triage.*',
  brief: '> *This Agent Brief was generated by AI during triage.*',
};

/**
 * Every rendering a publication can have on the tracker: one per wording, and
 * the pre-0.15 shared line is among them because it IS the triage wording. The
 * retired readiness lane's wording is NOT here, and its absence costs nothing:
 * its draft grammar is gone too, so such a draft is refused as unpublishable
 * long before the tracker is asked what it already carries.
 *
 * This is what makes an OLD publication recognizable without its job being
 * legible. A leftover draft's hazard is that it re-publishes VERBATIM — 26 of
 * them on the day this was reported, every one byte-identical to what already
 * landed — so the comment that carries this exact draft is an exact string
 * comparison, not a heuristic about headings or comment counts.
 */
const RENDERINGS = Object.values(DISCLAIMER_BY_JOB);

/** Tracker text and local text compared on the one axis GitHub does not alter. */
const normalize = text => String(text ?? '').replace(/\r\n/g, '\n').trim();

/**
 * Re-stated here only as the reason this verb needs no ready-label mechanism of
 * its own: `READY_LABEL` is declared beside the job vocabulary (`spec.mjs`),
 * where the `brief` child is instructed to write it into its `Labels:` line.
 * `publish` applies exactly what the draft names, so the label arrives through
 * the ordinary directive path — checked against the repository's label list
 * with every other name, landed by the same single `gh issue edit`. What this
 * file still reads the constant FOR is the mutation ORDER below.
 */

export function publish(argv = [], { exec = defaultExec, env = process.env, cwd = process.cwd(), resolve = resolveOrca, runner } = {}) {
  const usageError = message => {
    process.stderr.write(`ax triage publish: ${message}\n${USAGE}\n`);
    return 2;
  };
  const refuse = (message, repair) => {
    bad(redactSecrets(message));
    if (repair) fix(redactSecrets(repair));
    return 1;
  };

  const issues = [];
  let job = 'triage';
  let repo = '';
  let dry = false;
  let wantPass = '';
  let republish = false;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const value = () => argv[(i += 1)] ?? '';
    if (arg === '--issue') issues.push(value());
    else if (arg === '--job') job = value();
    else if (arg === '--repo') repo = value();
    else if (arg === '--dry-run') dry = true;
    else if (arg === '--pass') wantPass = value();
    else if (arg === '--republish') republish = true;
    // No help branch: `runCli` answers the flag from the registry, anywhere in
    // this noun's argv, before the verb is reached (../cli.mjs, #89).
    else return usageError(`unknown argument "${arg}"`);
  }

  if (issues.length === 0) return usageError('no --issue given');
  // Every occurrence gets its own full preflight, and the preflight reads the
  // tracker BEFORE this verb writes to it — so a repeated number is two reads of
  // an untouched issue, two entries in `ready`, and two identical comments from
  // one invocation, with no `--republish` asked for. Found by review on PR #33.
  //
  // Refused rather than deduplicated: a batch naming one issue twice is a typo,
  // and collapsing it silently would also swallow the likelier mistake behind it
  // — a second number the operator meant to type differently. `--republish` is
  // how a second verdict is asked for; it is never something argv repetition
  // buys by accident.
  const named = new Set();
  for (const issue of issues) {
    if (!/^[1-9][0-9]*$/.test(issue)) return usageError(`--issue expects a number, got "${issue}"`);
    if (named.has(issue)) return usageError(`--issue ${issue} given twice — one issue is published once per invocation`);
    named.add(issue);
  }
  if (job === 'refine') return usageError(REFINE_REMOVED);
  if (job === 'custom') {
    return refuse(
      'a custom job is not publishable: its draft is a report to you, not a tracker mutation — it names a finding, not a label set',
      'read the draft, and if it concluded something the tracker should carry, run a triage or brief job for it',
    );
  }
  if (!['triage', 'brief'].includes(job)) return usageError(`--job expects triage|brief, got "${job}"`);

  const paths = repoPaths(cwd);
  if (!paths.root) return refuse('not inside a git repository — the drafts live in this checkout');
  const gh = args => exec('gh', args, paths.root);
  const slug = repo || repoSlug(gh);
  if (slug === '') return refuse('could not resolve the current repository', 'ax triage publish --repo <owner>/<repo>');

  // The repository's own vocabulary, read ONCE for the batch and before any
  // mutation — a name this list does not carry is refused here rather than
  // discovered by `gh` halfway through a batch.
  const known = repoLabels(gh, slug);
  if (known === null) {
    return refuse(
      'gh could not list this repository\'s labels, so no name in any draft can be checked — and an unchecked remove is the one mistake that does not undo',
      `gh label list --repo ${slug} # then re-run once it answers`,
    );
  }
  if (known.truncated) {
    return refuse(
      `gh returned ${LABEL_CAP} labels, exactly the cap it was asked for, so this list may be missing names — and a name missing from a truncated list reads identically to one this repository does not have`,
      `gh label list --repo ${slug} --limit 5000 # confirm the names by hand, then raise LABEL_CAP in ax`,
    );
  }

  // The PROVENANCE vocabulary, which is the one label group whose doctrine
  // forbids a second name ("already on the issue at birth — keep it, never add
  // a second"). Read from the repository's own config, because the taxonomy is
  // the repository's and never this package's — and read through the SHARED
  // rule, because which classes exist is not this verb's to decide. It kept its
  // own two-class list until #179, so an issue born a declared FINDING was
  // invisible to the add-side gate below and a second `source:` label
  // published over it.
  //
  // A config that exists and does not parse is an inability to establish, not a
  // declaration of nothing: read as "no provenance declared" it would silently
  // switch the add-side gate below off. The same holds for a mapping that
  // parses and cannot be used — `ax.config.json` is schema-validated here, so a
  // `spec` that is a string refuses above rather than reading as an undeclared
  // contract. A repository that declares no provenance grades no ADD — an
  // absent declaration is not a rule (F-028), and this verb publishes for
  // repositories that never adopted the group — while a remove of a label the
  // issue does not carry is graded everywhere, from the live labels alone.
  const loaded = loadCheckoutConfig({ root: paths.root, main: paths.main });
  if (loaded.exists && loaded.errors.length > 0) {
    return refuse(`ax.config.json has ${loaded.errors.length} problem(s): ${loaded.errors.join('; ')}`, 'ax doctor');
  }
  const provenance = loaded.config?.triage?.provenance ?? {};
  const declared = declaredProvenance(provenance);

  // ── every draft read before the first mutation ────────────────────────────
  section(`drafts — ${slug} (job: ${job})`);
  const ready = [];
  let blocked = false;
  // Which PASS lands, decided per issue and always said out loud.
  //
  // Newest by default: once a second pass exists, that is what "the verdict on
  // this ticket" means. Naming an older one with `--pass N` IS the permission to
  // publish it — what is refused is naming a pass nobody wrote.
  //
  // The one hard gate is a NEWER pass whose child may still be working. It costs
  // an Orca round-trip, so it is paid ONLY on the `--pass <older>` path: with no
  // flag there is no newer pass by construction, and the ordinary publish stays
  // a `gh`-only verb that works with the runtime down.
  if (wantPass !== '' && !/^[1-9][0-9]*$/.test(wantPass)) return usageError(`--pass expects a number, got "${wantPass}"`);
  const store = defaultStore(env);
  let probe = null;
  for (const issue of issues) {
    const base = { job, repo: slug, issue };
    const written = passesIn(draftDirFor(paths.root), base, '.md');
    const recorded = passesIn(store, base, '.json');
    const all = [...new Set([...written, ...recorded])].sort((a, b) => a - b);
    // Only a written pass can be published, so the default target is the newest
    // DRAFT; an unwritten newer pass shows up in `later` and forces the probe.
    const target = written.length === 0 ? 1 : written[written.length - 1];
    const pass = wantPass === '' ? target : Number(wantPass);

    if (wantPass !== '' && !written.includes(pass) && !(written.length === 0 && pass === 1)) {
      bad(`#${issue} has no pass ${pass}${written.length > 0 ? ` — it has ${written.join(', ')}` : ' and no draft at all'}`);
      fix(`ax triage status --issue ${issue} --job ${job}   # every pass this ticket has`);
      blocked = true;
      continue;
    }
    if (all.length > 1 && pass === target) note(`#${issue} passes ${all.join(', ')} — publishing ${pass}, the newest with a draft`);

    // Only a DISPATCHED newer pass can be holding a child. A newer pass with a
    // draft and no record was written by hand and never had one, so probing it
    // would refuse on an absence that means nothing. The record is the evidence
    // a child exists; the pane probe then says whether it is still there.
    const later = all.filter(other => other > pass && recorded.includes(other));
    if (later.length > 0) {
      // Built once, on the first issue that needs it.
      if (probe === null) probe = livenessProbe({ resolve, runner, exec, env, store });
      if (!probe.ok) {
        bad(`#${issue} names pass ${pass} while ${later.length} newer pass(es) exist, and their panes cannot be read: ${probe.reason}`);
        fix('orca open   # a newer child that cannot be seen must never be assumed finished (F-028)');
        blocked = true;
        continue;
      }
      const rival = probe.judge(later.map(other => ({ pass: other, request: requestFor({ ...base, pass: other }) })));
      if (rival !== null) {
        bad(`#${issue} pass ${rival.pass ?? '?'} is ${rival.pane} (${rival.detail}) — publishing pass ${pass} underneath a child that may still be writing would land a verdict already being replaced`);
        fix(`ax worker ls   # settle the newer pass first, then re-run`);
        blocked = true;
        continue;
      }
      note(`#${issue} publishing pass ${pass}; newer pass(es) ${later.join(', ')} are finished`);
    }
    const draft = readDraft(paths.root, { ...base, pass });
    note(`#${issue} pass ${pass} — ${draft.sha ? `${draft.sha.slice(0, 12)} · ${draft.lines} line(s)` : 'no draft'}`);
    if (!draft.ok) {
      bad(`#${issue} ${draft.reason}`);
      if (existsSync(draft.path)) fix(`edit ${draft.path} # then re-run: publish applies exactly what it names`);
      blocked = true;
      continue;
    }
    // An OPEN question is a verdict not yet rendered: the child that wrote this
    // draft is parked on it, or died waiting on it — either way its loop is not
    // finished, and a comment landing mid-escalation is the adjustment problem
    // this whole noun exists to prevent. The spec already tells every child
    // "Report when the draft is FINAL — which means it carries no open
    // question"; this is that same contract, held at the boundary where it can
    // be enforced. No override: a question FOR THE REPORTER belongs in the
    // comment body as prose — the `Q<n>:` marker is, by grammar, the channel to
    // the parent and nothing else.
    //
    // What this gate is NOT: a wave guarantee. It makes any batch containing a
    // still-asking issue refuse entirely (the all-or-nothing above), but it
    // does not know what a "wave" is — publishing one finished issue alone
    // while its siblings still work is legal here, and whether ax should own
    // wave membership is an open arbitration.
    if (draft.questions.length > 0) {
      bad(`#${issue} still carries ${draft.questions.length} open question(s) — an open question is a verdict not yet rendered`);
      fix(`ax triage status --issue ${issue} --job ${job}   # who is waiting; answer it, let the child fold and drop its Q lines, then publish`);
      blocked = true;
      continue;
    }
    const unknown = [...draft.labels, ...draft.remove].filter(label => !known.names.has(label));
    if (unknown.length > 0) {
      bad(`#${issue} names ${unknown.length} label(s) this repository does not have: ${unknown.join(' | ')}`);
      // `ready-for-agent` is the one unknown name that is likelier a missing
      // label than a mistyped directive: a brief is the pass that applies it,
      // and a repository new to this flow has simply never created it.
      if (unknown.includes(READY_LABEL)) fix(`gh label create ${READY_LABEL} --repo ${slug} # the label a brief publication applies, and this repository does not carry it yet`);
      else fix(`edit ${draft.path} # a directive carries label NAMES only — no group prefix, no justification`);
      blocked = true;
      continue;
    }

    // ── has this publication already landed? ─────────────────────────────────
    //
    // The tracker is the only authority for what the tracker carries, and it has
    // to be ASKED: a draft SURVIVES its own publication in `.scratch`, so nothing
    // on disk tells "reviewed, ready to publish" apart from "published
    // yesterday". Measured on goodluckagency/ofmchat 2026-08-29: 26 leftover
    // drafts, every one re-publishable verbatim, and #98 took a second verdict
    // under a complete lifecycle from the day before because this question was
    // never put — not by `--dry-run` either, which offered to post it.
    //
    // This machine's release ledger is NOT the answer, though it happens to know
    // that particular pass landed: it records a pane's lifecycle, so it says
    // nothing about a verdict published by another session, published by hand, or
    // deleted since. Two answers to one question is how one of them ends up
    // wrong.
    const tracker = trackerState(gh, { slug, issue, marker: DISCLAIMER_BY_JOB[job], body: draft.body });
    if (!tracker.ok) {
      bad(`#${issue} what this issue already carries could not be read: ${tracker.reason} — and an unread issue reads exactly like an untouched one (F-028)`);
      fix(`gh issue view ${issue} --repo ${slug} --json comments,labels # then re-run once it answers`);
      blocked = true;
      continue;
    }

    // ── does either directive already have its effect? ───────────────────────
    //
    // The vocabulary check above answers which labels EXIST. It cannot answer
    // which of them are ON this issue, and until #101 nothing here could: three
    // published comments restated a `source:` label the issue wore at birth,
    // which `docs/agents/triage-labels.md` forbids ("already on the issue at
    // birth — keep it, never add a second"), and publish reported it as applied.
    //
    // It REFUSES rather than dropping the name. This verb applies exactly what
    // the draft names and never composes (see the header), so filtering a
    // directive out would reverse that rule and hide the draft that has to be
    // corrected. The repair names the line to delete.
    //
    // Two directions, one read. A `Labels:` name in the PROVENANCE group is
    // refused when the issue was born with ANY declared provenance name — the
    // same one or another — because that is the one group whose doctrine
    // forbids a second name; a redundant category or state name is disclosed
    // below instead. Comparing the draft's name to the same name on the issue
    // was the first draft's mistake (review, 2026-09-02): it let a second
    // provenance name through, which is the exact state the rule exists to
    // prevent. The add-side gate needs the vocabulary to know which names ARE
    // provenance, so it is off for a repository that declares none — an absent
    // declaration is not a rule (F-028). A `Remove labels:` name the issue does
    // NOT carry is the same no-op in the other direction, for any group, and it
    // needs only the live labels this verb already read: it is graded in every
    // repository, which is what the child is told (`spec.mjs`).
    const bornWith = declared.length > 0 ? declaredCarried(declared, tracker.carried) : [];
    const redundantAdds = bornWith.length === 0 ? [] : draft.labels.filter(name => declaredCarried([name], declared).length > 0);
    const absentRemoves = draft.remove.filter(name => !tracker.carried.some(carried => sameLabel(name, carried)));
    if (redundantAdds.length > 0 || absentRemoves.length > 0) {
      for (const name of redundantAdds) {
        bad(`#${issue} names ${name} on its Labels: line, and the issue was born with ${bornWith.join(', ')} — a provenance label is kept as born, never joined by a second`);
      }
      for (const name of absentRemoves) {
        bad(`#${issue} asks to remove ${name}, which the issue does not carry — that directive does nothing`);
      }
      fix(`edit ${draft.path} # delete ${[...redundantAdds, ...absentRemoves].join(', ')} from its directive line — publish applies exactly what a draft names, so it refuses one that would change nothing rather than dropping it`);
      blocked = true;
      continue;
    }

    // ── would this publication leave the issue with two origins? ────────────
    //
    // The birth rule above compares the draft's ADDS to what the issue was born
    // with, and that comparison is blind twice over: it says nothing when the
    // issue carries no provenance at all — a draft naming two classes at once
    // passed — and nothing when the draft names none, so a contradiction
    // ALREADY on the tracker published as though it were valid. Neither is a
    // state any consumer of this vocabulary accepts: `ax frontier` excludes
    // such a ticket `provenance-refused`, and `ax triage dispatch` refuses
    // every pass over it. Landing one here would publish work into a shape the
    // rest of the flow then refuses to touch.
    //
    // So what is graded is the FULL PROPOSED RESULT — carried, minus the
    // removes, plus the adds — through the same shared rule the other two
    // verbs read. Two directions of one comparison are not the same question as
    // the state the tracker would be left in.
    //
    // NO RECLASSIFICATION, EITHER WAY. This verb applies exactly what a draft
    // names, so the repair is a correction and never a composition: delete the
    // offending name from the draft when the draft added it, or correct the
    // established labels when the tracker is what contradicts itself. A draft
    // whose `Remove labels:` line resolves the contradiction publishes — that
    // one IS the correction, and the proposed result is consistent.
    const proposed = [...tracker.carried.filter(carried => !draft.remove.some(name => sameLabel(name, carried))), ...draft.labels];
    const classes = carriedClasses(provenance, proposed);
    if (classes.length > 1) {
      const named = classes.flatMap(({ names }) => names);
      const added = named.filter(name => draft.labels.some(add => sameLabel(add, name)));
      bad(
        `#${issue} would carry ${classes.map(({ names }) => names.join(', ')).join(' and ')} — one ticket cannot be both ${classes
          .map(({ kind }) => kind)
          .join(' and ')}, and no publication follows from a contradiction`,
      );
      if (added.length > 0) {
        fix(
          `edit ${draft.path} # delete ${added.join(', ')} from its directive line — publish applies exactly what a draft names, so it refuses a directive set that would leave two origins on one ticket`,
        );
      } else {
        fix(
          `gh issue edit ${issue} --repo ${slug} --remove-label ${named[0]} # the contradiction is already on the issue: correct the established labels, then re-run`,
        );
      }
      blocked = true;
      continue;
    }
    // A redundant name in a group whose doctrine permits it publishes, and is
    // said out loud so the operator can see a directive that changed nothing.
    const idle = draft.labels.filter(name => tracker.carried.some(carried => sameLabel(name, carried)));
    if (idle.length > 0) note(`#${issue} already carries ${dim(idle.join(', '))} — applied again, which GitHub answers idempotently`);
    // The exact-bytes refusal comes FIRST because it is the more convincing one
    // and the one that needs no marker: this draft's rendering is already on the
    // issue, whichever wording published it. It is what closes the pre-0.15
    // history — 14 Agent Briefs on ofmchat published under the shared wording —
    // without a migration, and it is also the literal shape of the reported
    // hazard: a leftover draft, re-published word for word.
    const at = hit => `${hit.createdAt || 'undated'} ${hit.url}`;
    let already = null;
    if (tracker.verbatim.length > 0) {
      already = { what: `this exact draft, word for word — ${at(tracker.verbatim[0])}`, read: 'read the comment that already carries it' };
    } else if (tracker.mine.length > 0) {
      const newest = tracker.mine[tracker.mine.length - 1];
      already = { what: `${tracker.mine.length} AI-published comment(s) for this job — the newest is ${at(newest)}`, read: 'read the pass that already landed' };
    }
    if (already !== null) {
      if (!republish) {
        bad(`#${issue} already carries ${already.what}`);
        fix(`gh issue view ${issue} --repo ${slug} --comments # ${already.read}`);
        fix(`ax triage publish --issue ${issue} --job ${job} --pass ${pass} --repo ${slug} --republish # only if this draft must supersede it, on purpose`);
        blocked = true;
        continue;
      }
      note(`#${issue} --republish over ${already.what}`);
    }
    // The stale-view warning, and it is a WARNING because the issue moving is
    // ordinary — a label edit, the orchestrator's own amendment — and only the
    // operator knows whether the move changed the verdict. It exists because
    // #98's root cause was upstream of ax and undetectable from inside the
    // draft: OMP's `issue://98` resource served a snapshot from 08-27 for an
    // issue mutated on 08-28, so a full verdict was authored against a view that
    // predated the one already published. That mismatch IS readable here.
    const wrote = writtenAt(draft.path);
    if (tracker.movedAt !== null && wrote !== null && tracker.movedAt > wrote) {
      warn(
        `#${issue} moved after this draft was written — issue ${new Date(tracker.movedAt).toISOString()}, draft ${new Date(wrote).toISOString()}. ` +
          `Read \`gh issue view ${issue} --repo ${slug} --comments\` before landing a verdict authored against an older view.`,
      );
    }
    note(`#${issue} ${draft.labels.length} label(s) ${dim(draft.labels.join(', '))}`);
    if (draft.labels.includes(READY_LABEL)) note('  ^ this publication is what makes the issue agent-grabbable');
    if (draft.remove.length > 0) note(`  ^ removing ${dim(draft.remove.join(', '))} in the same edit`);
    if (draft.close) note('  ^ this draft recommends closing — publish applies the labels and the comment, and leaves the issue OPEN');

    // Free text never touches argv. A verdict is multi-line prose written by an
    // agent and edited by a human — quotes, backticks, code fences and all — and
    // argv is the one channel that mangles exactly that. So the body is rendered
    // to a file and handed over as a path.
    //
    // It is rendered HERE, in the loop that can still refuse: a render that fails
    // after `gh issue edit` has run leaves the labels applied and the comment
    // missing, which is the half-landed state this batch is ordered to avoid.
    // ONE `gh issue edit` carries both directions, and that is one INVOCATION,
    // not one transaction. Read the claim this comment used to make, because it
    // was wrong: `gh` runs the two label directions as two concurrent GraphQL
    // mutations in an errgroup (`pkg/cmd/pr/shared/editable_http.go`, `UpdateIssue`
    // → `addLabels` / `removeLabels`), so `--add-label` and `--remove-label` are
    // NOT one API call and nothing here makes them atomic.
    //
    // It is still the right shape, for a reason worth keeping straight: GitHub
    // offers no atomic add-and-remove. `addLabelsToLabelable` and
    // `removeLabelsFromLabelable` are separate mutations, and gh chose that split
    // deliberately — its own comment says "to avoid having to replace the entire
    // list of labels and risking race conditions". The only single-mutation
    // alternative is `updateIssue(labelIds: …)`, which REPLACES the whole set and
    // therefore clobbers any concurrent label change. One invocation is the best
    // available; two invocations would merely add a second window for no gain.
    //
    // What follows from that is the refusal below, not this argv.
    const labels = [
      'issue',
      'edit',
      issue,
      '--repo',
      slug,
      ...draft.labels.flatMap(label => ['--add-label', label]),
      ...draft.remove.flatMap(label => ['--remove-label', label]),
    ];
    const bodyPath = `${draft.path.slice(0, -'.md'.length)}.body.md`;
    const body = `${DISCLAIMER_BY_JOB[job]}\n\n${draft.body}\n`;
    if (!dry) {
      try {
        writeFileSync(bodyPath, body);
      } catch (error) {
        bad(`#${issue} the comment could not be rendered to ${bodyPath}: ${String(error.code ?? error.message ?? error)}`);
        blocked = true;
        continue;
      }
    }
    // Whether a dispatch record can ADDRESS this pass's pane, decided here with
    // the store already in hand: the release hint after the mutation must never
    // name a gesture that is guaranteed to refuse, and a hand-written pass has
    // no record — `triage release` would answer "no dispatch record" every time.
    let releasable = false;
    if (recorded.includes(pass)) {
      try {
        releasable = typeof report(join(store, `${requestFor({ ...base, pass })}.json`)).summary?.dispatchId === 'string';
      } catch {
        releasable = false;
      }
    }
    ready.push({ issue, pass, releasable, draft, labels, bodyPath, lines: body.split('\n').length });
  }

  if (blocked) return refuse('nothing was published — one draft per issue, complete and rendered, before the first gh call');

  // ── the mutation, per issue ───────────────────────────────────────────────
  //
  // Two orders, and what selects between them is what the publication DOES,
  // not which lane asked for it:
  //
  //   ordinary — labels FIRST, then the comment. A comment whose label set
  //   never applied reads to the next human as a finished pass.
  //
  //   applying `ready-for-agent` — the comment FIRST, the labels AFTER. Here
  //   the label is an automation trigger: an AFK launcher dispatches on
  //   `ready-for-agent` plus the Agent Brief, so a label-then-failed-comment
  //   would expose a briefless ready signal that cannot be retracted once a
  //   launcher consumed it. An orphan brief with no label is visible but not
  //   runnable, which is the safe direction for a partial failure. This used to
  //   be keyed on the retired readiness lane, which was the only publisher of
  //   that label; a `brief` draft naming it in its own `Labels:` line ran the
  //   label-first order and had the hazard the whole time.
  let failed = 0;
  for (const { issue, pass, releasable, draft, labels, bodyPath, lines } of ready) {
    section(`issue #${issue}`);
    const commentFirst = draft.labels.includes(READY_LABEL);

    if (dry) {
      if (commentFirst) {
        note(`would post ${lines} line(s), rendered from ${draft.path}`);
        note(`then would run: gh ${labels.join(' ')}`);
      } else {
        note(`would run: gh ${labels.join(' ')}`);
        note(`would post ${lines} line(s), rendered from ${draft.path}`);
      }
      continue;
    }

    if (commentFirst) {
      const posted = gh(['issue', 'comment', issue, '--repo', slug, '--body-file', bodyPath]);
      if (posted.error || posted.status !== 0) {
        bad(`#${issue} the comment refused — ${firstLine(posted.stderr) || `exit ${posted.status}`}`);
        // The COMMENT state is indeterminate: a transport error can surface
        // after GitHub already created it, so "refused" does not prove absent
        // and a blind re-post would duplicate the brief. What IS proven is the
        // half that matters: no label was applied on this branch, so no
        // launcher can act on a briefless ready signal.
        note('  ^ the comment may still have landed server-side; no label was applied either way');
        fix(`gh issue view ${issue} --repo ${slug} --json comments --jq '.comments[-1].body' # did it land?`);
        fix(`gh ${labels.join(' ')} # if it landed, only the labels are missing`);
        fix(`ax triage publish --issue ${issue} --job ${job} --pass ${pass} # only if it did NOT land`);
        failed = 1;
        continue;
      }
      const applied = gh(labels);
      if (applied.error || applied.status !== 0) {
        bad(`#${issue} comment posted, labels refused — ${firstLine(applied.stderr) || `exit ${applied.status}`}`);
        fix(`gh ${labels.join(' ')} # the comment is already posted — a publish re-run would duplicate it`);
        failed = 1;
        continue;
      }
      note(`published — the comment, then ${draft.labels.length} label(s) including ${READY_LABEL}`);
      if (releasable) note(dim(`ax triage release --issue ${issue} --job ${job} --pass ${pass}   # this comment IS the landing proof release needs`));
      continue;
    }

    const applied = gh(labels);
    if (applied.error || applied.status !== 0) {
      bad(`#${issue} labels refused — ${firstLine(applied.stderr) || `exit ${applied.status}`}`);
      // The label state is INDETERMINATE here, and saying "nothing was posted"
      // alone invites a blind retry. gh's errgroup returns the FIRST error, so
      // the other direction may have landed: the issue can now hold both state
      // labels, neither, or the right one behind an unrelated failure.
      note('  ^ the add and the remove are two concurrent mutations, so one of them may have landed');
      fix(`gh issue view ${issue} --repo ${slug} --json labels # read the state before retrying anything`);
      fix(`gh ${labels.join(' ')} # no comment was posted for this issue`);
      failed = 1;
      continue;
    }
    // The comment goes second, and only after the labels landed: a comment
    // whose label set never applied reads to the next human as a finished pass.
    const posted = gh(['issue', 'comment', issue, '--repo', slug, '--body-file', bodyPath]);
    if (posted.error || posted.status !== 0) {
      bad(`#${issue} labels applied, comment refused — ${firstLine(posted.stderr) || `exit ${posted.status}`}`);
      fix(`gh issue comment ${issue} --repo ${slug} --body-file ${bodyPath} # the labels are already on`);
      failed = 1;
      continue;
    }
    note(`published — ${draft.labels.length} label(s) and one comment`);
    // The next gesture, ready to paste, offered HERE and not in `status`: the
    // comment that just landed is exactly the artifact `worker release` demands
    // for a triage pane (a comment on the issue AFTER the dispatch), so the
    // command below is one whose proof exists by construction. `status` cannot
    // see publication without a per-issue probe, and offering it there printed
    // a command that refused every time under the deferred-publish wave.
    if (releasable) note(dim(`ax triage release --issue ${issue} --job ${job} --pass ${pass}   # this comment IS the landing proof release needs`));
    if (draft.close) note('the draft recommended closing: that is yours to do, and this verb never does it');
  }
  return failed;
}

const firstLine = text => String(text ?? '').split('\n')[0].trim();

/**
 * How many labels one `gh label list` is asked for. `gh` paginates up to this
 * and then stops SILENTLY, which is why the cap is read back below rather than
 * trusted.
 */
const LABEL_CAP = 500;

/**
 * Every label this repository actually has, or `null` when `gh` could not say.
 *
 * This exists because ax cannot know what a label name looks like. GitHub allows
 * spaces, arrows and parentheses, so no local pattern can separate a real name
 * from a child's improvised prose — and three of three drafts measured on
 * 2026-08-22 improvised differently. The repository's own list is the only
 * authority, and asking it is one call for a whole batch.
 *
 * `null` is not an empty set: an unreachable `gh` must not read as "no label
 * exists", which would refuse every draft. It is a NAMED inability instead.
 *
 * And a FULL page is the same kind of inability, for the same reason a partial
 * `terminal list` cannot prove a pane is dead (`pane.mjs`). This check exists to
 * decide ABSENCE, and a list that stopped at the cap cannot establish one: the
 * missing name and the never-existing name read identically. Measured on the
 * repository that prompted this: 34 labels against a cap of 500, so the branch
 * is unreachable today and is written for the repo where it is not.
 *
 * The list is asked of `slug` EXPLICITLY, never of the checkout `gh` happens to
 * sit in. `--repo <owner/repo>` makes every mutation below target a repository
 * that is not this one, and a preflight read against the wrong vocabulary is
 * worse than none: it refuses names the target has, and passes names it does not.
 */
function repoLabels(gh, slug) {
  const out = gh(['label', 'list', '--repo', slug, '--limit', String(LABEL_CAP), '--json', 'name']);
  if (out.error || out.status !== 0) return null;
  try {
    const parsed = JSON.parse(String(out.stdout ?? ''));
    if (!Array.isArray(parsed)) return null;
    const names = new Set(parsed.map(entry => String(entry?.name ?? '')).filter(name => name !== ''));
    return { names, truncated: parsed.length >= LABEL_CAP };
  } catch {
    return null;
  }
}

/**
 * What the tracker already carries for this draft, and when the issue last moved.
 *
 * Two answers, because they hold different halves:
 *
 *   `mine` — comments carrying THIS job's disclaimer. The marker is per-job for
 *   exactly this reason (`DISCLAIMER_BY_JOB`), so a landed Agent Brief never
 *   reads as a landed verdict and no rule has to count comments to guess which
 *   is which. This is the forward-looking gate.
 *
 *   `verbatim` — comments that ARE this draft's published rendering under any of
 *   ax's wordings. Job-blind on purpose: it is what recognizes a publication
 *   made before the wordings split, and it needs no marker to be legible. It is
 *   also the exact hazard a leftover draft carries — re-publishing the same
 *   bytes — so it is a string comparison and never an inference.
 *
 *   `carried` — the label NAMES the issue wears right now. Read on this same
 *   call rather than a second one, so a batch pays nothing new for it: it is
 *   what lets a directive be graded against the issue instead of against the
 *   repository's vocabulary, which knows which labels exist and nothing about
 *   which are on this issue (#101).
 *
 * Every way `gh` fails to answer returns `ok: false` with the reason, and the
 * caller refuses on it. An unreadable issue is an inability to establish absence,
 * never an issue with nothing on it (F-028) — and the absence being established
 * here is the one that authorizes a mutation. That is why a missing `labels`
 * array is a refusal and not an empty set. An answer that IS readable and
 * carries an empty `comments` or `labels` array is a real answer, and it
 * authorizes.
 */
function trackerState(gh, { slug, issue, marker, body }) {
  const unknown = reason => ({ ok: false, reason, mine: [], verbatim: [], carried: [], movedAt: null });
  const out = gh(['issue', 'view', issue, '--repo', slug, '--json', 'comments,labels,updatedAt']);
  if (out.error) return unknown(`gh could not run: ${String(out.error.message ?? out.error)}`);
  if (out.status !== 0) return unknown(`gh refused — ${firstLine(out.stderr) || `exit ${out.status}`}`);
  let answer;
  try {
    answer = JSON.parse(String(out.stdout ?? ''));
  } catch {
    return unknown('gh answered something that is not JSON');
  }
  if (!Array.isArray(answer?.comments)) return unknown(`gh answered no comments array for #${issue}`);
  if (!Array.isArray(answer?.labels)) return unknown(`gh answered no labels array for #${issue}, so what this issue carries could not be read`);
  const movedAt = Date.parse(String(answer?.updatedAt ?? ''));
  const published = RENDERINGS.map(disclaimer => normalize(`${disclaimer}\n\n${body}`));
  const where = comment => ({ url: String(comment?.url ?? ''), createdAt: String(comment?.createdAt ?? '') });
  return {
    ok: true,
    mine: answer.comments.filter(comment => String(comment?.body ?? '').includes(marker)).map(where),
    verbatim: answer.comments.filter(comment => published.includes(normalize(comment?.body))).map(where),
    movedAt: Number.isFinite(movedAt) ? movedAt : null,
    carried: answer.labels.map(label => String(label?.name ?? '')).filter(name => name !== ''),
  };
}

/**
 * When this draft was last written, or `null` when that cannot be read. The
 * mtime is the right clock: an orchestrator's own correction moves it, so the
 * comparison is against the newest authorship rather than the dispatch date.
 */
function writtenAt(path) {
  try {
    return statSync(path).mtimeMs;
  } catch {
    return null;
  }
}
/**
 * Can a newer pass still be writing? Built lazily, because the answer costs an
 * Orca round-trip and the ordinary publish never needs it.
 *
 * Fail-closed on every read it cannot complete: this decides whether to land a
 * verdict under a child that may be replacing it, and that is not a call to make
 * on a partial inventory. `judge` returns the first pass that is not provably
 * finished, or `null` when every one of them is.
 */
function livenessProbe({ resolve, runner, exec, env, store }) {
  const bin = runner ? null : resolve({ env });
  if (!runner && bin === null) return { ok: false, reason: 'no Orca CLI on this machine, so no pane can be read' };
  const run = runner ?? createRunner({ bin, exec });
  const ready = runtimeReady(run);
  if (!ready.ready) return { ok: false, reason: ready.reason };

  const inventory = terminalInventory(run);
  if (!inventory.ok) return { ok: false, reason: inventory.reason };
  const index = dispatchIndex(store);
  if (!index.missing && index.reason !== '') return { ok: false, reason: `the dispatch store ${store} cannot be read: ${index.reason.slice(0, 160)}` };
  const handlesOf = handlesByRequest(index);

  return {
    ok: true,
    judge(entries) {
      for (const { pass, request } of entries) {
        const handles = [...(handlesOf.get(request) ?? [])];
        // Same rule as `dispatch --fresh`: no recorded handle is not a dead pane,
        // it is nothing to read — which is what the null case answers.
        const probed = handles.length === 0 ? [null] : handles;
        const why = `pass ${pass} has no pane recorded against it, so nothing here can say whether its child is done`;
        for (const handle of probed) {
          const verdict = paneVerdict(handle, why, inventory);
          if (verdict.pane !== 'MORT') return { pass, ...verdict };
        }
      }
      return null;
    },
  };
}
