// `ax triage publish` — the one place a triage verdict reaches the tracker.
//
// A triage child writes a draft and mutates nothing, so the mutation has to
// happen somewhere. Leaving it to the operator's own `gh` calls is not a smaller
// surface, it is an untested one — and it is precisely the failure this whole
// noun is paid for: on 2026-08-10 four issues landed with three empty label
// groups each, because applying five groups by hand is data entry and data entry
// gets skipped.
//
// So this verb is narrow and unfriendly on purpose:
//
//   * it applies EXACTLY what the draft names, and refuses a draft that names
//     nothing — it never composes, never guesses a missing group
//   * it reads every draft before the first `gh` call, so a batch cannot land
//     half applied
//   * it NEVER closes an issue. A child may recommend wontfix; closing is the
//     one gesture the reporter is owed by a human
//   * a `custom` job is not publishable at all, by name: its draft is a report
//     to you, not a tracker mutation

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRunner, resolveOrca, runtimeReady } from '../orca-bin.mjs';
import { repoPaths } from '../config.mjs';
import { bad, dim, fix, note, raw, section } from '../log.mjs';
import { redactSecrets } from '../redact.mjs';
import { defaultExec } from '../worker/release.mjs';
import { defaultStore, dispatchIndex, handlesByRequest } from '../worker/record.mjs';
import { terminalInventory } from '../worker/pane.mjs';
import { paneVerdict } from '../worker/ls.mjs';
import { DRAFT_DIR, passesIn, passesOf, readDraft, requestFor } from './draft.mjs';

const USAGE = 'ax triage publish --issue N [--issue M …] [--job triage|brief] [--pass N] [--repo <owner/repo>] [--dry-run]';

/** The disclaimer every AI-written comment on the tracker has to carry. */
const DISCLAIMER = '> *This was generated by AI during triage.*';

export function publish(argv = [], { exec = defaultExec, env = process.env, cwd = process.cwd(), resolve = resolveOrca, runner } = {}) {
  const usageError = message => {
    process.stderr.write(`ax triage publish: ${message}\n${USAGE}\n`);
    return 2;
  };
  const refuse = (message, repair) => {
    bad(redactSecrets(message));
    if (repair) fix(redactSecrets(repair));
    return 1;
  };

  const issues = [];
  let job = 'triage';
  let repo = '';
  let dry = false;
  let wantPass = '';

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const value = () => argv[(i += 1)] ?? '';
    if (arg === '--issue') issues.push(value());
    else if (arg === '--job') job = value();
    else if (arg === '--repo') repo = value();
    else if (arg === '--dry-run') dry = true;
    else if (arg === '--pass') wantPass = value();
    else if (arg === '-h' || arg === '--help') return (raw(`${USAGE}\n`), 0);
    else return usageError(`unknown argument "${arg}"`);
  }

  if (issues.length === 0) return usageError('no --issue given');
  for (const issue of issues) {
    if (!/^[1-9][0-9]*$/.test(issue)) return usageError(`--issue expects a number, got "${issue}"`);
  }
  if (job === 'custom') {
    return refuse(
      'a custom job is not publishable: its draft is a report to you, not a tracker mutation — it names a finding, not a label set',
      'read the draft, and if it concluded something the tracker should carry, run a triage or brief job for it',
    );
  }
  if (!['triage', 'brief'].includes(job)) return usageError(`--job expects triage|brief, got "${job}"`);

  const paths = repoPaths(cwd);
  if (!paths.root) return refuse('not inside a git repository — the drafts live in this checkout');
  const gh = args => exec('gh', args, paths.root);
  const slug = repo || resolveRepo(gh);
  if (slug === '') return refuse('could not resolve the current repository', 'ax triage publish --repo <owner>/<repo>');

  // The repository's own vocabulary, read ONCE for the batch and before any
  // mutation — a name this list does not carry is refused here rather than
  // discovered by `gh` halfway through a batch.
  const known = repoLabels(gh);
  if (known === null) {
    return refuse(
      'gh could not list this repository\'s labels, so no name in any draft can be checked — and an unchecked remove is the one mistake that does not undo',
      `gh label list --repo ${slug} # then re-run once it answers`,
    );
  }
  if (known.truncated) {
    return refuse(
      `gh returned ${LABEL_CAP} labels, exactly the cap it was asked for, so this list may be missing names — and a name missing from a truncated list reads identically to one this repository does not have`,
      `gh label list --repo ${slug} --limit 5000 # confirm the names by hand, then raise LABEL_CAP in ax`,
    );
  }

  // ── every draft read before the first mutation ────────────────────────────
  section(`drafts — ${slug} (job: ${job})`);
  const ready = [];
  let blocked = false;
  // Which PASS lands, decided per issue and always said out loud.
  //
  // Newest by default: once a second pass exists, that is what "the verdict on
  // this ticket" means. Naming an older one with `--pass N` IS the permission to
  // publish it — what is refused is naming a pass nobody wrote.
  //
  // The one hard gate is a NEWER pass whose child may still be working. It costs
  // an Orca round-trip, so it is paid ONLY on the `--pass <older>` path: with no
  // flag there is no newer pass by construction, and the ordinary publish stays
  // a `gh`-only verb that works with the runtime down.
  if (wantPass !== '' && !/^[1-9][0-9]*$/.test(wantPass)) return usageError(`--pass expects a number, got "${wantPass}"`);
  const store = defaultStore(env);
  let probe = null;
  for (const issue of issues) {
    const base = { job, repo: slug, issue };
    const written = passesIn(join(paths.root, DRAFT_DIR), base, '.md');
    const all = passesOf(store, join(paths.root, DRAFT_DIR), base);
    // Only a written pass can be published, so the default target is the newest
    // DRAFT; an unwritten newer pass shows up in `later` and forces the probe.
    const target = written.length === 0 ? 1 : written[written.length - 1];
    const pass = wantPass === '' ? target : Number(wantPass);

    if (wantPass !== '' && !written.includes(pass) && !(written.length === 0 && pass === 1)) {
      bad(`#${issue} has no pass ${pass}${written.length > 0 ? ` — it has ${written.join(', ')}` : ' and no draft at all'}`);
      fix(`ax triage status --issue ${issue} --job ${job}   # every pass this ticket has`);
      blocked = true;
      continue;
    }
    if (all.length > 1 && pass === target) note(`#${issue} passes ${all.join(', ')} — publishing ${pass}, the newest with a draft`);

    const later = all.filter(other => other > pass);
    if (later.length > 0) {
      // Built once, on the first issue that needs it.
      if (probe === null) probe = livenessProbe({ resolve, runner, exec, env, store });
      if (!probe.ok) {
        bad(`#${issue} names pass ${pass} while ${later.length} newer pass(es) exist, and their panes cannot be read: ${probe.reason}`);
        fix('orca open   # a newer child that cannot be seen must never be assumed finished (F-028)');
        blocked = true;
        continue;
      }
      const rival = probe.judge(later.map(other => ({ pass: other, request: requestFor({ ...base, pass: other }) })));
      if (rival !== null) {
        bad(`#${issue} pass ${rival.pass ?? '?'} is ${rival.pane} (${rival.detail}) — publishing pass ${pass} underneath a child that may still be writing would land a verdict already being replaced`);
        fix(`ax worker ls   # settle the newer pass first, then re-run`);
        blocked = true;
        continue;
      }
      note(`#${issue} publishing pass ${pass}; newer pass(es) ${later.join(', ')} are finished`);
    }
    const draft = readDraft(paths.root, { ...base, pass });
    note(`#${issue} pass ${pass} — ${draft.sha ? `${draft.sha.slice(0, 12)} · ${draft.lines} line(s)` : 'no draft'}`);
    if (!draft.ok) {
      bad(`#${issue} ${draft.reason}`);
      if (existsSync(draft.path)) fix(`edit ${draft.path} # then re-run: publish applies exactly what it names`);
      blocked = true;
      continue;
    }
    const unknown = [...draft.labels, ...draft.remove].filter(label => !known.names.has(label));
    if (unknown.length > 0) {
      bad(`#${issue} names ${unknown.length} label(s) this repository does not have: ${unknown.join(' | ')}`);
      fix(`edit ${draft.path} # a directive carries label NAMES only — no group prefix, no justification`);
      blocked = true;
      continue;
    }
    note(`#${issue} ${draft.labels.length} label(s) ${dim(draft.labels.join(', '))}`);
    if (draft.remove.length > 0) note(`  ^ removing ${dim(draft.remove.join(', '))} in the same edit`);
    if (draft.close) note('  ^ this draft recommends closing — publish applies the labels and the comment, and leaves the issue OPEN');

    // Free text never touches argv. A verdict is multi-line prose written by an
    // agent and edited by a human — quotes, backticks, code fences and all — and
    // argv is the one channel that mangles exactly that. So the body is rendered
    // to a file and handed over as a path.
    //
    // It is rendered HERE, in the loop that can still refuse: a render that fails
    // after `gh issue edit` has run leaves the labels applied and the comment
    // missing, which is the half-landed state this batch is ordered to avoid.
    // ONE `gh issue edit` carries both directions, and that is one INVOCATION,
    // not one transaction. Read the claim this comment used to make, because it
    // was wrong: `gh` runs the two label directions as two concurrent GraphQL
    // mutations in an errgroup (`pkg/cmd/pr/shared/editable_http.go`, `UpdateIssue`
    // → `addLabels` / `removeLabels`), so `--add-label` and `--remove-label` are
    // NOT one API call and nothing here makes them atomic.
    //
    // It is still the right shape, for a reason worth keeping straight: GitHub
    // offers no atomic add-and-remove. `addLabelsToLabelable` and
    // `removeLabelsFromLabelable` are separate mutations, and gh chose that split
    // deliberately — its own comment says "to avoid having to replace the entire
    // list of labels and risking race conditions". The only single-mutation
    // alternative is `updateIssue(labelIds: …)`, which REPLACES the whole set and
    // therefore clobbers any concurrent label change. One invocation is the best
    // available; two invocations would merely add a second window for no gain.
    //
    // What follows from that is the refusal below, not this argv.
    const labels = [
      'issue',
      'edit',
      issue,
      '--repo',
      slug,
      ...draft.labels.flatMap(label => ['--add-label', label]),
      ...draft.remove.flatMap(label => ['--remove-label', label]),
    ];
    const bodyPath = `${draft.path.slice(0, -'.md'.length)}.body.md`;
    const body = `${DISCLAIMER}\n\n${draft.body}\n`;
    if (!dry) {
      try {
        writeFileSync(bodyPath, body);
      } catch (error) {
        bad(`#${issue} the comment could not be rendered to ${bodyPath}: ${String(error.code ?? error.message ?? error)}`);
        blocked = true;
        continue;
      }
    }
    ready.push({ issue, draft, labels, bodyPath, lines: body.split('\n').length });
  }

  if (blocked) return refuse('nothing was published — one draft per issue, complete and rendered, before the first gh call');

  // ── the mutation, per issue, labels and comment together ──────────────────
  let failed = 0;
  for (const { issue, draft, labels, bodyPath, lines } of ready) {
    section(`issue #${issue}`);

    if (dry) {
      note(`would run: gh ${labels.join(' ')}`);
      note(`would post ${lines} line(s), rendered from ${draft.path}`);
      continue;
    }

    const applied = gh(labels);
    if (applied.error || applied.status !== 0) {
      bad(`#${issue} labels refused — ${firstLine(applied.stderr) || `exit ${applied.status}`}`);
      // The label state is INDETERMINATE here, and saying "nothing was posted"
      // alone invites a blind retry. gh's errgroup returns the FIRST error, so
      // the other direction may have landed: the issue can now hold both state
      // labels, neither, or the right one behind an unrelated failure.
      note('  ^ the add and the remove are two concurrent mutations, so one of them may have landed');
      fix(`gh issue view ${issue} --repo ${slug} --json labels # read the state before retrying anything`);
      fix(`gh ${labels.join(' ')} # no comment was posted for this issue`);
      failed = 1;
      continue;
    }
    // The comment goes second, and only after the labels landed: a comment
    // whose label set never applied reads to the next human as a finished pass.
    const posted = gh(['issue', 'comment', issue, '--repo', slug, '--body-file', bodyPath]);
    if (posted.error || posted.status !== 0) {
      bad(`#${issue} labels applied, comment refused — ${firstLine(posted.stderr) || `exit ${posted.status}`}`);
      fix(`gh issue comment ${issue} --repo ${slug} --body-file ${bodyPath} # the labels are already on`);
      failed = 1;
      continue;
    }
    note(`published — ${draft.labels.length} label(s) and one comment`);
    if (draft.close) note('the draft recommended closing: that is yours to do, and this verb never does it');
  }
  return failed;
}

const firstLine = text => String(text ?? '').split('\n')[0].trim();

function resolveRepo(gh) {
  const out = gh(['repo', 'view', '--json', 'nameWithOwner', '-q', '.nameWithOwner']);
  if (out.error || out.status !== 0) return '';
  return String(out.stdout ?? '').trim().split('\n')[0] ?? '';
}

/**
 * How many labels one `gh label list` is asked for. `gh` paginates up to this
 * and then stops SILENTLY, which is why the cap is read back below rather than
 * trusted.
 */
const LABEL_CAP = 500;

/**
 * Every label this repository actually has, or `null` when `gh` could not say.
 *
 * This exists because ax cannot know what a label name looks like. GitHub allows
 * spaces, arrows and parentheses, so no local pattern can separate a real name
 * from a child's improvised prose — and three of three drafts measured on
 * 2026-08-22 improvised differently. The repository's own list is the only
 * authority, and asking it is one call for a whole batch.
 *
 * `null` is not an empty set: an unreachable `gh` must not read as "no label
 * exists", which would refuse every draft. It is a NAMED inability instead.
 *
 * And a FULL page is the same kind of inability, for the same reason a partial
 * `terminal list` cannot prove a pane is dead (`pane.mjs`). This check exists to
 * decide ABSENCE, and a list that stopped at the cap cannot establish one: the
 * missing name and the never-existing name read identically. Measured on the
 * repository that prompted this: 34 labels against a cap of 500, so the branch
 * is unreachable today and is written for the repo where it is not.
 */
function repoLabels(gh) {
  const out = gh(['label', 'list', '--limit', String(LABEL_CAP), '--json', 'name']);
  if (out.error || out.status !== 0) return null;
  try {
    const parsed = JSON.parse(String(out.stdout ?? ''));
    if (!Array.isArray(parsed)) return null;
    const names = new Set(parsed.map(entry => String(entry?.name ?? '')).filter(name => name !== ''));
    return { names, truncated: parsed.length >= LABEL_CAP };
  } catch {
    return null;
  }
}
/**
 * Can a newer pass still be writing? Built lazily, because the answer costs an
 * Orca round-trip and the ordinary publish never needs it.
 *
 * Fail-closed on every read it cannot complete: this decides whether to land a
 * verdict under a child that may be replacing it, and that is not a call to make
 * on a partial inventory. `judge` returns the first pass that is not provably
 * finished, or `null` when every one of them is.
 */
function livenessProbe({ resolve, runner, exec, env, store }) {
  const bin = runner ? null : resolve({ env });
  if (!runner && bin === null) return { ok: false, reason: 'no Orca CLI on this machine, so no pane can be read' };
  const run = runner ?? createRunner({ bin, exec });
  const ready = runtimeReady(run);
  if (!ready.ready) return { ok: false, reason: ready.reason };

  const inventory = terminalInventory(run);
  if (!inventory.ok) return { ok: false, reason: inventory.reason };
  const index = dispatchIndex(store);
  if (!index.missing && index.reason !== '') return { ok: false, reason: `the dispatch store ${store} cannot be read: ${index.reason.slice(0, 160)}` };
  const handlesOf = handlesByRequest(index);

  return {
    ok: true,
    judge(entries) {
      for (const { pass, request } of entries) {
        const handles = [...(handlesOf.get(request) ?? [])];
        // Same rule as `dispatch --fresh`: no recorded handle is not a dead pane,
        // it is nothing to read — which is what the null case answers.
        const probed = handles.length === 0 ? [null] : handles;
        const why = `pass ${pass} has no pane recorded against it, so nothing here can say whether its child is done`;
        for (const handle of probed) {
          const verdict = paneVerdict(handle, why, inventory);
          if (verdict.pane !== 'MORT') return { pass, ...verdict };
        }
      }
      return null;
    },
  };
}
