// `ax triage status` and `ax triage publish`.
//
// `status` carries the three Bash propositions verbatim: it is READ-ONLY, an
// unsettled mutation routes to `--resume` and never to a second dispatch
// (F-001), and a settled one is reported without that instruction.
//
// `publish` has no Bash ancestor — under the Bash contract the child applied its
// own labels, which is why four issues landed on 2026-08-10 with three empty
// groups each. Every proposition here is a refusal that failure bought.

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

import { publish } from '../src/triage/publish.mjs';
import { status } from '../src/triage/index.mjs';

const REPO = 'acme/widgets';

function repo() {
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'ax-triage-')));
  execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: root });
  writeFileSync(join(root, 'ax.config.json'), JSON.stringify({ project: { name: 'widgets' }, apps: { web: 'apps/web' }, vendor: { repo: 'owner/kit' } }));
  return root;
}

const draft = (root, name, text) => {
  mkdirSync(join(root, '.scratch', 'triage'), { recursive: true });
  writeFileSync(join(root, '.scratch', 'triage', `${name}.md`), text);
  return join(root, '.scratch', 'triage', `${name}.md`);
};

/** A `gh` that records every call and answers per verb from a table. */
function fakeGh({ labels = { status: 0 }, comment = { status: 0 } } = {}) {
  const calls = [];
  return {
    calls,
    exec: (bin, args) => {
      calls.push(`${bin} ${args.join(' ')}`);
      if (args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
      if (args[1] === 'edit') return { stdout: '', stderr: '', ...labels };
      if (args[1] === 'comment') return { stdout: '', stderr: '', ...comment };
      return { status: 0, stdout: '', stderr: '' };
    },
  };
}

const capture = fn => {
  const written = [];
  const stdout = process.stdout.write;
  const stderr = process.stderr.write;
  process.stdout.write = chunk => (written.push(String(chunk)), true);
  process.stderr.write = chunk => (written.push(String(chunk)), true);
  try {
    return { code: fn(), out: written.join('') };
  } finally {
    process.stdout.write = stdout;
    process.stderr.write = stderr;
  }
};

const run = (argv, options = {}) => {
  const root = options.root ?? repo();
  const gh = options.gh ?? fakeGh(options.answers);
  const result = capture(() => publish([...argv], { exec: gh.exec, env: options.env ?? {}, cwd: root }));
  return { ...result, root, calls: gh.calls };
};

const mutations = calls => calls.filter(line => !line.includes('repo view'));

// ── publish: the mutation, and every way it refuses to make one ──────────────

test('publish applies exactly what the draft names, and posts its body', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug, priority/P2\nLabels: domains/api\n\n## Verdict\nIt reproduces on main.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  const [edit, comment] = mutations(r.calls);
  assert.match(edit, /issue edit 7 --repo acme\/widgets --add-label category\/bug --add-label priority\/P2 --add-label domains\/api/);
  // The body is a PATH on argv, never the prose itself: a verdict is multi-line
  // text with quotes and code fences, and argv is the channel that mangles it.
  const posted = /--body-file (\S+)/.exec(comment)[1];
  assert.match(readFileSync(posted, 'utf8'), /It reproduces on main\./);
});

test('every comment publish posts carries the AI disclaimer', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });
  const posted = /--body-file (\S+)/.exec(mutations(r.calls)[1])[1];
  assert.match(readFileSync(posted, 'utf8'), /> \*This was generated by AI during triage\.\*/);
});

test('a draft that names no label publishes nothing', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', '## Verdict\nLooks fine.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /names no label/);
  assert.deepEqual(mutations(r.calls), [], 'nothing reached the tracker');
});

test('a draft that was never written is named, and nothing is published', () => {
  const r = run(['--issue', '7']);
  assert.equal(r.code, 1);
  assert.match(r.out, /no draft at .*triage-acme-widgets-7\.md/);
  assert.deepEqual(mutations(r.calls), []);
});

test('one bad draft blocks the whole batch — every draft is read before the first gh call', () => {
  // Publication happens at the end of a chain, over several issues at once. A
  // batch that lands half applied is the state nobody can read afterwards.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFine.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: \n\nBroken.\n');
  const r = run(['--issue', '7', '--issue', '8'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /empty label/);
  assert.deepEqual(mutations(r.calls), [], 'not even the good issue was published');
});

test('publish NEVER closes an issue, however the draft concluded', () => {
  // The child may recommend wontfix. Closing is the one gesture the reporter is
  // owed by a human, so the verb applies the labels, posts the comment, and says
  // the close is not its to make.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: state/wontfix\nClose: yes\n\nAlready built, see src/x.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  assert.ok(
    r.calls.every(line => !line.includes('issue close')),
    'no close call, ever',
  );
  assert.match(r.out, /that is yours to do, and this verb never does it/);
});

test('a custom job is refused by name, not by an empty draft', () => {
  // Its draft is a report to the operator, not a label set — so the refusal says
  // so, instead of letting the caller read "names no label" and wonder.
  const r = run(['--issue', '7', '--job', 'custom']);
  assert.equal(r.code, 1);
  assert.match(r.out, /not publishable/);
  assert.match(r.out, /report to you/);
});

test('--dry-run shows the labels it would apply and mutates nothing', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--dry-run'], { root });

  assert.equal(r.code, 0);
  assert.match(r.out, /would run: gh issue edit 7/);
  assert.deepEqual(mutations(r.calls), []);
});

test('labels land before the comment, and a refused comment names the repair', () => {
  // A comment whose label set never applied reads to the next human as a
  // finished pass, so the order is fixed and the half-state is reported.
  const root = repo();
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { comment: { status: 1, stderr: 'rate limited' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /labels applied, comment refused/);
  // The repair is a command the operator can run verbatim, and it names the
  // rendered file rather than re-typing the prose.
  assert.match(r.out, new RegExp(`--body-file ${path.slice(0, -'.md'.length).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.body\\.md`));
});

test('a refused label call posts nothing for that issue', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/nope\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { labels: { status: 1, stderr: 'label not found' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /labels refused/);
  assert.ok(
    r.calls.every(line => !line.includes('issue comment')),
    'nothing was posted for this issue',
  );
});

test('a non-numeric --issue is refused before any draft is read', () => {
  const r = run(['--issue', 'GAP-353']);
  assert.equal(r.code, 2);
  assert.match(r.out, /expects a number/);
});

test('an unknown argument is refused', () => {
  const r = run(['--issue', '7', '--close']);
  assert.equal(r.code, 2);
  assert.match(r.out, /unknown argument "--close"/);
});

// ── status: read-only, and never a second dispatch ───────────────────────────

const runStatus = (argv, options = {}) => {
  const root = options.root ?? repo();
  const gh = options.gh ?? fakeGh();
  const result = capture(() => status([...argv], { exec: gh.exec, env: { ORCA_DISPATCH_STORE: options.store ?? join(root, 'store') }, cwd: root }));
  return { ...result, root, calls: gh.calls };
};

function record(store, request, { usable = true, repaired = false } = {}) {
  mkdirSync(store, { recursive: true });
  writeFileSync(
    join(store, `${request}.json`),
    JSON.stringify({
      request,
      createdAt: '2026-08-20T10:00:00.000Z',
      // The fact `start.mjs` persists after a CONFIRMED submission, and the only
      // thing that tells a reader a child is alive behind a `failed` Dispatch.
      ...(repaired ? { heldRepairAt: '2026-08-20T10:00:26.000Z' } : {}),
      attempts: [
        {
          n: 1,
          phases: [
            {
              name: 'worker-start',
              beganAt: '2026-08-20T10:00:00.000Z',
              exit: usable ? 0 : 1,
              receipt: usable
                ? { ok: true, result: { dispatchId: 'd-1', state: 'ready', stage: 'dispatched', effects: [{ kind: 'terminal', role: 'agent', id: 'term_child' }] } }
                : { ok: false, result: { state: 'unknown' } },
            },
          ],
        },
      ],
    }),
  );
}

test('status reports the absence of a record and of a draft, and mutates nothing', () => {
  const r = runStatus(['--issue', '7']);
  assert.equal(r.code, 0);
  assert.match(r.out, /no dispatch record/);
  assert.match(r.out, /nothing to publish yet/);
  assert.deepEqual(mutations(r.calls), [], 'status is a read');
});

test('status names an unsettled mutation and routes recovery to --resume, never to a new dispatch', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', { usable: false });
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /UNSETTLED/);
  assert.match(r.out, /--resume --request triage-acme-widgets-7/);
  assert.match(r.out, /F-001/);
});

test('a repaired held composer is never offered a --resume, because its child is running', () => {
  // Measured 2026-08-22 on the first real coordinator campaign: #50 and #51 both
  // read `RAN · failed · <handle> — UNSETTLED` and both were offered a resume,
  // while `orca terminal read` answered `status: running` on their panes and the
  // children were mid-analysis. Following that line puts a SECOND agent in a
  // working session — printed as the repair, which is the worst place for it.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', { usable: false, repaired: true });
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /UNSETTLED/, 'the record is still unsettled, and still says so');
  assert.match(r.out, /its child IS running/);
  assert.match(r.out, /ax worker transcript triage-acme-widgets-7/);
  // The COMMAND must be gone, not the word: the surviving prose names `--resume`
  // on purpose, to say which line not to type.
  assert.doesNotMatch(r.out, /ax worker start --resume/, 'the one line that would double the agent');
});

test('a settled record is reported without the recovery instruction', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /term_child/);
  assert.doesNotMatch(r.out, /--resume/);
});

test('status shows the draft once the child has written one', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = runStatus(['--issue', '7'], { root });
  assert.match(r.out, /draft .*triage-acme-widgets-7\.md/);
});

test('status reads the record for the job it was asked about', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'brief-acme-widgets-7');
  const r = runStatus(['--issue', '7', '--job', 'brief'], { root, store });
  assert.match(r.out, /request brief-acme-widgets-7/);
  assert.doesNotMatch(r.out, /no dispatch record/);
});
