// The artifact a triage job and Pass are PROVEN by, across the two verbs that
// own the two halves.
//
// `ax triage publish` stamps the attribution; `ax worker release` reads it back.
// Until #178 those halves shared nothing: publish posted a comment and release
// asked only whether the issue carried a comment newer than the dispatch, so an
// unrelated reply, another job's Agent Brief or a previous Pass's verdict all
// read as this Pass's proof — and a suffixed pass 2 request was refused as
// naming no issue at all, because the reader took the grammar apart by hand.
//
// So the propositions here are joint ones. The publication under test is
// produced by the REAL publisher, handed to the tracker stub as the comment it
// actually posted, and read by the REAL `triage release` → `worker release`
// chain, whose close mutation is observed on the Orca stub. A stubbed Release,
// or an invented comment body that matches by hand, would prove the two halves
// agree with the test rather than with each other.
//
// Offline by construction: `gh`, `git`, and the Orca runtime are all injected.

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';

import { createRunner } from '../src/orca-bin.mjs';
import { publicationIn, publicationMarker, samePublication, withoutMarker } from '../src/triage/publication.mjs';
import { publish } from '../src/triage/publish.mjs';
import { triageRelease } from '../src/triage/release.mjs';

const REPO = 'acme/widgets';

const capture = fn => {
  const written = [];
  const stdout = process.stdout.write;
  const stderr = process.stderr.write;
  process.stdout.write = chunk => (written.push(String(chunk)), true);
  process.stderr.write = chunk => (written.push(String(chunk)), true);
  try {
    return { code: fn(), out: written.join('') };
  } finally {
    process.stdout.write = stdout;
    process.stderr.write = stderr;
  }
};

// ── the vocabulary both halves read ──────────────────────────────────────────

test('an attribution names all four of repository, issue, job and Pass, or it identifies nothing', () => {
  const marker = publicationMarker({ job: 'triage', repo: REPO, issue: '7', pass: 2 });
  const found = publicationIn(`${marker}\n> *This was generated by AI during triage.*\n\nverdict\n`);
  assert.deepEqual(found, { ok: true, job: 'triage', repo: REPO, issue: '7', pass: 2 });
  assert.equal(samePublication({ job: 'triage', repo: REPO, issue: '7', pass: 2 }, found), true);
  // The identity is whole: one field off is another pass, another job, or
  // another repository's ticket — never this one.
  assert.equal(samePublication({ job: 'triage', repo: REPO, issue: '7', pass: 1 }, found), false);
  assert.equal(samePublication({ job: 'brief', repo: REPO, issue: '7', pass: 2 }, found), false);
  assert.equal(samePublication({ job: 'triage', repo: 'other/repo', issue: '7', pass: 2 }, found), false);
  assert.equal(samePublication({ job: 'triage', repo: REPO, issue: '70', pass: 2 }, found), false);
});

test('a comment with no attribution, and one whose attribution does not parse, are two different answers', () => {
  // A disclaimer alone is what every AI comment carries, including one published
  // before attribution existed: it says a robot wrote something, never which
  // pass it proves. And a marker that cannot be read is AMBIGUOUS — the one
  // state that must not fall back to "no publication", because a caller that
  // repairs an absence would post a second verdict over it.
  assert.equal(publicationIn('> *This was generated by AI during triage.*\n\nverdict\n'), null);
  assert.equal(publicationIn(''), null);
  const ragged = publicationIn('<!-- ax:publication job=triage repo=acme/widgets issue=7 -->\nverdict\n');
  assert.equal(ragged.ok, false);
  assert.equal(samePublication({ job: 'triage', repo: REPO, issue: '7', pass: 1 }, ragged), false);
});

test('two attributions in one comment identify nothing, even when the first one matches', () => {
  const mine = publicationMarker({ job: 'triage', repo: REPO, issue: '7', pass: 1 });
  const extra = publicationMarker({ job: 'triage', repo: REPO, issue: '7', pass: 2 });
  const doubled = publicationIn(`${mine}\n${extra}\nverdict\n`);
  assert.equal(doubled.ok, false);
  assert.equal(samePublication({ job: 'triage', repo: REPO, issue: '7', pass: 1 }, doubled), false);
  const ragged = publicationIn(`${mine}\n<!-- ax:publication job=triage repo=acme/widgets issue=7 -->\nverdict\n`);
  assert.equal(ragged.ok, false);
  const doubledKeys = publicationIn('<!-- ax:publication job=brief job=triage repo=acme/widgets issue=7 pass=1 -->\nverdict\n');
  assert.equal(doubledKeys.ok, false);
  assert.equal(samePublication({ job: 'triage', repo: REPO, issue: '7', pass: 1 }, doubledKeys), false);
});

test('the attribution is invisible to the bytes comparison that catches a replayed draft', () => {
  // The publisher's duplicate protection compares this draft's rendering against
  // what the tracker carries. Stamping the comment must not defeat it, and an
  // unstamped comment from before #178 must keep matching.
  const rendering = '> *This was generated by AI during triage.*\n\nverdict\n';
  const stamped = `${publicationMarker({ job: 'triage', repo: REPO, issue: '7', pass: 1 })}\n${rendering}`;
  assert.equal(withoutMarker(stamped).trim(), rendering.trim());
  assert.equal(withoutMarker(rendering).trim(), rendering.trim());
});

// ── the joint: the publisher's own comment, read by Release ───────────────────

/** A checkout with a draft per pass, and the dispatch records those passes wrote. */
function checkout({ passes = [1], job = 'triage' } = {}) {
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'ax-pub-')));
  execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: root });
  mkdirSync(join(root, '.scratch', 'triage'), { recursive: true });
  mkdirSync(join(root, 'store'), { recursive: true });
  for (const pass of passes) {
    const request = `${job}-acme-widgets-7${pass > 1 ? `-p${pass}` : ''}`;
    writeFileSync(join(root, '.scratch', 'triage', `${request}.md`), 'Labels: category/bug\n\nIt reproduces on pass ' + pass + '.\n');
    writeFileSync(
      join(root, 'store', `${request}.json`),
      JSON.stringify({
        request,
        repo: REPO,
        createdAt: '2026-08-20T10:00:00.000Z',
        attempts: [
          {
            n: 1,
            phases: [
              {
                name: 'worker-start',
                argv: ['stub-orca', 'orchestration', 'worker-start'],
                beganAt: '2026-08-20T10:00:00.000Z',
                exit: 0,
                receipt: {
                  ok: true,
                  result: { dispatchId: `ctx_p${pass}`, state: 'ready', effects: [{ kind: 'terminal', role: 'agent', id: `term_p${pass}` }] },
                },
              },
            ],
          },
        ],
      }),
    );
  }
  return root;
}

/**
 * The publisher, run for real. Returns the comment body it POSTED — read off the
 * `--body-file` it handed `gh`, which is the only place that text exists.
 */
function published(root, argv) {
  let posted = null;
  const exec = (bin, args) => {
    if (args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
    if (args[0] === 'label' && args[1] === 'list') {
      return { status: 0, stdout: JSON.stringify([{ name: 'category/bug' }, { name: 'needs-triage' }]), stderr: '' };
    }
    if (args[1] === 'view') {
      return { status: 0, stdout: JSON.stringify({ comments: [], labels: [{ name: 'needs-triage' }], updatedAt: '2020-01-01T00:00:00.000Z' }), stderr: '' };
    }
    if (args[1] === 'comment') {
      posted = readFileSync(args[args.indexOf('--body-file') + 1], 'utf8');
      return { status: 0, stdout: '', stderr: '' };
    }
    return { status: 0, stdout: '', stderr: '' };
  };
  const result = capture(() => publish([...argv, '--repo', REPO], { exec, env: {}, cwd: root, resolve: () => null }));
  assert.equal(result.code, 0, `the publisher refused, so there is no publication to prove Release with:\n${result.out}`);
  assert.ok(posted !== null, 'the publisher posted no comment');
  return posted;
}

/**
 * `ax triage release` over the real `worker release`, with the tracker answering
 * `comments` and the Orca stub recording every mutation it is asked for.
 */
function releasing(root, argv, { comments = [], prs = [] } = {}) {
  const orca = [];
  const shell = [];
  const runner = createRunner({
    bin: 'stub-orca',
    exec: (bin, args) => {
      const line = args.join(' ');
      orca.push(line);
      if (args[0] === 'status') return { status: 0, stdout: JSON.stringify({ ok: true, result: { runtime: { reachable: true } } }), stderr: '' };
      if (line.includes('worker-list')) {
        return {
          status: 0,
          stdout: JSON.stringify({
            ok: true,
            result: {
              workers: [1, 2].map(pass => ({
                dispatchId: `ctx_p${pass}`,
                workerState: 'succeeded',
                terminalState: 'retained',
                agentTerminalHandle: `term_p${pass}`,
                resource: null,
              })),
            },
          }),
          stderr: '',
        };
      }
      if (line.startsWith('terminal list')) {
        return {
          status: 0,
          stdout: JSON.stringify({
            ok: true,
            result: {
              terminals: [1, 2].map(pass => ({ handle: `term_p${pass}`, orphaned: false, worktreePath: join(root, 'ws'), executionHostId: 'local' })),
              hostScope: { hostIds: ['local'], omittedHostIds: [] },
              truncated: false,
            },
          }),
          stderr: '',
        };
      }
      if (line.startsWith('terminal read')) {
        const handle = args[args.indexOf('--terminal') + 1];
        return { status: 0, stdout: JSON.stringify({ ok: true, result: { terminal: { handle, status: 'running', latestCursor: 4, tail: [] } } }), stderr: '' };
      }
      if (line.includes('worker-release')) {
        return {
          status: 0,
          stdout: JSON.stringify({
            ok: true,
            result: {
              dispatchId: args[args.indexOf('--dispatch') + 1],
              state: 'released',
              processAction: 'closed_agent_terminal',
              archive: { source: 'terminal', status: 'captured' },
              mutation: { requestId: args[args.indexOf('--retry-request') + 1], replayed: false },
            },
          }),
          stderr: '',
        };
      }
      return { status: 1, stdout: JSON.stringify({ ok: false, error: { code: 'unexpected' } }), stderr: '' };
    },
  });
  const exec = (bin, args) => {
    shell.push([bin, ...args].join(' '));
    if (bin === 'git' && args.includes('--show-toplevel')) return { status: 0, stdout: `${root}\n`, stderr: '' };
    if (bin === 'gh' && args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
    if (bin === 'gh' && args[0] === 'issue' && args[1] === 'view') return { status: 0, stdout: JSON.stringify({ comments }), stderr: '' };
    if (bin === 'gh' && args[0] === 'pr') return { status: 0, stdout: JSON.stringify(prs), stderr: '' };
    return { status: 1, stdout: '', stderr: `stub has no answer for ${bin} ${args.join(' ')}\n` };
  };
  const result = capture(() =>
    triageRelease([...argv, '--repo', REPO], {
      exec,
      runner,
      env: { ORCA_DISPATCH_STORE: join(root, 'store') },
      cwd: root,
      sleep: () => {},
      resolve: () => null,
    }),
  );
  return { ...result, orca, shell, closed: orca.filter(line => line.includes('worker-release')) };
}

/** The comment the tracker carries, as `gh issue view --json comments` answers it. */
const onIssue = (body, createdAt = '2026-08-20T11:00:00.000Z') => ({ body, createdAt, url: 'https://github.com/acme/widgets/issues/7#issuecomment-1' });

test('a pass-2 publication made by the publisher lets Release close pass 2, and pass 1 alone does not', () => {
  const root = checkout({ passes: [1, 2] });
  const first = published(root, ['--issue', '7', '--job', 'triage', '--pass', '1']);
  const second = published(root, ['--issue', '7', '--job', 'triage', '--pass', '2']);
  assert.notEqual(first, second, 'the two passes published the same bytes, so this fixture cannot tell them apart');

  const proven = releasing(root, ['--issue', '7', '--job', 'triage', '--pass', '2'], { comments: [onIssue(second)] });
  assert.equal(proven.code, 0);
  assert.match(proven.out, /CLOSE.*triage pass 2 publication on #7/);
  assert.deepEqual(
    proven.closed.map(line => line.includes('ctx_p2')),
    [true],
    `the pass-2 pane was not the one closed:\n${proven.out}`,
  );

  // The SAME pane, the same request, and the previous pass's publication in
  // place of its own: newer than nothing here, and still not this Pass's proof.
  const stale = releasing(root, ['--issue', '7', '--job', 'triage', '--pass', '2'], { comments: [onIssue(first, '2026-08-20T12:00:00.000Z')] });
  assert.equal(stale.code, 0);
  assert.match(stale.out, /KEEP.*no triage pass 2 publication on #7/);
  assert.deepEqual(stale.closed, [], 'a pane with no publication of its own was closed');
});

test('an arbitrary later comment and another job’s publication are not this Pass’s proof', () => {
  const root = checkout({ passes: [1] });
  const brief = checkout({ passes: [1], job: 'brief' });
  const mine = published(root, ['--issue', '7', '--job', 'triage']);
  const theirs = published(brief, ['--issue', '7', '--job', 'brief']);

  const chatter = releasing(root, ['--issue', '7', '--job', 'triage'], {
    comments: [onIssue('Any update on this?', '2026-08-30T09:00:00.000Z')],
  });
  assert.match(chatter.out, /KEEP.*no triage pass 1 publication on #7/);
  assert.deepEqual(chatter.closed, []);

  const crossJob = releasing(root, ['--issue', '7', '--job', 'triage'], { comments: [onIssue(theirs, '2026-08-30T09:00:00.000Z')] });
  assert.match(crossJob.out, /KEEP.*no triage pass 1 publication on #7/);
  assert.deepEqual(crossJob.closed, []);

  // And the control: this job's own publication does close it, so the three
  // refusals above are about attribution and not about a broken fixture.
  const proven = releasing(root, ['--issue', '7', '--job', 'triage'], { comments: [onIssue(mine)] });
  assert.match(proven.out, /CLOSE.*triage pass 1 publication on #7/);
  assert.deepEqual(
    proven.closed.map(line => line.includes('ctx_p1')),
    [true],
  );
});

test('a matching publication beside an unreadable sibling still closes', () => {
  // Ambiguity is of the CANDIDATE comment: two markers in one body, or
  // duplicate identity keys, make that comment unreadable. A separate
  // historical comment that cannot be read is not this Pass's artifact and
  // does not withhold the exact, dated publication that is.
  const root = checkout({ passes: [1] });
  const mine = published(root, ['--issue', '7', '--job', 'triage']);
  const sibling = onIssue('<!-- ax:publication job=triage repo=acme/widgets issue=7 -->\nverdict\n', '2026-08-20T12:00:00.000Z');
  sibling.url = 'https://github.com/acme/widgets/issues/7#issuecomment-2';
  const r = releasing(root, ['--issue', '7', '--job', 'triage'], { comments: [onIssue(mine), sibling] });
  assert.match(r.out, /CLOSE.*triage pass 1 publication on #7/);
  assert.deepEqual(
    r.closed.map(line => line.includes('ctx_p1')),
    [true],
    `a clean publication was withheld by an unrelated malformed comment:\n${r.out}`,
  );
});

test('a custom Pass stays KEEP beside a merged pull request, and never asks about one', () => {
  // The neighbouring-PR case: the parent checkout has merged work, and a custom
  // pass has no landing artifact at all. Reading that PR as its proof would
  // close a pane whose report nobody has read.
  const root = checkout({ passes: [1], job: 'custom' });
  const r = releasing(root, ['--issue', '7', '--job', 'custom'], {
    prs: [{ number: 91, state: 'MERGED', headRefName: 'ws' }],
    comments: [onIssue('the operator replied', '2026-08-30T09:00:00.000Z')],
  });

  assert.match(r.out, /KEEP.*custom pass/);
  assert.deepEqual(r.closed, [], 'a custom pass was closed on an artifact it never produced');
  assert.deepEqual(
    r.shell.filter(line => line.startsWith('gh pr')),
    [],
    'the custom proof path consulted the parent checkout for a pull request',
  );
});
