// `ax triage status` and `ax triage publish`.
//
// `status` carries the three Bash propositions verbatim: it is READ-ONLY, an
// unsettled mutation routes to `--resume` and never to a second dispatch
// (F-001), and a settled one is reported without that instruction.
//
// `publish` has no Bash ancestor — under the Bash contract the child applied its
// own labels, which is why four issues landed on 2026-08-10 with three empty
// groups each. Every proposition here is a refusal that failure bought.

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { test } from 'node:test';

import { createRunner } from '../src/orca-bin.mjs';
import { draftPath } from '../src/triage/draft.mjs';
import { publish } from '../src/triage/publish.mjs';
import { status } from '../src/triage/index.mjs';

const REPO = 'acme/widgets';

/**
 * `provenance` declares `triage.provenance` the way a consuming repository does
 * — the group whose doctrine says a birth label is kept and never applied a
 * second time. Omitted, this project declares no provenance vocabulary and
 * publish gates nothing on carried labels.
 */
function repo({ provenance, config } = {}) {
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'ax-triage-')));
  execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: root });
  writeFileSync(
    join(root, 'ax.config.json'),
    config ??
      JSON.stringify({
        project: { name: 'widgets' },
        apps: { web: 'apps/web' },
        vendor: { repo: 'owner/kit' },
        ...(provenance ? { triage: { provenance } } : {}),
      }),
  );
  return root;
}

const draft = (root, name, text) => {
  mkdirSync(join(root, '.scratch', 'triage'), { recursive: true });
  writeFileSync(join(root, '.scratch', 'triage', `${name}.md`), text);
  return join(root, '.scratch', 'triage', `${name}.md`);
};

/** Every label the fake repository has. A name outside this set is refused locally. */
const REPO_LABELS = [
  'category/bug',
  'priority/P2',
  'domains/api',
  'state/wontfix',
  'needs-triage',
  'needs-info',
  'source:agent-found',
  'source:user-report',
  'source:roadmap',
];

/**
 * A `gh` that records every call and answers per verb from a table.
 *
 * `label list` is answered because `publish` reads the repository's vocabulary
 * before it mutates: ax cannot know what a label name looks like, so the list is
 * the only authority. `labelList` overrides it, which is how the tests exercise
 * both an unknown name and a `gh` that cannot answer at all.
 *
 * `issue view` is answered because publish reads what the tracker ALREADY
 * carries before it adds to it. The default is an issue with no comments, last
 * moved long before any draft here is written — the absences that authorize a
 * first publication — and born `needs-triage`, as every inbound issue is,
 * because a remove of a label the issue does not carry is refused in every
 * repository and the existing transitions all remove that one. `carried`
 * overrides it for the tests about redundant directives.
 */
function fakeGh({
  labels = { status: 0 },
  comment = { status: 0 },
  labelList = null,
  comments = [],
  carried = ['needs-triage'],
  updatedAt = '2020-01-01T00:00:00.000Z',
  issueView = null,
} = {}) {
  const calls = [];
  return {
    calls,
    exec: (bin, args) => {
      calls.push(`${bin} ${args.join(' ')}`);
      if (args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
      if (args[0] === 'label' && args[1] === 'list') {
        return labelList ?? { status: 0, stdout: JSON.stringify(REPO_LABELS.map(name => ({ name }))), stderr: '' };
      }
      if (args[1] === 'view') return issueView ?? { status: 0, stdout: JSON.stringify({ comments, labels: carried.map(name => ({ name })), updatedAt }), stderr: '' };
      if (args[1] === 'edit') return { stdout: '', stderr: '', ...labels };
      if (args[1] === 'comment') return { stdout: '', stderr: '', ...comment };
      return { status: 0, stdout: '', stderr: '' };
    },
  };
}

/** One comment already on the tracker, shaped like `gh issue view --json comments`. */
const onIssue = (body, over = {}) => ({
  body,
  createdAt: '2026-08-28T07:25:00.000Z',
  url: `https://github.com/${REPO}/issues/7#issuecomment-1`,
  author: { login: 'flo' },
  ...over,
});

/** What ax's own publications carry, and the one signal a re-publication is read from. */
const AI_TRIAGE = '> *This was generated by AI during triage.*';
const AI_REFINE = '> *This was generated by AI during refinement.*';

const capture = fn => {
  const written = [];
  const stdout = process.stdout.write;
  const stderr = process.stderr.write;
  process.stdout.write = chunk => (written.push(String(chunk)), true);
  process.stderr.write = chunk => (written.push(String(chunk)), true);
  try {
    return { code: fn(), out: written.join('') };
  } finally {
    process.stdout.write = stdout;
    process.stderr.write = stderr;
  }
};
/** A settled dispatch record for one PASS, with a pane handle to probe. */
function passRecord(store, request, { handle = 'term_child', dispatchId = 'd-1' } = {}) {
  mkdirSync(store, { recursive: true });
  writeFileSync(
    join(store, `${request}.json`),
    JSON.stringify({
      request,
      createdAt: '2026-08-20T10:00:00.000Z',
      attempts: [
        {
          n: 1,
          phases: [
            {
              name: 'worker-start',
              argv: ['orca', 'orchestration', 'worker-start'],
              beganAt: '2026-08-20T10:00:00.000Z',
              exit: 0,
              receipt: { ok: true, result: { dispatchId, state: 'ready', effects: [{ kind: 'terminal', role: 'agent', id: handle }] } },
            },
          ],
        },
      ],
    }),
  );
}

const receipt = result => ({ status: 0, stdout: JSON.stringify({ ok: true, result }), stderr: '' });

/** An Orca that owns the panes it is told to own, and records every argv. */
function fakeOrca({ panes = [], omitted = [], reachable = true } = {}) {
  const calls = [];
  const runner = createRunner({
    bin: 'stub-orca',
    exec: (bin, args) => {
      calls.push(args.join(' '));
      if (args[0] === 'status') return receipt({ runtime: { reachable } });
      if (args.join(' ').startsWith('terminal list')) {
        return receipt({ terminals: panes.map(handle => ({ handle })), hostScope: { omittedHostIds: omitted } });
      }
      return { status: 1, stdout: '', stderr: 'unexpected orca call' };
    },
  });
  return { runner, calls };
}

const run = (argv, options = {}) => {
  const root = options.root ?? repo();
  const gh = options.gh ?? fakeGh(options.answers);
  const orca = options.orca === undefined ? null : fakeOrca(options.orca);
  const result = capture(() =>
    publish([...argv], {
      exec: gh.exec,
      env: options.env ?? {},
      cwd: root,
      runner: orca?.runner,
      // Never a real binary: an un-injected probe must answer "no Orca here"
      // rather than reach for the one on this machine.
      resolve: () => null,
    }),
  );
  return { ...result, root, calls: gh.calls, orcaCalls: orca?.calls ?? [] };
};

// `repo view`, `label list` and `issue view` are reads: publish asks all three
// before it decides. Only what follows them can change the tracker.
const READS = ['repo view', 'label list', 'issue view'];
const mutations = calls => calls.filter(line => !READS.some(read => line.includes(read)));

// ── publish: the mutation, and every way it refuses to make one ──────────────

test('publish applies exactly what the draft names, and posts its body', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug, priority/P2\nLabels: domains/api\n\n## Verdict\nIt reproduces on main.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  const [edit, comment] = mutations(r.calls);
  assert.match(edit, /issue edit 7 --repo acme\/widgets --add-label category\/bug --add-label priority\/P2 --add-label domains\/api/);
  // The body is a PATH on argv, never the prose itself: a verdict is multi-line
  // text with quotes and code fences, and argv is the channel that mangles it.
  const posted = /--body-file (\S+)/.exec(comment)[1];
  assert.match(readFileSync(posted, 'utf8'), /It reproduces on main\./);
});

test('every comment publish posts carries the AI disclaimer', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });
  const posted = /--body-file (\S+)/.exec(mutations(r.calls)[1])[1];
  assert.match(readFileSync(posted, 'utf8'), /> \*This was generated by AI during triage\.\*/);
});

test('a draft that names no label publishes nothing', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', '## Verdict\nLooks fine.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /names no label/);
  assert.deepEqual(mutations(r.calls), [], 'nothing reached the tracker');
});

test('a draft that was never written is named, and nothing is published', () => {
  const r = run(['--issue', '7']);
  assert.equal(r.code, 1);
  assert.match(r.out, /no draft at .*triage-acme-widgets-7\.md/);
  assert.deepEqual(mutations(r.calls), []);
});

test('one bad draft blocks the whole batch — every draft is read before the first gh call', () => {
  // Publication happens at the end of a chain, over several issues at once. A
  // batch that lands half applied is the state nobody can read afterwards.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFine.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: \n\nBroken.\n');
  const r = run(['--issue', '7', '--issue', '8'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /empty label/);
  assert.deepEqual(mutations(r.calls), [], 'not even the good issue was published');
});

test('publish NEVER closes an issue, however the draft concluded', () => {
  // The child may recommend wontfix. Closing is the one gesture the reporter is
  // owed by a human, so the verb applies the labels, posts the comment, and says
  // the close is not its to make.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: state/wontfix\nClose: yes\n\nAlready built, see src/x.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  assert.ok(
    r.calls.every(line => !line.includes('issue close')),
    'no close call, ever',
  );
  assert.match(r.out, /that is yours to do, and this verb never does it/);
});

test('a custom job is refused by name, not by an empty draft', () => {
  // Its draft is a report to the operator, not a label set — so the refusal says
  // so, instead of letting the caller read "names no label" and wonder.
  const r = run(['--issue', '7', '--job', 'custom']);
  assert.equal(r.code, 1);
  assert.match(r.out, /not publishable/);
  assert.match(r.out, /report to you/);
});

test('--dry-run shows the labels it would apply and mutates nothing', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--dry-run'], { root });

  assert.equal(r.code, 0);
  assert.match(r.out, /would run: gh issue edit 7/);
  assert.deepEqual(mutations(r.calls), []);
});

test('labels land before the comment, and a refused comment names the repair', () => {
  // A comment whose label set never applied reads to the next human as a
  // finished pass, so the order is fixed and the half-state is reported.
  const root = repo();
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { comment: { status: 1, stderr: 'rate limited' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /labels applied, comment refused/);
  // The repair is a command the operator can run verbatim, and it names the
  // rendered file rather than re-typing the prose.
  assert.match(r.out, new RegExp(`--body-file ${path.slice(0, -'.md'.length).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\.body\\.md`));
});

test('a refused label call posts nothing for that issue', () => {
  // The label EXISTS here, on purpose. A name the repository does not carry is
  // refused locally now, before any call — so to prove this proposition the call
  // has to reach `gh` and be refused for a reason ax could not have predicted.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { labels: { status: 1, stderr: 'HTTP 403: Resource not accessible by integration' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /labels refused/);
  assert.ok(
    r.calls.every(line => !line.includes('issue comment')),
    'nothing was posted for this issue',
  );
});

test('a state transition asks for the removal, in the same invocation as the adds', () => {
  // Reported by the first real orchestrator campaign, 2026-08-22: publish only
  // ever built `--add-label`, so publishing a draft that moved an issue off
  // `needs-triage` left BOTH state labels on it.
  //
  // This proves ONE INVOCATION carrying both directions, and deliberately not
  // atomicity — an earlier version of this name claimed that and was wrong. `gh`
  // runs the two directions as concurrent GraphQL mutations in an errgroup, and
  // GitHub offers no atomic add-and-remove at all, so no argv here could buy
  // one. What one invocation buys is the absence of a SECOND window, plus a
  // single exit status to react to.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: needs-info\nRemove labels: needs-triage\n\nTwo rulings are missing.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  const edits = mutations(r.calls).filter(line => line.includes('issue edit'));
  assert.equal(edits.length, 1, 'one edit carries both directions');
  assert.match(edits[0], /--add-label needs-info/);
  assert.match(edits[0], /--remove-label needs-triage/);
});

test('a refused edit says the label state is indeterminate, and how to read it', () => {
  // gh's errgroup returns the FIRST error, so the other direction may have
  // landed. A refusal that only says "nothing was posted" reads as "nothing
  // changed" and invites a blind retry onto a half-applied transition.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: needs-info\nRemove labels: needs-triage\n\nTwo rulings are missing.\n');
  const r = run(['--issue', '7'], { root, answers: { labels: { status: 1, stderr: 'HTTP 502' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /may have landed/);
  assert.match(r.out, /issue view 7 .*--json labels/, 'the repair reads the state first');
  assert.ok(r.calls.every(line => !line.includes('issue comment')), 'no comment on an unknown label state');
});

test('a directive naming a label the repository does not have is refused before any call', () => {
  // Measured across the campaign's three drafts, which used three grammars. One
  // wrote `Labels: category → enhancement`; comma-split-and-trim makes that a
  // label name, and ax cannot tell it from a real one — GitHub allows arrows,
  // spaces and parentheses in a label. The repository's list can.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category → category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /does not have/);
  assert.match(r.out, /category → category\/bug/, 'the refusal quotes what it read');
  assert.deepEqual(mutations(r.calls), [], 'refused before the first mutation');
});

test('an unknown name on the REMOVE side is refused too, because a wrong remove does not undo', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\nRemove labels: needs-triage (superseded by needs-info).\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /does not have/);
  assert.deepEqual(mutations(r.calls), [], 'nothing was removed on a guess');
});

// ── what the ISSUE already carries, not just what the repository has ─────────
//
// The vocabulary check above answers which labels EXIST. It cannot answer which
// of them are on this issue, and publish held no view of that at all — so three
// published comments restated a birth `source:` label the label doctrine
// forbids adding a second time (#101), and a `Remove labels:` line naming
// something the issue does not carry was the same silent no-op in the other
// direction.

const PROVENANCE = { spec: ['source:roadmap'], inbound: ['source:agent-found', 'source:user-report'] };

test('a Labels: line naming a provenance label the issue already carries refuses', () => {
  // The reported case, verbatim: the drafts of #89, #92 and #96 each named
  // `source:agent-found` while the issue wore it from birth.
  const root = repo({ provenance: PROVENANCE });
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: category/bug, source:agent-found\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /source:agent-found/, 'the refusal names the label');
  assert.match(r.out, new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), 'and the draft line to correct');
  assert.deepEqual(mutations(r.calls), [], 'nothing was applied and nothing was posted');
});

test('a Labels: line naming a DIFFERENT provenance label than the one the issue was born with refuses', () => {
  // Review of the first draft (Codex, P1): the check compared the draft's name
  // to the same name on the issue, so `source:user-report` on an issue born
  // `source:agent-found` passed and GitHub would have carried two provenance
  // labels — the exact state the doctrine forbids ("never a second").
  const root = repo({ provenance: PROVENANCE });
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: category/bug, source:user-report\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /source:user-report/, 'the refusal names the label the draft adds');
  assert.match(r.out, /source:agent-found/, 'and the one the issue was born with');
  assert.match(r.out, new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.deepEqual(mutations(r.calls), [], 'nothing was applied and nothing was posted');
});

test('a Remove labels: line naming a label the issue does not carry refuses', () => {
  const root = repo({ provenance: PROVENANCE });
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: needs-info\nRemove labels: needs-triage\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['category/bug'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /needs-triage/);
  assert.match(r.out, new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.deepEqual(mutations(r.calls), []);
});

test('a stale Remove labels: still refuses under --republish — the directive does nothing either way', () => {
  // The cost this ruling accepted: a corrected draft re-published after the
  // earlier publication already removed `needs-triage` names a directive that
  // is now a no-op, and the repair is to delete the line.
  const root = repo({ provenance: PROVENANCE });
  draft(root, 'triage-acme-widgets-7', 'Labels: needs-info\nRemove labels: needs-triage\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--republish'], { root, answers: { carried: ['needs-info'] } });
  assert.equal(r.code, 1);
  assert.match(r.out, /needs-triage/);
  assert.deepEqual(mutations(r.calls), []);
});

test('a redundant CATEGORY name is disclosed and published — only provenance forbids a second name', () => {
  const root = repo({ provenance: PROVENANCE });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['category/bug'] } });

  assert.equal(r.code, 0);
  assert.match(r.out, /category\/bug/);
  assert.match(r.out, /already carries/, 'the run says so rather than hiding a directive that changes nothing');
  assert.equal(mutations(r.calls).length, 2, 'the publication still lands: one edit, one comment');
});

test('the redundant-provenance refusal holds under --dry-run: the read happens in the preflight', () => {
  const root = repo({ provenance: PROVENANCE });
  draft(root, 'triage-acme-widgets-7', 'Labels: source:agent-found\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--dry-run'], { root, answers: { carried: ['source:agent-found'] } });
  assert.equal(r.code, 1);
  assert.ok(!r.out.includes('would run: gh issue edit'), 'a dry run reports the refusal instead of offering to publish');
});

test('one refused issue publishes none of its siblings', () => {
  const root = repo({ provenance: PROVENANCE });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFine.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: source:agent-found\n\nRedundant.\n');
  const r = run(['--issue', '7', '--issue', '8'], { root, answers: { carried: ['source:agent-found'] } });
  assert.equal(r.code, 1);
  assert.deepEqual(mutations(r.calls), [], 'not even the good issue was published');
});

test('an issue view with no labels array is an inability to establish, not an issue with no labels', () => {
  // F-028, and the absence being established here is the one that authorizes a
  // mutation. The wording has to differ from "the issue carries it already", or
  // an operator cannot tell an unread issue from a redundant directive.
  const root = repo({ provenance: PROVENANCE });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], {
    root,
    answers: { issueView: { status: 0, stdout: JSON.stringify({ comments: [], updatedAt: '2020-01-01T00:00:00.000Z' }), stderr: '' } },
  });
  assert.equal(r.code, 1);
  assert.match(r.out, /labels/);
  assert.match(r.out, /could not be read/);
  assert.deepEqual(mutations(r.calls), []);
});

test('a repository that declares no provenance vocabulary gates no ADD, and still refuses a remove that would do nothing', () => {
  // The repository is input, and an absent declaration is not a rule (F-028):
  // the provenance gate on the add side needs a vocabulary to name provenance,
  // so it is off. The remove gate needs only the issue's live labels, which
  // publish reads regardless — so the child's promise (`spec.mjs`: "asking to
  // remove a label it does not have is refused") holds in every repository.
  // Review of the first draft (Codex, P2) caught the gate switched off wholesale.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: source:agent-found\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found'] } });
  assert.equal(r.code, 0, 'a redundant add is not graded without a vocabulary that names provenance');
  assert.equal(mutations(r.calls).length, 2);

  const path = draft(root, 'triage-acme-widgets-7', 'Labels: needs-info\nRemove labels: needs-triage\n\nIt reproduces.\n');
  const r2 = run(['--issue', '7'], { root, answers: { carried: ['category/bug'] } });
  assert.equal(r2.code, 1, 'a remove of a label the issue does not carry is refused with or without a vocabulary');
  assert.match(r2.out, /needs-triage/);
  assert.match(r2.out, new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.deepEqual(mutations(r2.calls), []);
});

// ── the declared classes are one vocabulary, and the check reads the whole
// proposed result ───────────────────────────────────────────────────────────
//
// #179. This verb composed its OWN two-class list — `spec` plus `inbound` —
// while `provenanceVerdict` and `ax frontier` already read three. An issue born
// a declared FINDING was therefore invisible to the add-side gate: a draft
// naming `source:user-report` over `source:agent-found` published, and the
// issue ended up carrying two provenance labels, which is the exact state #101
// exists to prevent.
//
// The birth comparison alone cannot see two further contradictions either — a
// draft that adds two classes to an issue carrying none, and a contradiction
// already established on the tracker that the draft merely leaves alone — so
// what is graded is the PROPOSED RESULT: carried, minus the removes, plus the
// adds.

const PROVENANCE_FINDINGS = { spec: ['source:roadmap'], inbound: ['source:user-report'], findings: ['source:agent-found'] };

test('a Labels: line adding inbound provenance to an issue born a declared FINDING refuses', () => {
  // The counter-example: the same draft the two-class list let through.
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: category/bug, source:user-report\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /source:user-report/, 'the refusal names the label the draft adds');
  assert.match(r.out, /source:agent-found/, 'and the finding the issue was born with');
  assert.match(r.out, new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), 'and the directive to correct');
  assert.deepEqual(mutations(r.calls), [], 'nothing was applied and nothing was posted');
});

test('a spec provenance label added over a birth finding refuses too — the class added is not what decides', () => {
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  draft(root, 'triage-acme-widgets-7', 'Labels: source:roadmap\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });
  assert.equal(r.code, 1);
  assert.match(r.out, /source:roadmap/);
  assert.match(r.out, /source:agent-found/);
  assert.deepEqual(mutations(r.calls), []);
});

test('a draft adding two declared classes to an issue carrying none is refused on the proposed result', () => {
  // Nothing on the issue to compare a birth label against, and the draft would
  // still land a contradiction. The refusal names both labels and the line.
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  const path = draft(root, 'triage-acme-widgets-7', 'Labels: source:roadmap, source:user-report\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['needs-triage'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /source:roadmap/);
  assert.match(r.out, /source:user-report/);
  assert.match(r.out, /spec-born/);
  assert.match(r.out, /inbound/);
  assert.match(r.out, new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), 'the draft is what has to be corrected');
  assert.deepEqual(mutations(r.calls), []);
});

test('a contradiction already on the tracker refuses even when the draft adds no source label', () => {
  // A contradictory established state is not silently valid because this draft
  // is innocent: the publication would leave the issue in it, and the repair is
  // on the tracker rather than in the draft.
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:roadmap', 'source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /source:roadmap/);
  assert.match(r.out, /source:agent-found/);
  assert.match(r.out, /gh issue edit 7 --repo acme\/widgets --remove-label source:/, 'the repair corrects the established state');
  assert.deepEqual(mutations(r.calls), []);
});

test('a draft whose Remove labels: line resolves a contradictory state publishes', () => {
  // The proposed result is what is graded, so the one draft that repairs the
  // tracker is not refused for the state it repairs.
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\nRemove labels: source:roadmap\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:roadmap', 'source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 0);
  assert.equal(mutations(r.calls).length, 2, 'one edit, one comment');
});

test('an ordinary draft that leaves a valid birth finding alone still publishes', () => {
  // The control. A declared finding is a VALID provenance: the class routes
  // passes away from a ticket, and says nothing about publishing a verdict on
  // one that was dispatched anyway.
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug, needs-info\nRemove labels: needs-triage\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 0);
  const [edit] = mutations(r.calls);
  assert.match(edit, /--add-label category\/bug --add-label needs-info --remove-label needs-triage/);
  assert.equal(mutations(r.calls).length, 2);
});

test('one provenance contradiction in a batch is found before the first mutation', () => {
  const root = repo({ provenance: PROVENANCE_FINDINGS });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFine.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: source:user-report\n\nContradictory.\n');
  const r = run(['--issue', '7', '--issue', '8'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 1);
  assert.deepEqual(mutations(r.calls), [], 'the valid sibling was not partially published');
});

test('a project that declares no findings class keeps its two-class behavior', () => {
  // The vocabulary is the project's, never a spelling this package knows: an
  // undeclared `source:agent-found` is not provenance here, so a spec label
  // joins it and publishes exactly as it did before the third class existed.
  const root = repo({ provenance: { spec: ['source:roadmap'], inbound: ['source:user-report'] } });
  draft(root, 'triage-acme-widgets-7', 'Labels: source:roadmap\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found', 'needs-triage'] } });

  assert.equal(r.code, 0, 'a label the project does not declare is not graded as provenance');
  assert.equal(mutations(r.calls).length, 2);
});

test('a provenance declaration of the wrong shape refuses, and is never read as an undeclared contract', () => {
  // A config that PARSES and declares a mapping this run cannot use is the same
  // hazard as one that does not parse: read as "no provenance declared" it
  // switches a declared gate silently off.
  const root = repo({
    config: JSON.stringify({
      project: { name: 'widgets' },
      apps: { web: 'apps/web' },
      vendor: { repo: 'owner/kit' },
      triage: { provenance: { spec: 'source:roadmap' } },
    }),
  });
  draft(root, 'triage-acme-widgets-7', 'Labels: source:user-report\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['source:agent-found'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /ax\.config\.json/);
  assert.deepEqual(mutations(r.calls), []);
});

test('a config that exists and does not parse refuses, rather than reading as "no provenance declared"', () => {
  const root = repo({ config: '{ "project": { "name": "widgets" },,,' });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });
  assert.equal(r.code, 1);
  assert.match(r.out, /ax\.config\.json/);
  assert.deepEqual(mutations(r.calls), []);
});

test('label identity is compared case-insensitively and trimmed, by the comparator the package already has', () => {
  // A config that writes `Source:Agent-Found` names the same tracker label as a
  // carried `source:agent-found`: GitHub label names are case-insensitively
  // unique, and byte-exact matching has already cost this package a wrong lane.
  const root = repo({ provenance: { inbound: [' Source:Agent-Found '] } });
  draft(root, 'triage-acme-widgets-7', 'Labels: source:agent-found\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { carried: ['SOURCE:Agent-Found'] } });
  assert.equal(r.code, 1);
  assert.match(r.out, /source:agent-found/i);
  assert.deepEqual(mutations(r.calls), []);
});

test('a draft that both applies and removes one label is a contradiction, not a transition', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: needs-info\nRemove labels: needs-info\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /both applies and removes needs-info/);
  assert.deepEqual(mutations(r.calls), [], 'gh would have accepted it and picked an order');
});

test('a gh that cannot list labels refuses the batch instead of checking nothing', () => {
  // Fail CLOSED, and say which measurement is missing. Treating an unreachable
  // `gh` as "no label exists" would refuse every draft with the wrong reason;
  // treating it as "every name is fine" would let a guessed remove through.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { labelList: { status: 1, stderr: 'gh: not authenticated' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /could not list/);
  assert.match(r.out, /unchecked remove/);
  assert.deepEqual(mutations(r.calls), [], 'no issue was touched');
});

test('a label list that came back AT the cap refuses, because absence is what it would prove', () => {
  // Same rule as a partial `terminal list` in pane.mjs: a truncated list cannot
  // establish an absence, and absence is the only thing this check decides. `gh
  // label list` stops at its cap silently, so a legitimate name past the page
  // would read exactly like one the repository does not have — a false refusal
  // that sends the operator hunting a typo that is not there.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const capped = Array.from({ length: 500 }, (_, i) => ({ name: `filler/${i}` }));
  const r = run(['--issue', '7'], { root, answers: { labelList: { status: 0, stdout: JSON.stringify(capped), stderr: '' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /exactly the cap/);
  assert.deepEqual(mutations(r.calls), [], 'no issue was touched on an unprovable absence');
});

test('--repo reads the TARGET repository\'s labels, not the checkout it is run from', () => {
  // The preflight and the mutation have to be asked of the same repository. A
  // bare `gh label list` is answered by whatever checkout the process sits in,
  // and `--repo` exists precisely to publish somewhere else — so a vocabulary
  // read from here is not merely useless against there, it is wrong in both
  // directions: it refuses names the target HAS, and passes names it does NOT.
  //
  // The two label sets below are disjoint on purpose, and the draft names a
  // label only the TARGET carries. Read the checkout and this refuses.
  const CHECKOUT_ONLY = ['category/bug'];
  const TARGET_ONLY = ['area/foreign'];
  const calls = [];
  const exec = (bin, args) => {
    calls.push(`${bin} ${args.join(' ')}`);
    // `repo view` would answer acme/widgets, as everywhere else in this file.
    if (args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
    if (args[0] === 'label' && args[1] === 'list') {
      const asked = args[args.indexOf('--repo') + 1];
      const names = asked === 'foreign/widgets' ? TARGET_ONLY : CHECKOUT_ONLY;
      return { status: 0, stdout: JSON.stringify(names.map(name => ({ name }))), stderr: '' };
    }
    // The tracker read is asked of the TARGET too — the same one-repository
    // invariant as the vocabulary above: a duplicate check against the wrong
    // issue is worse than none.
    if (args[1] === 'view') return { status: 0, stdout: JSON.stringify({ comments: [], labels: [], updatedAt: '2020-01-01T00:00:00.000Z' }), stderr: '' };
    return { status: 0, stdout: '', stderr: '' };
  };

  const root = repo();
  draft(root, 'triage-foreign-widgets-7', 'Labels: area/foreign\n\nIt reproduces on main.\n');
  const r = capture(() =>
    publish(['--issue', '7', '--repo', 'foreign/widgets'], { exec, env: {}, cwd: root, resolve: () => null }),
  );

  assert.equal(r.code, 0, r.out);
  const list = calls.find(line => line.includes('label list'));
  assert.match(list, /label list --repo foreign\/widgets /, 'the preflight named the target repository');
  assert.match(calls.find(line => line.includes('issue view')), /issue view 7 --repo foreign\/widgets /, 'so did the read of what already landed');

  // Read and mutations agree — one repository for the whole gesture.
  const targetOf = line => /--repo (\S+)/.exec(line)?.[1];
  const mutated = mutations(calls);
  assert.equal(mutated.length, 2, 'one edit and one comment');
  for (const line of mutated) assert.equal(targetOf(line), targetOf(list), line);
  assert.match(mutated[0], /issue edit 7 --repo foreign\/widgets --add-label area\/foreign/);
});

test('--repo does not let a name the TARGET lacks through, even when the checkout has it', () => {
  // The other direction of the same mistake, and the dangerous one: reading the
  // checkout would ACCEPT `category/bug` here and hand it to a repository that
  // has no such label — an unchecked name reaching the tracker is exactly what
  // the preflight is paid to prevent.
  const calls = [];
  const exec = (bin, args) => {
    calls.push(`${bin} ${args.join(' ')}`);
    if (args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
    if (args[0] === 'label' && args[1] === 'list') {
      const asked = args[args.indexOf('--repo') + 1];
      const names = asked === 'foreign/widgets' ? ['area/foreign'] : REPO_LABELS;
      return { status: 0, stdout: JSON.stringify(names.map(name => ({ name }))), stderr: '' };
    }
    return { status: 0, stdout: '', stderr: '' };
  };

  const root = repo();
  draft(root, 'triage-foreign-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = capture(() =>
    publish(['--issue', '7', '--repo', 'foreign/widgets'], { exec, env: {}, cwd: root, resolve: () => null }),
  );

  assert.equal(r.code, 1);
  assert.match(r.out, /does not have/);
  assert.match(r.out, /category\/bug/);
  assert.deepEqual(mutations(calls), [], 'nothing reached the target repository');
});

test('a non-numeric --issue is refused before any draft is read', () => {
  const r = run(['--issue', 'GAP-353']);
  assert.equal(r.code, 2);
  assert.match(r.out, /expects a number/);
});

test('an unknown argument is refused', () => {
  const r = run(['--issue', '7', '--close']);
  assert.equal(r.code, 2);
  assert.match(r.out, /unknown argument "--close"/);
});

// ── publish: an open question is a verdict not yet rendered ──────────────────

test('a draft with open Q lines refuses — the child is still asking, nothing may land', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nQ1: bug or enhancement?\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /1 open question\(s\) — an open question is a verdict not yet rendered/);
  assert.match(r.out, /ax triage status --issue 7/);
  assert.deepEqual(mutations(r.calls), [], 'nothing landed mid-escalation');
});

test('one still-asking issue refuses the whole batch — the finished sibling does not land either', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFinal verdict.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: category/bug\n\nQ1: still waiting on this.\n\nParked.\n');
  const r = run(['--issue', '7', '--issue', '8'], { root });

  assert.equal(r.code, 1);
  assert.deepEqual(mutations(r.calls), [], 'the batch is one gesture: all or nothing');
});

test('one issue named twice is refused before any read — the gate cannot see its own first comment', () => {
  // Codex, reviewing PR #33: `--issue 7 --issue 7` runs the whole preflight per
  // occurrence, so BOTH tracker reads happen before either mutation and both see
  // an untouched issue. The mutation loop then posts the same verdict twice, in
  // one invocation, with no `--republish` — the guard defeated by a repeated
  // argument. Refused rather than deduplicated: a batch that names one issue
  // twice is a typo, and silently collapsing it would also swallow the likelier
  // mistake behind it — a second number the operator meant to type differently.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--issue', '7'], { root });

  assert.equal(r.code, 2);
  assert.match(r.out, /--issue 7 given twice/);
  assert.deepEqual(r.calls, [], 'refused before even the label list — nothing was read, nothing was posted');
});

// ── publish: the verdict already on the tracker (ofmchat #98, 2026-08-29) ─────
//
// A published pass leaves a draft in `.scratch/triage/`, and that leftover is the
// NORMAL steady state of the directory — 26 of them on that day, every one
// re-publishable verbatim. So "publish it" stayed armed forever, and on #98 it
// fired: a second verdict landed under a complete lifecycle from the day before
// (verdict 07:25, amendment 07:28, Agent Brief 08:29), because a stale
// `issue://98` snapshot had shown a fresh ticket and nothing downstream doubted
// it. Two verdicts on one issue is the exact outcome the reporting project's
// doctrine forbids, and no gate here held it.
//
// The tracker is the authority for what the tracker carries: not this machine's
// release ledger, which records a pane's lifecycle and answers nothing about a
// verdict published by another session or by hand.

test('a landed verdict refuses a second one, and names both the reader and the override', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { comments: [onIssue(`${AI_TRIAGE}\n\nThe first verdict.`)] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /already carries 1 AI-published comment/);
  assert.match(r.out, /issuecomment-1/);
  assert.match(r.out, /--republish/);
  assert.deepEqual(mutations(r.calls), [], 'a duplicate verdict is refused before the first mutation');
});

test('--dry-run refuses it too — the offer to post IS the defect', () => {
  // The reproduction as reported: `--dry-run` printed "would post 76 line(s)"
  // over a published verdict, which is what an operator reads to decide.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--dry-run'], { root, answers: { comments: [onIssue(`${AI_TRIAGE}\n\nThe first verdict.`)] } });

  assert.equal(r.code, 1);
  assert.doesNotMatch(r.out, /would post/);
});

test('--republish IS the permission, and says what it is publishing over', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nThe corrected verdict.\n');
  const r = run(['--issue', '7', '--republish'], { root, answers: { comments: [onIssue(`${AI_TRIAGE}\n\nThe first verdict.`)] } });

  assert.equal(r.code, 0);
  assert.match(r.out, /--republish/);
  assert.equal(mutations(r.calls).length, 2, 'the labels and the comment still land, in that order');
});

test('a gh that cannot say what the issue carries refuses — absence is not zero', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { issueView: { status: 1, stdout: '', stderr: 'gh: not found\n' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /gh refused/);
  assert.deepEqual(mutations(r.calls), []);
});

test('an answer with no comments array is unknown, never an empty issue', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { issueView: { status: 0, stdout: JSON.stringify({ updatedAt: '2020-01-01T00:00:00.000Z' }), stderr: '' } } });

  assert.equal(r.code, 1);
  assert.match(r.out, /no comments array/);
  assert.deepEqual(mutations(r.calls), []);
});

test('one already-published issue refuses the whole batch — the fresh sibling does not land either', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFresh verdict.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: category/bug\n\nA verdict that already landed.\n');
  const gh = {
    calls: [],
    exec: (bin, args) => {
      gh.calls.push(`${bin} ${args.join(' ')}`);
      if (args[0] === 'repo') return { status: 0, stdout: `${REPO}\n`, stderr: '' };
      if (args[0] === 'label') return { status: 0, stdout: JSON.stringify(REPO_LABELS.map(name => ({ name }))), stderr: '' };
      if (args[1] === 'view') {
        const comments = args[2] === '8' ? [onIssue(`${AI_TRIAGE}\n\nAlready there.`)] : [];
        return { status: 0, stdout: JSON.stringify({ comments, updatedAt: '2020-01-01T00:00:00.000Z' }), stderr: '' };
      }
      return { status: 0, stdout: '', stderr: '' };
    },
  };
  const r = run(['--issue', '7', '--issue', '8'], { root, gh });

  assert.equal(r.code, 1);
  assert.deepEqual(mutations(gh.calls), [], 'the batch is one gesture: all or nothing');
});

test('a brief is not a verdict: it publishes over one, and only a landed brief blocks it', () => {
  // The reason each job carries its own disclaimer. Counting AI comments cannot
  // decide this: a corrected pass 2 verdict is a legitimate second one, so
  // arithmetic would refuse a FIRST brief on a twice-triaged issue and call it a
  // duplicate. The marker is the job's identity.
  const root = repo();
  mkdirSync(join(root, '.scratch', 'triage'), { recursive: true });
  writeFileSync(join(root, '.scratch', 'triage', 'brief-acme-widgets-7.md'), 'Labels: domains/api\n\nThe Agent Brief.\n');
  const verdicts = [
    onIssue(`${AI_TRIAGE}\n\nThe verdict.`),
    onIssue(`${AI_TRIAGE}\n\nThe corrected verdict.`, { url: 'https://github.com/acme/widgets/issues/7#issuecomment-2' }),
  ];

  const first = run(['--issue', '7', '--job', 'brief'], { root, answers: { comments: verdicts } });
  assert.equal(first.code, 0, 'two landed verdicts are not a landed brief');
  const posted = /--body-file (\S+)/.exec(mutations(first.calls)[1])[1];
  const brief = readFileSync(posted, 'utf8');
  assert.match(brief, /> \*This Agent Brief was generated by AI during triage\.\*/, 'a brief says which pass wrote it');
  assert.ok(!brief.includes(AI_TRIAGE), 'and it is not the verdict disclaimer, or nothing could tell the two apart');

  // Re-run over its own landed comment: the bytes are identical, so the
  // exact-draft reason is what answers — the more specific of the two.
  const again = run(['--issue', '7', '--job', 'brief'], { root, answers: { comments: [...verdicts, onIssue(brief)] } });
  assert.equal(again.code, 1);
  assert.match(again.out, /already carries this exact draft, word for word/);

  // A DIFFERENT brief on the same issue is caught by the marker instead: the
  // wording is what says a brief landed here, whatever it said.
  const other = run(['--issue', '7', '--job', 'brief'], {
    root,
    answers: { comments: [...verdicts, onIssue(`> *This Agent Brief was generated by AI during triage.*\n\nAn earlier brief, since rewritten.`)] },
  });
  assert.equal(other.code, 1);
  assert.match(other.out, /already carries 1 AI-published comment/);
});

test('a corrected pass 2 still publishes over a landed pass 1 — the repair names the exact permission, and the release hint survives it', () => {
  // The pass mechanism (`triage dispatch --fresh --because …`) exists to
  // supersede a verdict, so this guard must not make the second one
  // unpublishable. What it costs is ONE named flag, and that is the whole
  // design: pass 1's comment IS on the tracker, so pass 2 lands a second
  // verdict, and a second verdict is a gesture to make on purpose rather than
  // by re-running a command over a draft that never went away.
  const root = repo();
  const store = join(realpathSync(mkdtempSync(join(tmpdir(), 'ax-store-'))), 'store');
  passRecord(store, 'triage-acme-widgets-7');
  passRecord(store, 'triage-acme-widgets-7-p2', { dispatchId: 'd-2' });
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nThe first verdict.\n');
  draft(root, 'triage-acme-widgets-7-p2', 'Labels: category/bug\n\nWhat changed since.\n');
  const answers = { comments: [onIssue(`${AI_TRIAGE}\n\nThe first verdict.`)] };
  const env = { ORCA_DISPATCH_STORE: store };

  const refused = run(['--issue', '7'], { root, env, answers });
  assert.equal(refused.code, 1);
  assert.match(refused.out, /--pass 2 --repo acme\/widgets --republish/, 'the repair names the pass it resolved, ready to paste');
  assert.deepEqual(mutations(refused.calls), []);

  const landed = run(['--issue', '7', '--republish'], { root, env, answers });
  assert.equal(landed.code, 0);
  assert.match(landed.out, /publishing 2, the newest with a draft/);
  // The post-success hint is untouched by the gate: pass 2's own dispatch is
  // later than pass 1's comment, so that comment can never be pass 2's proof.
  assert.match(landed.out, /ax triage release --issue 7 --job triage --pass 2 {3}# this comment IS the landing proof/);
});

// ── publish: the history that predates the per-job wordings ──────────────────
//
// Measured on goodluckagency/ofmchat at the reporter's request, 2026-08-29: 14
// Agent Briefs — one each on #50-#61, #98 and #100 — were published under the
// shared triage wording. So the marker alone
// leaves a second brief armed on every one of them, and the offered repair — 14
// `gh api -X PATCH` rewrites of published comments — would have made this
// package's correctness depend on a per-repository migration the next consuming
// repo would owe again.
//
// The bytes close it instead. A leftover draft's hazard is that it re-publishes
// VERBATIM, so the comment carrying this draft's own rendering is recognizable
// under ANY of ax's wordings, with no job to infer.
//
// These fixtures model COMMENTS, never the draft directory. The two populations
// answer different questions — the leftover-draft hazard is about drafts, the
// duplicate is about comments — and on that repository they had different sizes,
// because briefs published under ax v0.5.0 left no local file under this name.

test('a brief published under the OLD shared wording still blocks its own re-publication', () => {
  const root = repo();
  mkdirSync(join(root, '.scratch', 'triage'), { recursive: true });
  const body = 'Absorbs what the pass asked for.\n\n## Acceptance\n\nThe socket reconnects.';
  writeFileSync(join(root, '.scratch', 'triage', 'brief-acme-widgets-7.md'), `Labels: domains/api\n\n${body}\n`);
  // Exactly what ofmchat #98's 08:29 comment is: an Agent Brief opening on the
  // triage disclaimer, because that is what publish rendered before the split.
  const legacy = onIssue(`> *This was generated by AI during triage.*\n\n${body}\n`);
  const r = run(['--issue', '7', '--job', 'brief'], { root, answers: { comments: [onIssue(`${AI_TRIAGE}\n\nThe verdict.`), legacy] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /already carries this exact draft, word for word/);
  assert.deepEqual(mutations(r.calls), []);
});

test('a verdict-only issue still takes its FIRST brief', () => {
  // Eleven issues in that inventory carried a verdict and no brief. Stranding
  // this publication is the failure mode the reporter worried about most, and it
  // is the one an arithmetic gate would have caused: a brief follows a verdict by
  // grammar, so the comment that verdict left must not read as a landed brief.
  const root = repo();
  mkdirSync(join(root, '.scratch', 'triage'), { recursive: true });
  writeFileSync(join(root, '.scratch', 'triage', 'brief-acme-widgets-7.md'), 'Labels: domains/api\n\nThe brief nobody has published.\n');
  const r = run(['--issue', '7', '--job', 'brief'], { root, answers: { comments: [onIssue(`${AI_TRIAGE}\n\nThe verdict.`)] } });

  assert.equal(r.code, 0);
  assert.equal(mutations(r.calls).length, 2);
});

test('a CORRECTED draft is not the landed one — the bytes decide, so an edit is publishable with --republish and refused without it', () => {
  // The two halves of the same comparison: an edited draft no longer matches the
  // comment byte for byte, so `verbatim` releases it — and the per-job marker
  // still holds it, which is what keeps an edited verdict a deliberate act
  // rather than a silent second one.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces, and here is the new evidence.\n');
  const answers = { comments: [onIssue(`${AI_TRIAGE}\n\nIt reproduces.\n`)] };

  const refused = run(['--issue', '7'], { root, answers });
  assert.equal(refused.code, 1);
  assert.match(refused.out, /already carries 1 AI-published comment/, 'not the exact-bytes reason: this draft is not what landed');

  const landed = run(['--issue', '7', '--republish'], { root, answers });
  assert.equal(landed.code, 0);
});

test('GitHub returning CRLF does not hide a verbatim republication', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces on main.\n');
  const crlf = `${AI_TRIAGE}\r\n\r\nIt reproduces on main.\r\n`;
  const r = run(['--issue', '7'], { root, answers: { comments: [onIssue(crlf)] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /word for word/);
});

// ── publish: the draft may be older than the issue it judges ─────────────────
//
// The root cause on #98 was upstream of ax — a stale `issue://98` snapshot,
// `updated 2026-08-27`, over an issue mutated on 08-28 — and it is detectable
// here without trusting the snapshot: the draft's own mtime against the issue's
// `updatedAt`. It warns rather than refuses, because the issue moving is
// ordinary (a label edit, the orchestrator's own amendment) and only the
// operator knows whether the move changed the verdict.

test('an issue that moved after the draft was written warns, and still publishes', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, answers: { updatedAt: '2126-01-01T00:00:00.000Z' } });

  assert.equal(r.code, 0);
  assert.match(r.out, /warning: #7 moved after this draft was written/);
  assert.equal(mutations(r.calls).length, 2, 'a warning is not a refusal');
});

test('a draft written after the issue last moved warns about nothing', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7', '--dry-run'], { root });

  assert.equal(r.code, 0);
  assert.doesNotMatch(r.out, /moved after/);
  // The shape an operator reads to verify a publish, unchanged by the guard.
  assert.match(r.out, /would run: gh issue edit 7/);
  assert.match(r.out, /would post \d+ line\(s\), rendered from/);
});

// ── status: read-only, and never a second dispatch ───────────────────────────

const runStatus = (argv, options = {}) => {
  const root = options.root ?? repo();
  const gh = options.gh ?? fakeGh();
  const result = capture(() =>
    status([...argv], {
      exec: gh.exec,
      env: { ORCA_DISPATCH_STORE: options.store ?? join(root, 'store'), ORCA_DISPATCH_AUTOSUBMIT_GAP: '0' },
      cwd: root,
      // A machine with no Orca unless the test says otherwise: the waiting
      // state is Orca's, and these tests must answer identically beside a live
      // runtime and on a bare CI box.
      resolve: options.resolve ?? (() => null),
      runner: options.runner,
      sleep: () => {},
    }),
  );
  return { ...result, root, calls: gh.calls };
};

/**
 * An Orca whose inbox holds exactly these messages, newest-first like the real
 * one — and whose pane cursors follow a script, for the --oneline pane states.
 */
function fakeInbox(messages, { readable = true, cursors = [] } = {}) {
  const calls = [];
  let at = 0;
  const runner = createRunner({
    bin: 'stub-orca',
    exec: (bin, args) => {
      calls.push(args.join(' '));
      if (args[0] === 'orchestration' && args[1] === 'inbox') {
        if (!readable) return { status: 1, stdout: '', stderr: 'runtime not reachable' };
        return receipt({ count: messages.length, messages });
      }
      if (args[0] === 'terminal' && args[1] === 'read') {
        const value = cursors[Math.min(at, Math.max(0, cursors.length - 1))];
        at += 1;
        if (value === undefined) return { status: 1, stdout: '', stderr: 'no cursor scripted' };
        return receipt({ terminal: { status: 'running', latestCursor: value } });
      }
      return { status: 1, stdout: '', stderr: 'unexpected orca call' };
    },
  });
  return { runner, calls };
}

function record(store, request, { usable = true, repaired = false, ask = null } = {}) {
  mkdirSync(store, { recursive: true });
  writeFileSync(
    join(store, `${request}.json`),
    JSON.stringify({
      request,
      createdAt: '2026-08-20T10:00:00.000Z',
      // The fact `start.mjs` persists after a CONFIRMED submission, and the only
      // thing that tells a reader a child is alive behind a `failed` Dispatch.
      ...(repaired ? { heldRepairAt: '2026-08-20T10:00:26.000Z' } : {}),
      // The question lifecycle `ax triage ask` writes: asking → pending |
      // answered | refused, then replying → answered.
      ...(ask ? { ask } : {}),
      attempts: [
        {
          n: 1,
          phases: [
            {
              name: 'worker-start',
              argv: ['orca', 'orchestration', 'worker-start'],
              beganAt: '2026-08-20T10:00:00.000Z',
              exit: usable ? 0 : 1,
              receipt: usable
                ? { ok: true, result: { dispatchId: 'd-1', state: 'ready', stage: 'dispatched', effects: [{ kind: 'terminal', role: 'agent', id: 'term_child' }] } }
                : { ok: false, result: { state: 'unknown' } },
            },
          ],
        },
      ],
    }),
  );
}

test('status reports the absence of a record and of a draft, and mutates nothing', () => {
  const r = runStatus(['--issue', '7']);
  assert.equal(r.code, 0);
  assert.match(r.out, /no dispatch record/);
  assert.match(r.out, /nothing to publish yet/);
  assert.deepEqual(mutations(r.calls), [], 'status is a read');
});

test('status names an unsettled mutation and routes recovery to --resume, never to a new dispatch', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', { usable: false });
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /UNSETTLED/);
  assert.match(r.out, /--resume --request triage-acme-widgets-7/);
  assert.match(r.out, /F-001/);
});

test('a repaired held composer is never offered a --resume, because its child is running', () => {
  // Measured 2026-08-22 on the first real orchestrator campaign: #50 and #51
  // both read `RAN · failed · <handle> — UNSETTLED` and both were offered a
  // resume, while `orca terminal read` answered `status: running` on their panes
  // and the children were mid-analysis. Following that line puts a SECOND agent
  // in a working session — printed as the repair, which is the worst place for
  // it.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', { usable: false, repaired: true });
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /UNSETTLED/, 'the record is still unsettled, and still says so');
  assert.match(r.out, /its child IS running/);
  assert.match(r.out, /ax worker transcript triage-acme-widgets-7/);
  // The COMMAND must be gone, not the word: the surviving prose names `--resume`
  // on purpose, to say which line not to type.
  assert.doesNotMatch(r.out, /ax worker start --resume/, 'the one line that would double the agent');
});

test('a settled record is reported without the recovery instruction', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /term_child/);
  assert.doesNotMatch(r.out, /--resume/);
});

test('status shows the draft once the child has written one', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = runStatus(['--issue', '7'], { root });
  assert.match(r.out, /draft .*triage-acme-widgets-7\.md/);
});

test('status reads the record for the job it was asked about', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'brief-acme-widgets-7');
  const r = runStatus(['--issue', '7', '--job', 'brief'], { root, store });
  assert.match(r.out, /request brief-acme-widgets-7/);
  assert.doesNotMatch(r.out, /no dispatch record/);
});

// ── status: the waiting state is Orca's, read from Orca ──────────────────────
//
// NEVER deduced from the draft: a count of `Q<n>:` lines cannot tell a child
// blocked on its ask from a child that died after writing its questions, or
// from an answer that arrived without a revision. A question is PENDING when
// Orca holds a `type: "question"` message that no other message threads back
// to — both shapes measured 2026-08-22.

const question = (over = {}) => ({
  id: 'msg_q1',
  from_handle: 'term_child',
  to_handle: 'run:run_owner',
  type: 'question',
  // A REAL `composeAsk` header: the sha is 40 hex, because that is what
  // `askHeader` parses and what decides whether `ax triage answer` can pair
  // this row at all. `draft abc` parsed as no header, so this fixture used to
  // stand for a raw `orca orchestration ask` while claiming to be an ax one.
  body: 'triage-acme-widgets-7 is blocked on the question(s) below, asked from draft 0123456789abcdef0123456789abcdef01234567. Each needs one ruling, paired by number.\nQ1: bug or enhancement?\nQ2: which priority?',
  thread_id: null,
  created_at: '2026-08-22T10:00:00Z',
  ...over,
});

test('a pass whose child is blocked on questions says WAITING, names them, and names the repair', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const orca = fakeInbox([question({ from_handle: 'term_child' })]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /WAITING since 2026-08-22T10:00:00Z on Q1-Q2 — message msg_q1/);
  assert.match(r.out, /ax triage answer --issue 7 --job triage --id msg_q1 --file/);
  assert.doesNotMatch(r.out, /waiting state unknown/);
});

test('a draft that asks with NO answerable ask says why, and names an exit that exists', () => {
  // Measured 2026-08-26: a child whose own `ax triage ask` failed
  // `dispatch_capability_invalid` asked through `orca orchestration ask`. This
  // verb printed `4 open question(s)` off the draft and nothing else; `answer`
  // refused the resulting id for carrying no ax header, and pointed back here
  // for "the pending question's real id". Four correct refusals, no exit.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  draft(root, 'triage-acme-widgets-7', 'Q1: bug or enhancement?\nQ2: which priority?\n');
  const orca = fakeInbox([]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /the draft asks 2, and no answerable ask is visible/);
  assert.match(r.out, /never asked through `ax triage ask`/);
  assert.match(r.out, /rule the questions and fold them into/);
  assert.doesNotMatch(r.out, /WAITING since/);
  // The phrase that collided with the injected child contract, where the same
  // words mean "the channel is dead" and authorise reporting with questions
  // open. Measured 2026-08-27 on ofmchat #87: a child read this line as that
  // permission and settled a pass whose ask was still pending.
  assert.doesNotMatch(r.out, /supervised reply is not available/);
});

// ── the record is the second witness (ofmchat #87, 2026-08-27) ────────────────
//
// `ax triage ask` minted a question and `--resume` proved it PENDING, while this
// verb — reading the pane mailbox alone — announced "this pane has no pending
// question — it never asked through `ax triage ask`" and told the reader to fold
// the rulings and publish. The child followed this surface and settled the pass.
// An absence from a bounded inbox is not proof that no question exists (F-028),
// so the pass's own record now answers alongside it.

test('a recorded PENDING ask is WAITING even when the mailbox shows nothing', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', {
    ask: { state: 'pending', messageId: 'msg_recorded', at: '2026-08-27T02:00:00Z' },
  });
  draft(root, 'triage-acme-widgets-7', 'Q1: bug or enhancement?\n');
  const orca = fakeInbox([]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /WAITING since 2026-08-27T02:00:00Z on message msg_recorded/);
  assert.match(r.out, /THIS PASS'S RECORD, not the mailbox/);
  assert.match(r.out, /ax triage answer --issue 7 --job triage --id msg_recorded/);
  // And the advice that destroyed the pass must be absent while it is open.
  assert.doesNotMatch(r.out, /rule the questions and fold them into/);
  assert.doesNotMatch(r.out, /supervised reply is not available/);
  assert.doesNotMatch(r.out, /never asked through/);
});

test('a record stuck at ASKING says the outcome is unknown, and never advises publishing', () => {
  // The state a process killed between the send and the write leaves behind —
  // the ofmchat #87 shape exactly, since the harness kills bash at 600s and the
  // ask default used to need 620s.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', {
    ask: { state: 'asking', at: '2026-08-27T02:00:00Z', sha: 'abc123' },
  });
  draft(root, 'triage-acme-widgets-7', 'Q1: bug or enhancement?\n');
  const orca = fakeInbox([]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /an ask was ISSUED for this pass and its outcome was never recorded/);
  assert.doesNotMatch(r.out, /rule the questions and fold them into/, 'publishing over a possibly-live question cannot be undone');
  assert.doesNotMatch(r.out, /never asked through/);
});

test('an ANSWERED record does not keep the pass looking blocked', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7', {
    ask: { state: 'answered', messageId: 'msg_done', at: '2026-08-27T02:00:00Z' },
  });
  draft(root, 'triage-acme-widgets-7', 'Q1: still written down?\n');
  const orca = fakeInbox([]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.doesNotMatch(r.out, /WAITING/);
  // A terminal lifecycle is exactly when folding by hand IS the right advice.
  assert.match(r.out, /recorded answered/);
  assert.match(r.out, /rule the questions and fold them into/);
});

test('a pass with no pane says THAT, rather than blaming the child for not asking', () => {
  const root = repo();
  const store = join(root, 'store');
  draft(root, 'triage-acme-widgets-7', 'Q1: bug or enhancement?\n');
  const orca = fakeInbox([]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /no answerable ask is visible: this pass records neither a pane nor a dispatch/);
});

test('an unreadable mailbox is named as the reason, never as the child not asking', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  draft(root, 'triage-acme-widgets-7', 'Q1: bug or enhancement?\n');
  const orca = fakeInbox([], { readable: false });
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /no answerable ask is visible: the mailbox could not be read/);
});

test('an answered question is not WAITING: the reply that threads back to it closes the row', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const orca = fakeInbox([
    { id: 'msg_a1', from_handle: 'run:run_owner', type: 'status', body: 'Q1: …\nA1: bug', thread_id: 'msg_q1', created_at: '2026-08-22T11:00:00Z' },
    question(),
  ]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.doesNotMatch(r.out, /WAITING/);
});

test('a question threaded to ITSELF is still WAITING — a self-reference is not a reply', () => {
  // THE ROOT CAUSE of the #87 contradiction, measured 2026-08-27 on this
  // machine's own mailbox: of 25 questions, 17 carried `thread_id === id`,
  // including msg_59bbc463c531 — the exact id whose `--resume` was answering
  // PENDING while this verb reported the pane had none. Orca stamps the ask's
  // own row that way; `threaded` collected every thread_id including those, so
  // a question closed itself the moment it was asked.
  //
  // A reply is another message pointing AT this one. Nothing else is.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const orca = fakeInbox([question({ id: 'msg_q1', thread_id: 'msg_q1' })]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /WAITING since 2026-08-22T10:00:00Z on Q1-Q2 — message msg_q1/);
  assert.match(r.out, /ax triage answer --issue 7 --job triage --id msg_q1/);
});

// THE PIN OUTRANKS THE PANE, and that is the point of the header. `composeAsk`
// writes the request id into the body, and `answer()` verifies exactly that
// before replying — so a row whose header names THIS pass is this pass's ask no
// matter which handle relayed it. What must never be attributed here is a row
// belonging to ANOTHER pass; that one is unpairable, and `answer` would refuse
// it with "was asked by X, not Y".
test("another pass's question is not attributed to this pass", () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const foreign = question({
    from_handle: 'term_other',
    body: 'triage-acme-widgets-99 is blocked on the question(s) below, asked from draft 0123456789abcdef0123456789abcdef01234567. Each needs one ruling, paired by number.\nQ1: bug or enhancement?',
  });
  const orca = fakeInbox([foreign]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.doesNotMatch(r.out, /WAITING/, 'a foreign pane carrying a foreign header reaches this pass by no key at all');
});

test("a question the header pins to this pass is attributed however it was relayed", () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const orca = fakeInbox([question({ from_handle: 'term_relay' })]);
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /WAITING since 2026-08-22T10:00:00Z on Q1-Q2 — message msg_q1/);
  assert.match(r.out, /ax triage answer --issue 7 --job triage --id msg_q1 --file/);
});

test('an unreadable mailbox is NAMED, never rendered as an absence of questions', () => {
  // F-028 on the reading side: status still answers from records and drafts,
  // but the gap has to be on the page — an operator deciding "nobody is
  // waiting" from this output must be able to see the ground it stands on.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const orca = fakeInbox([], { readable: false });
  const r = runStatus(['--issue', '7'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /waiting state unknown: orca orchestration inbox unreadable/);
  assert.match(r.out, /request triage-acme-widgets-7/, 'the rest of the report survives');
});

test('a machine with no Orca at all names the gap the same way', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /waiting state unknown: no Orca CLI on this machine/);
});

test('status NEVER offers the release command — the proof it needs is a published comment it cannot see', () => {
  // The hint lived here for one commit and was wrong every time under the
  // deferred-publish wave: `worker release` proves a triage landing by a
  // comment on the issue AFTER the dispatch, and a FINAL draft says nothing
  // about that. The offer now follows the publish that creates the proof.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFinal verdict.\n');
  const r = runStatus(['--issue', '7'], { root, store });

  assert.equal(r.code, 0);
  assert.doesNotMatch(r.out, /ax triage release/);
});

test('a published DISPATCHED pass is offered its release — the comment that just landed IS the proof', () => {
  const root = repo();
  const store = passStore();
  passRecord(store, 'triage-acme-widgets-7');
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root, env: { ORCA_DISPATCH_STORE: store } });

  assert.equal(r.code, 0);
  assert.match(r.out, /published — 1 label\(s\) and one comment/);
  assert.match(r.out, /ax triage release --issue 7 --job triage --pass 1   # this comment IS the landing proof/);
});

test('a published HAND-WRITTEN pass gets no release offer — there is no dispatch to address', () => {
  // The hint printed unconditionally for one commit, and for a draft with no
  // record it named a gesture guaranteed to refuse ("no dispatch record").
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  assert.match(r.out, /published — 1 label\(s\) and one comment/);
  assert.doesNotMatch(r.out, /ax triage release/);
});

test('a refused batch offers NO release anywhere — nothing landed, so nothing is provable', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFinal verdict.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: category/bug\n\nQ1: still open.\n\nParked.\n');
  const r = run(['--issue', '7', '--issue', '8'], { root });

  assert.equal(r.code, 1);
  assert.doesNotMatch(r.out, /ax triage release/);
});

// ── status --oneline: the completion view, built to be POLLED ─────────────────
//
// Measured 2026-08-23: the final report of a finished child travelled a peer
// transport that loses messages (five lost that day), nothing else signals
// completion, and the wave stalled on FINISHED work until a human noticed. A
// cheap pull is the floor that survives every transport.

test('--oneline renders one line per issue — the newest pass, its draft shape, its record', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nFinal verdict.\n');
  draft(root, 'triage-acme-widgets-8', 'Labels: x\n\nQ1: [technical] which cardinality?\n\nParked.\n');
  const r = runStatus(['--issue', '7-9', '--oneline'], { root, store });

  assert.equal(r.code, 0);
  assert.match(r.out, /#7 p1 · FINAL [0-9a-f]{12} · 4 ln · settled/);
  assert.match(r.out, /#8 p1 · ASKING Q1 · [0-9a-f]{12} · no record/);
  assert.match(r.out, /#9 — no pass/);
});

test('--oneline shows the NEWEST pass, and a pending question as WAITING with its id', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  draft(root, 'triage-acme-widgets-7', 'Labels: old\n\nPass one.\n');
  draft(root, 'triage-acme-widgets-7-p2', 'Labels: x\n\nQ1: open?\n\nParked.\n');
  const orca = fakeInbox([question({ from_handle: 'term_child', id: 'msg_p2' })]);
  const p2record = () => {
    // The newest pass owns the pane the question came from.
    record(store, 'triage-acme-widgets-7-p2');
  };
  p2record();
  const r = runStatus(['--issue', '7', '--oneline'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /#7 p2 · ASKING Q1 .* · WAITING on msg_p2/);
  assert.doesNotMatch(r.out, /p1/, 'brief is the verdict state: one line, the newest pass');
});

test('a malformed range refuses with the shape named', () => {
  assert.equal(runStatus(['--issue', '9-7']).code, 2);
  assert.equal(runStatus(['--issue', '7-']).code, 2);
});

test('an oversized range is a typo, not a wave — refused before any expansion', () => {
  // Expansion is eager and every issue pays filesystem work: unbounded, a typo
  // like 55-610000000 hangs the verb allocating six hundred million rows.
  const r = runStatus(['--issue', '55-610000000']);
  assert.equal(r.code, 2);
  assert.match(r.out, /is a typo, not a wave/);
});

test('--oneline samples the pane behind an unfinished row: QUIET is the alarm #60 needed', () => {
  // Measured 2026-08-23: #60 finished long before anyone knew — its draft
  // could not be written (the verdict lived in its scrollback) and its report
  // was the day's sixth lost peer message. "no draft · child running" was
  // indistinguishable from a child at work; the pane's cursor tells them apart.
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  const orca = fakeInbox([], { cursors: [5, 5] });
  const r = runStatus(['--issue', '7', '--oneline'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /#7 p1 · no draft · settled · pane QUIET/);
});

test('--oneline names an EMITTING pane, and never probes behind a FINAL row', () => {
  const root = repo();
  const store = join(root, 'store');
  record(store, 'triage-acme-widgets-7');
  record(store, 'triage-acme-widgets-8');
  draft(root, 'triage-acme-widgets-8', 'Labels: x\n\nFinal verdict.\n');
  const orca = fakeInbox([], { cursors: [5, 9] });
  const r = runStatus(['--issue', '7', '--issue', '8', '--oneline'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /#7 p1 · no draft · settled · pane EMITTING/);
  assert.match(r.out, /#8 p1 · FINAL [0-9a-f]{12} · 4 ln · settled$/m, 'a FINAL row costs no probe and carries no pane state');
  assert.equal(orca.calls.filter(line => line.startsWith('terminal read')).length, 2, 'one pane, two samples — the FINAL row was not probed');
});

test("--oneline probes a REMOTE pane in its recorded environment — without --on it would read UNREADABLE", () => {
  const root = repo();
  const store = join(root, 'store');
  // A record whose worker-start argv carries --on, like a remote dispatch does.
  mkdirSync(store, { recursive: true });
  writeFileSync(
    join(store, 'triage-acme-widgets-7.json'),
    JSON.stringify({
      request: 'triage-acme-widgets-7',
      createdAt: '2026-08-20T10:00:00.000Z',
      attempts: [{
        n: 1,
        phases: [{
          name: 'worker-start',
          identity: 'id-1',
          argv: ['orca', 'orchestration', 'worker-start', '--task', 'task_1', '--on', 'env_remote', '--retry-request', 'id-1', '--json'],
          exit: 0,
          receipt: { ok: true, result: { dispatchId: 'd-1', state: 'ready', stage: 'dispatched', effects: [{ kind: 'terminal', role: 'agent', id: 'term_remote' }] } },
        }],
      }],
    }),
  );
  const orca = fakeInbox([], { cursors: [5, 5] });
  const r = runStatus(['--issue', '7', '--oneline'], { root, store, runner: orca.runner });

  assert.equal(r.code, 0);
  assert.match(r.out, /pane QUIET/);
  const reads = orca.calls.filter(line => line.startsWith('terminal read'));
  assert.equal(reads.length, 2);
  for (const read of reads) assert.match(read, /--environment env_remote/, 'the recorded --on rides with every probe');
});

// ── which pass lands ─────────────────────────────────────────────────────────
//
// Once one issue can hold two verdicts, "publish it" stops being unambiguous.
// Every case below is a way the wrong one could land silently.

const passStore = () => join(realpathSync(mkdtempSync(join(tmpdir(), 'ax-store-'))), 'store');

test('with two drafts and no --pass, the NEWEST lands', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  draft(root, 'triage-acme-widgets-7-p2', 'Labels: priority/P2\n\nPass two.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  assert.match(r.out, /passes 1, 2 — publishing 2/);
  const edit = r.calls.find(line => line.includes('issue edit'));
  assert.match(edit, /--add-label priority\/P2/);
  assert.ok(!edit.includes('category/bug'), 'pass 1 did not land');
});

test('naming an older pass IS the permission to publish it', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  draft(root, 'triage-acme-widgets-7-p2', 'Labels: priority/P2\n\nPass two.\n');
  const r = run(['--issue', '7', '--pass', '1'], { root });

  assert.equal(r.code, 0);
  assert.match(r.calls.find(line => line.includes('issue edit')), /--add-label category\/bug/);
});

test('naming a pass nobody wrote is refused, and the refusal lists the ones that exist', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  draft(root, 'triage-acme-widgets-7-p2', 'Labels: priority/P2\n\nPass two.\n');
  const r = run(['--issue', '7', '--pass', '5'], { root });

  assert.equal(r.code, 1);
  assert.match(r.out, /has no pass 5 — it has 1, 2/);
  assert.ok(r.calls.every(line => !line.includes('issue edit')), 'nothing was mutated');
});

test('an UNWRITTEN newer pass with a live pane blocks the older one', () => {
  // The union case, and the reason the pass universe is records ∪ drafts: pass 2
  // has been dispatched and its child is writing right now, so it owns no `.md`
  // yet. Reading drafts alone would call pass 1 the newest and land it under a
  // child that is at that moment replacing it.
  const root = repo();
  const store = passStore();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  passRecord(store, 'triage-acme-widgets-7-p2', { handle: 'term_busy' });
  const r = run(['--issue', '7'], { root, env: { ORCA_DISPATCH_STORE: store }, orca: { panes: ['term_busy'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /pass 2 is VIVANT/);
  assert.ok(r.calls.every(line => !line.includes('issue edit')), 'nothing was mutated');
});

test('an unwritten newer pass whose pane is gone does not block the older one', () => {
  const root = repo();
  const store = passStore();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  passRecord(store, 'triage-acme-widgets-7-p2', { handle: 'term_gone' });
  const r = run(['--issue', '7'], { root, env: { ORCA_DISPATCH_STORE: store }, orca: { panes: [] } });

  assert.equal(r.code, 0);
  assert.match(r.out, /newer pass\(es\) 2 are finished/);
  assert.match(r.calls.find(line => line.includes('issue edit')), /--add-label category\/bug/);
});

test('a newer pane that cannot be read blocks the older pass, rather than being assumed finished', () => {
  // F-028 at the publishing end: an absence from a list that omits hosts is not
  // a death, and this mutation cannot be taken back.
  const root = repo();
  const store = passStore();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  passRecord(store, 'triage-acme-widgets-7-p2', { handle: 'term_elsewhere' });
  const r = run(['--issue', '7'], { root, env: { ORCA_DISPATCH_STORE: store }, orca: { panes: [], omitted: ['host_b'] } });

  assert.equal(r.code, 1);
  assert.match(r.out, /pass 2 is INCONNU/);
  assert.ok(r.calls.every(line => !line.includes('issue edit')));
});

test('with no Orca at all, a newer dispatched pass still blocks — the probe fails closed', () => {
  const root = repo();
  const store = passStore();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  passRecord(store, 'triage-acme-widgets-7-p2', { handle: 'term_busy' });
  const r = run(['--issue', '7'], { root, env: { ORCA_DISPATCH_STORE: store } });

  assert.equal(r.code, 1);
  assert.match(r.out, /no Orca CLI on this machine/);
  assert.ok(r.calls.every(line => !line.includes('issue edit')));
});

test('a newer pass that was never dispatched is not probed, because no child ever existed', () => {
  // A hand-written newer draft has no record. Probing it would refuse on an
  // absence that means nothing, and this path must not need Orca at all.
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nPass one.\n');
  draft(root, 'triage-acme-widgets-7-p2', 'Labels: priority/P2\n\nPass two.\n');
  const r = run(['--issue', '7', '--pass', '1'], { root });

  assert.equal(r.code, 0);
  assert.deepEqual(r.orcaCalls, [], 'no Orca round-trip on this path');
});

test('an ordinary publish on a single pass never reaches for Orca', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nOne pass.\n');
  const r = run(['--issue', '7'], { root });

  assert.equal(r.code, 0);
  assert.deepEqual(r.orcaCalls, []);
});

test('--pass expects a number', () => {
  const r = run(['--issue', '7', '--pass', 'latest']);
  assert.equal(r.code, 2);
  assert.match(r.out, /--pass expects a number/);
});

// ── status: the two draft states a publisher can be in ───────────────────────
// There were three while the readiness grammar existed: a NOT-READY row read a
// `ready: 'no'` verdict only that grammar produced. With it gone there are two,
// and a malformed draft must not read as anything softer.

test('status renders a publishable draft apart from an unpublishable one', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  draft(root, 'triage-acme-widgets-8', 'no directives at all\n');
  const r = runStatus(['--issue', '7-8', '--oneline'], { root });
  assert.equal(r.code, 0);
  assert.match(r.out, /#7 p1 · FINAL/);
  assert.match(r.out, /#8 p1 · NOT-PUBLISHABLE/);
  assert.doesNotMatch(r.out, /NOT-READY/, 'the retired grammar had the only producer of that row');
});

// ── publish: the brief, and the label that makes an issue grabbable ──────────
//
// `brief` is the only pass that produces a brief, so it is the only pass that
// makes an issue agent-grabbable. The label arrives through the draft's OWN
// `Labels:` directive — the child is instructed to write it (`spec.mjs`) and
// this verb applies exactly what the draft names, with no second mechanism.
//
// The ORDER flips when `ready-for-agent` is among those names, and it is keyed
// on that rather than on the job: the label is an automation trigger, an AFK
// launcher dispatches on `ready-for-agent` plus the brief, and a
// label-then-failed-comment would expose a briefless ready signal that cannot be
// retracted once a launcher consumed it. An orphan brief with no label is
// visible but not runnable, which is the safe direction for a partial failure.

const READY_LABELS = { status: 0, stdout: JSON.stringify([...REPO_LABELS, 'ready-for-agent'].map(name => ({ name }))), stderr: '' };

const BRIEF_READY = 'Labels: ready-for-agent, category/bug\nRemove labels: needs-triage\n\nSummary: wire the widget to the socket.\n';

test('a brief publishes the Agent Brief and applies ready-for-agent — the comment FIRST', () => {
  const root = repo();
  draft(root, 'brief-acme-widgets-7', BRIEF_READY);
  const r = run(['--issue', '7', '--job', 'brief'], { root, answers: { labelList: READY_LABELS } });
  assert.equal(r.code, 0);
  const [comment, edit] = mutations(r.calls);
  assert.match(comment, /issue comment 7/, 'the brief lands before the trigger label');
  assert.match(edit, /issue edit 7 --repo acme\/widgets/);
  assert.match(edit, /--add-label ready-for-agent/);
  assert.match(edit, /--add-label category\/bug/, 'the rest of the directive lands in the same edit');
  assert.match(edit, /--remove-label needs-triage/);
  const posted = /--body-file (\S+)/.exec(comment)[1];
  const body = readFileSync(posted, 'utf8');
  assert.match(body, /wire the widget to the socket/);
  assert.match(body, /This Agent Brief was generated by AI during triage/);
  assert.match(r.out, /makes the issue agent-grabbable/);
});

test('an ordinary triage publication keeps labels FIRST — the order follows the label, not the lane', () => {
  const root = repo();
  draft(root, 'triage-acme-widgets-7', 'Labels: category/bug\n\nIt reproduces.\n');
  const r = run(['--issue', '7'], { root });
  assert.equal(r.code, 0);
  const [first, second] = mutations(r.calls);
  assert.match(first, /issue edit 7/, 'a comment whose label set never applied reads as a finished pass');
  assert.match(second, /issue comment 7/);
});

test('a brief whose comment is refused applies NO label, and never promises a blind re-post', () => {
  const root = repo();
  draft(root, 'brief-acme-widgets-7', BRIEF_READY);
  const r = run(['--issue', '7', '--job', 'brief'], { root, answers: { labelList: READY_LABELS, comment: { status: 1, stderr: 'boom' } } });
  assert.equal(r.code, 1);
  assert.equal(mutations(r.calls).length, 1, 'the label edit never ran');
  assert.match(r.out, /no label was applied/);
  assert.match(r.out, /did it land\?/, 'the repair reads the state before any retry');
  assert.match(r.out, /--job brief --pass 1/, 'the re-run repair names the pass it resolved');
});

test('a brief whose label edit is refused names the label-only repair, never a publish re-run', () => {
  const root = repo();
  draft(root, 'brief-acme-widgets-7', BRIEF_READY);
  const r = run(['--issue', '7', '--job', 'brief'], { root, answers: { labelList: READY_LABELS, labels: { status: 1, stderr: 'nope' } } });
  assert.equal(r.code, 1);
  assert.match(r.out, /gh issue edit 7 --repo acme\/widgets .*--add-label ready-for-agent/);
  assert.match(r.out, /already posted/i);
});

test('a repository without the ready-for-agent label refuses the batch, and the repair creates it', () => {
  // The generic "edit the draft" repair is wrong for this one name: a
  // repository new to this flow has simply never created the label, and the
  // directive is right.
  const root = repo();
  draft(root, 'brief-acme-widgets-7', BRIEF_READY);
  const r = run(['--issue', '7', '--job', 'brief'], { root });
  assert.equal(r.code, 1);
  assert.equal(mutations(r.calls).length, 0, 'nothing landed');
  assert.match(r.out, /ready-for-agent/);
  assert.match(r.out, /gh label create ready-for-agent --repo acme\/widgets/);
});

test('open questions block a brief publish exactly as they block a triage one', () => {
  const root = repo();
  draft(root, 'brief-acme-widgets-7', 'Labels: ready-for-agent\n\nQ1: [product] cap the import where?\nSummary.\n');
  const r = run(['--issue', '7', '--job', 'brief'], { root, answers: { labelList: READY_LABELS } });
  assert.equal(r.code, 1);
  assert.equal(mutations(r.calls).length, 0);
  assert.match(r.out, /open question/);
});
