/**
 * THE REPORT A COMPLETION CARRIES, and the four dispositions it is named under.
 *
 * The first test is the one that keeps this runtime honest: the rule that turns
 * a dispatch record into a path exists twice — once for the brief
 * (`src/worker/report.mjs`), once here for the receiver (`docs/adr/0002`) — and
 * two rules that must agree are two rules that will drift unless a test reads
 * one record on both sides and demands one path. The record is the fixture #135
 * committed, and the expected path is the file it committed beside it.
 *
 * Everything below uses real files in a real temp tree. The containment proof
 * this module makes is `realpath`, and on macOS `/var` IS a symlink — a mocked
 * filesystem would pass a proof the real one fails.
 */

import { expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { reportPath as workerReportPath } from '../../src/worker/report.mjs';
import { resetDispatchNames } from './attribution.ts';
import { REPORT_CAP_BYTES, completionReport, reportPath } from './completion.ts';

const FIXTURE = join(import.meta.dir, '..', '..', 'tests', 'fixtures', 'report-record.json');
const EXPECTED = join(import.meta.dir, '..', '..', 'tests', 'fixtures', 'report-path.txt');

const DISPATCH = 'ctx_69710a418c47';

/** A record shaped like the one `ax worker start` writes, with the effects a caller chooses. */
function record(effects: unknown[], request = '137-work') {
  return {
    request,
    host: 'test.example',
    orca: 'orca',
    attempts: [
      {
        n: 1,
        settled: false,
        phases: [
          {
            name: 'worker-start',
            argv: ['orca', 'orchestration', 'worker-start'],
            receipt: { ok: true, result: { dispatchId: DISPATCH, state: 'ready', effects } },
            exit: 0,
          },
        ],
      },
    ],
  };
}

/** A worktree in a fresh temp tree, plus the Report path derived under it. */
function worktree(request = '137-work') {
  const path = mkdtempSync(join(tmpdir(), 'ax-report-'));
  const derived = join(path, '.scratch', 'report', `${request}.md`);
  return { path, derived, rec: record([{ kind: 'worktree', id: `repo::${path}` }], request) };
}

function withReport(body: string, request = '137-work') {
  const wt = worktree(request);
  mkdirSync(dirname(wt.derived), { recursive: true });
  writeFileSync(wt.derived, body);
  return wt;
}

/** A completion exactly as Orca delivers one: `dispatch:<id>` handle, payload as a string. */
function completion(payload: Record<string, unknown> | null = null) {
  return {
    id: 'm1',
    type: 'worker_done',
    body: 'Opened PR #99. Both suites green. Nothing left.',
    from_handle: `dispatch:${DISPATCH}`,
    ...(payload === null ? {} : { payload: JSON.stringify(payload) }),
  };
}

/** The receiver's own wiring, with the record lookup and the host answer injected. */
function deps(rec: unknown, environment = '') {
  return {
    record: (id: string) => (id === DISPATCH ? { request: '137-work', json: rec } : null),
    environmentOf: () => environment,
  };
}

// ─── parity, which is the reason the twin is allowed to exist ────────────────

test('the fixture #135 committed yields the same path here as in the worker module', () => {
  const rec = JSON.parse(readFileSync(FIXTURE, 'utf8'));
  const expected = readFileSync(EXPECTED, 'utf8').trim();

  expect(reportPath(rec).path).toBe(expected);
  // And against the other implementation directly, not only its committed
  // answer: the fixture file could be regenerated by one side alone.
  expect(reportPath(rec).path).toBe(workerReportPath(rec).path);
});

// The case list below is the twin's maintenance contract, and it is kept by
// hand: a new refusal branch on EITHER side of the Report-path rule joins this
// list in the same commit that adds it — never a follow-up. Measured within
// hours of the rule's birth (#143): #136 split the src side into
// `reportPathFor({ worktree, request })` + `reportPath(rec)` and re-worded one
// refusal, and #137's twin drifted the same day; this test caught it on the
// merged tree. So the src side is now TWO functions, and a split or a rewording
// over there moves two wordings here, not one. The twin exists at all because
// importing `reportPath` into the receiver would evaluate the CLI emitter chain
// at every session's startup; this list is the price of that ruling.
test('both rules refuse the same records, and neither invents a path key', () => {
  const cases: Array<[string, unknown]> = [
    ['no worktree', record([])],
    ['two worktrees', record([{ kind: 'worktree', id: 'repo::/wt-a' }, { kind: 'worktree', id: 'repo::/wt-b' }])],
    ['a traversal request', record([{ kind: 'worktree', id: 'repo::/wt' }], '../../outside')],
    // Reachable, and newly worded by #136's `reportPathFor`: an effect naming a
    // relative directory. Both rules must refuse it the same way, in the same
    // order relative to the request check.
    ['a relative worktree', record([{ kind: 'worktree', id: 'repo::wt/relative' }])],
    ['a relative worktree and a bad request', record([{ kind: 'worktree', id: 'repo::wt/relative' }], '..')],
  ];

  for (const [why, rec] of cases) {
    const mine = reportPath(rec);
    const theirs = workerReportPath(rec);
    expect(`${why}: ${'path' in mine}`).toBe(`${why}: false`);
    expect(`${why}: ${'path' in theirs}`).toBe(`${why}: false`);
    expect(mine.reason).toBe(theirs.reason);
  }
});

// ─── the four dispositions ──────────────────────────────────────────────────

test('a completion whose record resolves to a worktree holding a Report carries it', () => {
  const wt = withReport('## CRITERIA\n- Parity: MET, `bun test omp` read it back.\n\n## LEARNINGS\n');

  const block = completionReport(completion({ reportPath: wt.derived }), deps(wt.rec));

  expect(block).toContain(wt.derived);
  expect(block).toContain('## CRITERIA');
  expect(block).toContain('- Parity: MET, `bun test omp` read it back.');
  // A reference that agrees with the derived path is not news, so it is not a line.
  expect(block).not.toContain('FINDING');
  expect(block).not.toContain('NOTE');
});

test('a missing file is a finding naming the derived path, never a silence', () => {
  const wt = worktree();

  const block = completionReport(completion({ reportPath: wt.derived }), deps(wt.rec));

  expect(block).toContain('FINDING: no Report at this path');
  expect(block).toContain(wt.derived);
});

test('a reportPath naming another file is a finding, and that file is never opened', () => {
  const wt = withReport('## CRITERIA\n- the derived Report\n');
  const elsewhere = join(mkdtempSync(join(tmpdir(), 'ax-decoy-')), 'claimed.md');
  writeFileSync(elsewhere, 'ATTACKER-PASSPHRASE-8f21\n');

  const block = completionReport(completion({ reportPath: elsewhere }), deps(wt.rec));

  expect(block).toContain('FINDING: the completion named');
  expect(block).toContain(elsewhere);
  // The proof, not the intention: the bytes of the named file are absent.
  expect(block).not.toContain('ATTACKER-PASSPHRASE-8f21');
  // And the derived Report still arrives — a contradicted reference withholds nothing.
  expect(block).toContain('- the derived Report');
});

test('no reportPath with the file present is a note, and the Report is injected', () => {
  const wt = withReport('## CRITERIA\n- the derived Report\n');

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('NOTE: the completion named no reportPath');
  expect(block).toContain('- the derived Report');
  expect(block).not.toContain('FINDING');
});

test('a worktree on another host is inaccessible, and no local file stands in for it', () => {
  // The same path exists HERE, holding something else. A dispatch that ran on
  // another execution host must never read it: same path, different machine,
  // different file — that is the whole hazard of a host-blind read.
  const wt = withReport('LOCAL-IMPOSTOR-3c7d\n');

  const block = completionReport(completion(), deps(wt.rec, 'gapicore'));

  expect(block).toContain('Report inaccessible from this host');
  expect(block).toContain(wt.derived);
  expect(block).toContain('gapicore');
  expect(block).not.toContain('LOCAL-IMPOSTOR-3c7d');
});

// ─── the fences and the emitters ────────────────────────────────────────────

test('a Report symlinked out of the worktree is refused by the realpath proof', () => {
  const wt = worktree();
  const outside = join(mkdtempSync(join(tmpdir(), 'ax-outside-')), 'secret.md');
  writeFileSync(outside, 'OUTSIDE-PASSPHRASE-b19e\n');
  mkdirSync(dirname(wt.derived), { recursive: true });
  symlinkSync(outside, wt.derived);

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('FINDING: the derived path resolves outside the recorded worktree');
  expect(block).not.toContain('OUTSIDE-PASSPHRASE-b19e');
});

test('an oversized Report keeps CRITERIA whole and ends on a truncation line naming the path', () => {
  const criteria = '## CRITERIA\n- Parity: MET, one path from two rules.\n- Cap: MET, this line survived.\n';
  const filler = `## EVIDENCE\n${'evidence line, repeated to overflow the cap\n'.repeat(1200)}`;
  const wt = withReport(`${criteria}\n${filler}\n## LEARNINGS\n- durable: TAIL-MARKER-4a90\n`);

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('- Parity: MET, one path from two rules.');
  expect(block).toContain('- Cap: MET, this line survived.');
  expect(block).toContain('`## CRITERIA` is whole above; read the rest at');
  expect(block).toContain(wt.derived);
  expect(block).not.toContain('TAIL-MARKER-4a90');
  expect(block.length).toBeLessThan(REPORT_CAP_BYTES + 2_000);
});

test('a CRITERIA section larger than the cap is refused by name, never shown in part', () => {
  // THE CASE A HEAD CAP CANNOT HONOUR, and the ticket's criterion is what
  // decides it: `## CRITERIA` stays whole. A section larger than the cap itself
  // cannot be kept whole AND bounded, and raising the cap for one Report would
  // make the cap not a cap — an unbounded section is an unbounded injection into
  // the orchestrator's context. So nothing partial is shown: a truncated
  // criteria list reads as complete, and the reader decides on it.
  const wt = withReport(
    `## CRITERIA\n${'- a criterion line, repeated past the cap\n'.repeat(500)}\n## LEARNINGS\n- durable: x\n`,
  );

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('FINDING: the Report\'s `## CRITERIA` section alone is');
  expect(block).toContain('no complete criteria list can be injected');
  expect(block).toContain(`Repair: read ${wt.derived}`);
  // Not one criterion line reaches the model, and no `---` body fence opens.
  expect(block).not.toContain('- a criterion line');
});

/**
 * WHAT THE READER DOES NEXT, which is the half a diagnosis leaves out.
 *
 * `AGENTS.md`: every finding names its repair — "a `bad` without a `fix` is a
 * finding neither an agent nor a human can act on". These three came out of the
 * review on PR #142, and each one is a case where the block told the truth and
 * still left the orchestrator to invent the next move, or told a truth that was
 * not the one that happened.
 */
test('a missing Report names its repair, and names the channel it goes through', () => {
  const wt = worktree();

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('FINDING: no Report at this path');
  expect(block).toContain('Repair:');
  expect(block).toContain('peer_reply');
  // The repair must not invite the one message Orca has already settled.
  expect(block).toContain('never a second `worker_done`');
});

test('an oversized Report with no CRITERIA heading gets a neutral trailer, not a completeness claim', () => {
  // The heading is missing or misspelled, so nothing above the trailer is a
  // criteria list. Claiming the section is whole would be a false completeness
  // claim at the very gate that reads it — worse than the malformed Report.
  const wt = withReport(`# Report\n${'a line with no heading above it\n'.repeat(700)}`);

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('no `## CRITERIA` heading was found');
  expect(block).not.toContain('`## CRITERIA` is whole above');
});

test('a resolution failure that is not an absence is not blamed on the worker', () => {
  // A symlink loop at the derived path: the file "exists" and cannot resolve.
  // ENOENT is the only error that means the worker never wrote one, and
  // pointing recovery at the worker for an ELOOP sends it to fix a file it has
  // no fault in.
  const wt = worktree();
  mkdirSync(dirname(wt.derived), { recursive: true });
  symlinkSync(wt.derived, wt.derived);

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('ELOOP');
  expect(block).not.toContain('the worker completed without writing one there');
});

test("a dispatch capability in the Report is redacted, not relayed", () => {
  // Child-authored text carries the token BY CONSTRUCTION (`src/redact.mjs`),
  // and the Report is child-authored text reaching another session's context.
  const wt = withReport('## CRITERIA\n- ran `--dispatch-capability dcap_4el9BbvjyOxxx`\n');

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('dcap_<redacted>');
  expect(block).not.toContain('dcap_4el9BbvjyOxxx');
});

test('a capability inside a contradicted reportPath is redacted too', () => {
  // The finding QUOTES a path the worker chose, so that quote is child-authored
  // text on the same footing as the Report's body. Redacting only the body is
  // the leak `src/worker/transcript.mjs` puts one boundary on the emitter for.
  const wt = withReport('## CRITERIA\n- the derived Report\n');

  const block = completionReport(
    completion({ reportPath: '/tmp/claimed-dcap_4el9BbvjyOxxx/report.md' }),
    deps(wt.rec),
  );

  expect(block).toContain('FINDING: the completion named');
  expect(block).toContain('dcap_<redacted>');
  expect(block).not.toContain('dcap_4el9BbvjyOxxx');
});

test('a record that names no worktree is a named inability, and still no path key', () => {
  const block = completionReport(completion(), deps(record([])));

  expect(block).toContain('FINDING');
  expect(block).toContain('cannot be established');
});

test('nothing is appended to a message that is not a dispatched worker completion', () => {
  const wt = withReport('## CRITERIA\n- x\n');

  // A status message from the same worker: not a completion.
  expect(completionReport({ ...completion(), type: 'status' }, deps(wt.rec))).toBe('');
  // A completion from a pane peer: no dispatch record to derive from.
  expect(completionReport({ ...completion(), from_handle: 'term_child' }, deps(wt.rec))).toBe('');
  // A dispatch this machine never recorded: nothing of ours to derive.
  expect(
    completionReport({ ...completion(), from_handle: 'dispatch:ctx_stranger' }, deps(wt.rec)),
  ).toBe('');
});

// ─── the witnessed shape: a LOCAL supervised worker on the fork build ─────────
//
// Measured 2026-09-05 on the #162 wave (the Report's first real measurement,
// flosrn/ax#168): the #164 worker's `worker_done` reached the orchestrator's Run
// with `from_handle: term_0843…`, a `sender_pane_key`, and the dispatch id in
// `payload.dispatchId` — not under a `dispatch:<id>` address. Both gates missed
// it: attribution said pane, this module said not-a-completion, and the
// completion was injected with no Report block and no finding. Silence, on the
// one message this module exists to annotate. The `dispatch:<id>` shape is the
// FEDERATED one (no pane key by contract); a local supervised worker arrives
// witnessed, and the record — which names the pane it dispatched — is what
// proves the payload's dispatch id is this sender's to claim.

const PANE = 'term_08435344-a42a-4152-a220-82db976d8424';
const PANE_KEY = 'd113fd70-347d-4ddf-893c-0090f117f7da:4eb71be1-ca2a-4e95-bc1d-446cde509ef8';

/** A record whose worker-start also recorded the agent pane, as a real one does. */
function witnessedWorktree(request = '164-work') {
  const wt = withReport('## CRITERIA\n- Witness: MET, the record names this pane.\n\n## LEARNINGS\n', request);
  wt.rec.attempts[0].phases[0].receipt.result.effects.push({ kind: 'terminal', role: 'agent', action: 'created', id: PANE });
  return wt;
}

/** The envelope exactly as the fork build delivers a local worker's completion. */
function witnessed(payload: Record<string, unknown>, extra: Record<string, unknown> = {}) {
  return {
    id: 'msg_0ef061ff33f5',
    type: 'worker_done',
    body: 'Inherited the placement. Both suites green. Nothing left.',
    from_handle: PANE,
    to_handle: 'run:run_494da6a0f77c',
    sender_pane_key: PANE_KEY,
    payload: JSON.stringify(payload),
    ...extra,
  };
}

test('a witnessed pane whose payload names a dispatch this machine recorded FOR THAT PANE carries the Report', () => {
  const wt = witnessedWorktree();

  const block = completionReport(
    witnessed({ taskId: 'task_3d703cad122b', dispatchId: DISPATCH, outcome: 'succeeded', reportPath: wt.derived }),
    deps(wt.rec),
  );

  expect(block).toContain('## CRITERIA');
  expect(block).toContain('- Witness: MET, the record names this pane.');
  expect(block).not.toContain('FINDING');
});

test('a witnessed pane claiming a dispatch whose record names ANOTHER pane is a finding, and nothing is derived', () => {
  const wt = witnessedWorktree();

  const block = completionReport(
    witnessed({ dispatchId: DISPATCH, outcome: 'succeeded' }, { from_handle: 'term_someone_else' }),
    deps(wt.rec),
  );

  expect(block).toContain('FINDING');
  expect(block).toContain(PANE);
  expect(block).toContain('term_someone_else');
  expect(block).not.toContain('- Witness: MET');
});

test('an UNWITNESSED sender claiming a dispatch is a finding, whatever handle it typed', () => {
  // Orca nulls `sender_pane_key` when a sender overrides its identity (`--from`).
  // A handle equal to the recorded one proves nothing then: the witness is the
  // pane key, and the payload alone never authorizes a derivation.
  const wt = witnessedWorktree();

  const block = completionReport(witnessed({ dispatchId: DISPATCH }, { sender_pane_key: '' }), deps(wt.rec));

  expect(block).toContain('FINDING');
  expect(block).toContain('not witnessed');
  expect(block).not.toContain('- Witness: MET');
});

test('a record that recorded no pane cannot cross-check a witnessed claim, and says so', () => {
  const wt = withReport('## CRITERIA\n- x\n', '164-work');

  const block = completionReport(witnessed({ dispatchId: DISPATCH }), deps(wt.rec));

  expect(block).toContain('FINDING');
  expect(block).toContain('names no pane');
  expect(block).not.toContain('- x');
});

test('a witnessed worker_done naming a dispatch this machine never recorded stays silent, like the federated stranger', () => {
  const wt = witnessedWorktree();
  expect(completionReport(witnessed({ dispatchId: 'ctx_stranger' }), deps(wt.rec))).toBe('');
});

test('the cross-check binds to the attempt that owns the claimed dispatch — a replaced pane never lends its identity', () => {
  // Records ACCUMULATE: a `--replace` writes a second attempt with a second
  // dispatch id and a second pane. A record-wide "any terminal this record ever
  // named" scan would let the retired pane claim the new dispatch's completion,
  // or refuse the new pane because the old one came first — the wrong-slice
  // attribution `environmentOfDispatch` refuses for the same reason.
  const wt = withReport('## CRITERIA\n- Replace: MET, the new pane reported.\n\n## LEARNINGS\n', '164-work');
  const OLD_PANE = 'term_old_1111';
  const NEW_PANE = 'term_new_2222';
  const OLD_ID = 'ctx_old_attempt';
  const worktreeEffect = wt.rec.attempts[0].phases[0].receipt.result.effects[0];
  wt.rec.attempts = [
    {
      n: 1,
      settled: true,
      phases: [
        {
          name: 'worker-start',
          argv: ['orca', 'orchestration', 'worker-start'],
          receipt: { ok: true, result: { dispatchId: OLD_ID, state: 'failed', effects: [worktreeEffect, { kind: 'terminal', role: 'agent', action: 'created', id: OLD_PANE }] } },
          exit: 1,
        },
      ],
    },
    {
      n: 2,
      settled: false,
      phases: [
        {
          name: 'worker-start',
          argv: ['orca', 'orchestration', 'worker-start', '--replace'],
          receipt: { ok: true, result: { dispatchId: DISPATCH, state: 'ready', effects: [worktreeEffect, { kind: 'terminal', role: 'agent', action: 'created', id: NEW_PANE }] } },
          exit: 0,
        },
      ],
    },
  ];

  // The new pane claiming the new dispatch: derived.
  const accepted = completionReport(witnessed({ dispatchId: DISPATCH }, { from_handle: NEW_PANE }), deps(wt.rec));
  expect(accepted).toContain('- Replace: MET, the new pane reported.');
  expect(accepted).not.toContain('FINDING');

  // The retired pane claiming the new dispatch: a finding naming the pane the
  // NEW attempt recorded, never the old one it happens to appear in.
  const refused = completionReport(witnessed({ dispatchId: DISPATCH }, { from_handle: OLD_PANE }), deps(wt.rec));
  expect(refused).toContain('FINDING');
  expect(refused).toContain(NEW_PANE);
  expect(refused).toContain(OLD_PANE);
  expect(refused).not.toContain('- Replace: MET');
  // The new pane claiming the OLD dispatch id: refused against the old attempt's
  // own pane — the id decides which attempt is consulted. The lookup answers
  // both ids from the one accumulated record, as the real store does.
  const both = { record: (id: string) => (id === DISPATCH || id === OLD_ID ? { request: '164-work', json: wt.rec } : null), environmentOf: () => '' };
  const stale = completionReport(witnessed({ dispatchId: OLD_ID }, { from_handle: NEW_PANE }), both);
  expect(stale).toContain('FINDING');
  expect(stale).toContain(OLD_PANE);
});

test('the reader is total: a lookup that throws becomes a finding, never a lost completion', () => {
  // The receiver appends this block to the completion it is about to inject. A
  // throw here would fail the injection and replay the whole delivery, so the
  // module absorbs its own faults into a line.
  const block = completionReport(completion(), {
    record: () => {
      throw new Error('store unreadable');
    },
    environmentOf: () => '',
  });

  expect(block).toContain('FINDING');
  expect(block).toContain('store unreadable');
});

test('the wired defaults answer from a real dispatch store, with nothing injected', () => {
  // Every test above hands the record over. This one proves the DEFAULTS the
  // receiver actually runs with: `dispatchRecord` walking a store on disk, and
  // `environmentOfDispatch` reading the recorded argv for `--on`. A module whose
  // only proof is its injected seam is a module nobody has run.
  const store = mkdtempSync(join(tmpdir(), 'ax-store-'));
  const dispatch = 'ctx_defaults_1';
  const wt = withReport('## CRITERIA\n- Defaults: MET, read through the store.\n', 'wired-work');
  const rec = {
    ...wt.rec,
    attempts: [
      {
        n: 1,
        settled: false,
        phases: [
          {
            name: 'worker-start',
            argv: ['orca', 'orchestration', 'worker-start', '--task', 'task_1'],
            receipt: {
              ok: true,
              result: {
                dispatchId: dispatch,
                effects: [{ kind: 'worktree', id: `repo::${wt.path}` }],
              },
            },
            exit: 0,
          },
        ],
      },
    ],
  };
  writeFileSync(join(store, 'wired-work.json'), JSON.stringify(rec));

  const previous = process.env.ORCA_DISPATCH_STORE_DIR;
  process.env.ORCA_DISPATCH_STORE_DIR = store;
  resetDispatchNames();
  try {
    const block = completionReport({
      id: 'm1',
      type: 'worker_done',
      body: 'Opened PR #99.',
      from_handle: `dispatch:${dispatch}`,
    });

    expect(block).toContain('- Defaults: MET, read through the store.');
    expect(block).toContain(wt.derived);
    // No `--on` on the recorded argv, so the worktree is here and the read ran.
    expect(block).not.toContain('inaccessible from this host');
  } finally {
    if (previous === undefined) delete process.env.ORCA_DISPATCH_STORE_DIR;
    else process.env.ORCA_DISPATCH_STORE_DIR = previous;
    resetDispatchNames();
  }
});

test('the wired defaults classify a remote dispatch from the recorded argv alone', () => {
  // The `--on` half of the default. The disposition above is reached through the
  // injected seam; this is `environmentOfDispatch` reading a record off disk, so
  // the classification that decides whether a file is even touched is proven on
  // the code path the receiver runs. A Report exists at the derived path HERE,
  // holding something else, and must not be read.
  const store = mkdtempSync(join(tmpdir(), 'ax-store-remote-'));
  const dispatch = 'ctx_defaults_remote';
  const wt = withReport('REMOTE-IMPOSTOR-71fc\n', 'remote-work');
  writeFileSync(
    join(store, 'remote-work.json'),
    JSON.stringify({
      ...wt.rec,
      attempts: [
        {
          n: 1,
          settled: false,
          phases: [
            {
              name: 'worker-start',
              argv: ['orca', 'orchestration', 'worker-start', '--task', 'task_1', '--on', 'gapicore'],
              receipt: {
                ok: true,
                result: { dispatchId: dispatch, effects: [{ kind: 'worktree', id: `repo::${wt.path}` }] },
              },
              exit: 0,
            },
          ],
        },
      ],
    }),
  );

  const previous = process.env.ORCA_DISPATCH_STORE_DIR;
  process.env.ORCA_DISPATCH_STORE_DIR = store;
  resetDispatchNames();
  try {
    const block = completionReport({
      id: 'm1',
      type: 'worker_done',
      body: 'Opened PR #99.',
      from_handle: `dispatch:${dispatch}`,
    });

    expect(block).toContain('Report inaccessible from this host');
    expect(block).toContain('gapicore');
    expect(block).toContain(wt.derived);
    expect(block).not.toContain('REMOTE-IMPOSTOR-71fc');
  } finally {
    if (previous === undefined) delete process.env.ORCA_DISPATCH_STORE_DIR;
    else process.env.ORCA_DISPATCH_STORE_DIR = previous;
    resetDispatchNames();
  }
});
