/**
 * THE REPORT A COMPLETION CARRIES, and the four dispositions it is named under.
 *
 * The first test is the one that keeps this runtime honest: the rule that turns
 * a dispatch record into a path exists twice — once for the brief
 * (`src/worker/report.mjs`), once here for the receiver (`docs/adr/0002`) — and
 * two rules that must agree are two rules that will drift unless a test reads
 * one record on both sides and demands one path. The record is the fixture #135
 * committed, and the expected path is the file it committed beside it.
 *
 * Everything below uses real files in a real temp tree. The containment proof
 * this module makes is `realpath`, and on macOS `/var` IS a symlink — a mocked
 * filesystem would pass a proof the real one fails.
 */

import { expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { reportPath as workerReportPath } from '../../src/worker/report.mjs';
import { resetDispatchNames } from './attribution.ts';
import { REPORT_CAP_BYTES, completionReport, reportPath } from './completion.ts';

const FIXTURE = join(import.meta.dir, '..', '..', 'tests', 'fixtures', 'report-record.json');
const EXPECTED = join(import.meta.dir, '..', '..', 'tests', 'fixtures', 'report-path.txt');

const DISPATCH = 'ctx_69710a418c47';

/** A record shaped like the one `ax worker start` writes, with the effects a caller chooses. */
function record(effects: unknown[], request = '137-work') {
  return {
    request,
    host: 'test.example',
    orca: 'orca',
    attempts: [
      {
        n: 1,
        settled: false,
        phases: [
          {
            name: 'worker-start',
            argv: ['orca', 'orchestration', 'worker-start'],
            receipt: { ok: true, result: { dispatchId: DISPATCH, state: 'ready', effects } },
            exit: 0,
          },
        ],
      },
    ],
  };
}

/** A worktree in a fresh temp tree, plus the Report path derived under it. */
function worktree(request = '137-work') {
  const path = mkdtempSync(join(tmpdir(), 'ax-report-'));
  const derived = join(path, '.scratch', 'report', `${request}.md`);
  return { path, derived, rec: record([{ kind: 'worktree', id: `repo::${path}` }], request) };
}

function withReport(body: string, request = '137-work') {
  const wt = worktree(request);
  mkdirSync(dirname(wt.derived), { recursive: true });
  writeFileSync(wt.derived, body);
  return wt;
}

/** A completion exactly as Orca delivers one: `dispatch:<id>` handle, payload as a string. */
function completion(payload: Record<string, unknown> | null = null) {
  return {
    id: 'm1',
    type: 'worker_done',
    body: 'Opened PR #99. Both suites green. Nothing left.',
    from_handle: `dispatch:${DISPATCH}`,
    ...(payload === null ? {} : { payload: JSON.stringify(payload) }),
  };
}

/** The receiver's own wiring, with the record lookup and the host answer injected. */
function deps(rec: unknown, environment = '') {
  return {
    record: (id: string) => (id === DISPATCH ? { request: '137-work', json: rec } : null),
    environmentOf: () => environment,
  };
}

// ─── parity, which is the reason the twin is allowed to exist ────────────────

test('the fixture #135 committed yields the same path here as in the worker module', () => {
  const rec = JSON.parse(readFileSync(FIXTURE, 'utf8'));
  const expected = readFileSync(EXPECTED, 'utf8').trim();

  expect(reportPath(rec).path).toBe(expected);
  // And against the other implementation directly, not only its committed
  // answer: the fixture file could be regenerated by one side alone.
  expect(reportPath(rec).path).toBe(workerReportPath(rec).path);
});

test('both rules refuse the same records, and neither invents a path key', () => {
  const cases: Array<[string, unknown]> = [
    ['no worktree', record([])],
    ['two worktrees', record([{ kind: 'worktree', id: 'repo::/wt-a' }, { kind: 'worktree', id: 'repo::/wt-b' }])],
    ['a traversal request', record([{ kind: 'worktree', id: 'repo::/wt' }], '../../outside')],
  ];

  for (const [why, rec] of cases) {
    const mine = reportPath(rec);
    const theirs = workerReportPath(rec);
    expect(`${why}: ${'path' in mine}`).toBe(`${why}: false`);
    expect(`${why}: ${'path' in theirs}`).toBe(`${why}: false`);
    expect(mine.reason).toBe(theirs.reason);
  }
});

// ─── the four dispositions ──────────────────────────────────────────────────

test('a completion whose record resolves to a worktree holding a Report carries it', () => {
  const wt = withReport('## CRITERIA\n- Parity: MET, `bun test omp` read it back.\n\n## LEARNINGS\n');

  const block = completionReport(completion({ reportPath: wt.derived }), deps(wt.rec));

  expect(block).toContain(wt.derived);
  expect(block).toContain('## CRITERIA');
  expect(block).toContain('- Parity: MET, `bun test omp` read it back.');
  // A reference that agrees with the derived path is not news, so it is not a line.
  expect(block).not.toContain('FINDING');
  expect(block).not.toContain('NOTE');
});

test('a missing file is a finding naming the derived path, never a silence', () => {
  const wt = worktree();

  const block = completionReport(completion({ reportPath: wt.derived }), deps(wt.rec));

  expect(block).toContain('FINDING: no Report at this path');
  expect(block).toContain(wt.derived);
});

test('a reportPath naming another file is a finding, and that file is never opened', () => {
  const wt = withReport('## CRITERIA\n- the derived Report\n');
  const elsewhere = join(mkdtempSync(join(tmpdir(), 'ax-decoy-')), 'claimed.md');
  writeFileSync(elsewhere, 'ATTACKER-PASSPHRASE-8f21\n');

  const block = completionReport(completion({ reportPath: elsewhere }), deps(wt.rec));

  expect(block).toContain('FINDING: the completion named');
  expect(block).toContain(elsewhere);
  // The proof, not the intention: the bytes of the named file are absent.
  expect(block).not.toContain('ATTACKER-PASSPHRASE-8f21');
  // And the derived Report still arrives — a contradicted reference withholds nothing.
  expect(block).toContain('- the derived Report');
});

test('no reportPath with the file present is a note, and the Report is injected', () => {
  const wt = withReport('## CRITERIA\n- the derived Report\n');

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('NOTE: the completion named no reportPath');
  expect(block).toContain('- the derived Report');
  expect(block).not.toContain('FINDING');
});

test('a worktree on another host is inaccessible, and no local file stands in for it', () => {
  // The same path exists HERE, holding something else. A dispatch that ran on
  // another execution host must never read it: same path, different machine,
  // different file — that is the whole hazard of a host-blind read.
  const wt = withReport('LOCAL-IMPOSTOR-3c7d\n');

  const block = completionReport(completion(), deps(wt.rec, 'gapicore'));

  expect(block).toContain('Report inaccessible from this host');
  expect(block).toContain(wt.derived);
  expect(block).toContain('gapicore');
  expect(block).not.toContain('LOCAL-IMPOSTOR-3c7d');
});

// ─── the fences and the emitters ────────────────────────────────────────────

test('a Report symlinked out of the worktree is refused by the realpath proof', () => {
  const wt = worktree();
  const outside = join(mkdtempSync(join(tmpdir(), 'ax-outside-')), 'secret.md');
  writeFileSync(outside, 'OUTSIDE-PASSPHRASE-b19e\n');
  mkdirSync(dirname(wt.derived), { recursive: true });
  symlinkSync(outside, wt.derived);

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('FINDING: the derived path resolves outside the recorded worktree');
  expect(block).not.toContain('OUTSIDE-PASSPHRASE-b19e');
});

test('an oversized Report keeps CRITERIA whole and ends on a truncation line naming the path', () => {
  const criteria = '## CRITERIA\n- Parity: MET, one path from two rules.\n- Cap: MET, this line survived.\n';
  const filler = `## EVIDENCE\n${'evidence line, repeated to overflow the cap\n'.repeat(1200)}`;
  const wt = withReport(`${criteria}\n${filler}\n## LEARNINGS\n- durable: TAIL-MARKER-4a90\n`);

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('- Parity: MET, one path from two rules.');
  expect(block).toContain('- Cap: MET, this line survived.');
  expect(block).toContain(`read it in full at ${wt.derived}`);
  expect(block).not.toContain('TAIL-MARKER-4a90');
  expect(block.length).toBeLessThan(REPORT_CAP_BYTES + 2_000);
});

test("a dispatch capability in the Report is redacted, not relayed", () => {
  // Child-authored text carries the token BY CONSTRUCTION (`src/redact.mjs`),
  // and the Report is child-authored text reaching another session's context.
  const wt = withReport('## CRITERIA\n- ran `--dispatch-capability dcap_4el9BbvjyOxxx`\n');

  const block = completionReport(completion(), deps(wt.rec));

  expect(block).toContain('dcap_<redacted>');
  expect(block).not.toContain('dcap_4el9BbvjyOxxx');
});

test('a capability inside a contradicted reportPath is redacted too', () => {
  // The finding QUOTES a path the worker chose, so that quote is child-authored
  // text on the same footing as the Report's body. Redacting only the body is
  // the leak `src/worker/transcript.mjs` puts one boundary on the emitter for.
  const wt = withReport('## CRITERIA\n- the derived Report\n');

  const block = completionReport(
    completion({ reportPath: '/tmp/claimed-dcap_4el9BbvjyOxxx/report.md' }),
    deps(wt.rec),
  );

  expect(block).toContain('FINDING: the completion named');
  expect(block).toContain('dcap_<redacted>');
  expect(block).not.toContain('dcap_4el9BbvjyOxxx');
});

test('a record that names no worktree is a named inability, and still no path key', () => {
  const block = completionReport(completion(), deps(record([])));

  expect(block).toContain('FINDING');
  expect(block).toContain('cannot be established');
});

test('nothing is appended to a message that is not a dispatched worker completion', () => {
  const wt = withReport('## CRITERIA\n- x\n');

  // A status message from the same worker: not a completion.
  expect(completionReport({ ...completion(), type: 'status' }, deps(wt.rec))).toBe('');
  // A completion from a pane peer: no dispatch record to derive from.
  expect(completionReport({ ...completion(), from_handle: 'term_child' }, deps(wt.rec))).toBe('');
  // A dispatch this machine never recorded: nothing of ours to derive.
  expect(
    completionReport({ ...completion(), from_handle: 'dispatch:ctx_stranger' }, deps(wt.rec)),
  ).toBe('');
});

test('the reader is total: a lookup that throws becomes a finding, never a lost completion', () => {
  // The receiver appends this block to the completion it is about to inject. A
  // throw here would fail the injection and replay the whole delivery, so the
  // module absorbs its own faults into a line.
  const block = completionReport(completion(), {
    record: () => {
      throw new Error('store unreadable');
    },
    environmentOf: () => '',
  });

  expect(block).toContain('FINDING');
  expect(block).toContain('store unreadable');
});

test('the wired defaults answer from a real dispatch store, with nothing injected', () => {
  // Every test above hands the record over. This one proves the DEFAULTS the
  // receiver actually runs with: `dispatchRecord` walking a store on disk, and
  // `environmentOfDispatch` reading the recorded argv for `--on`. A module whose
  // only proof is its injected seam is a module nobody has run.
  const store = mkdtempSync(join(tmpdir(), 'ax-store-'));
  const dispatch = 'ctx_defaults_1';
  const wt = withReport('## CRITERIA\n- Defaults: MET, read through the store.\n', 'wired-work');
  const rec = {
    ...wt.rec,
    attempts: [
      {
        n: 1,
        settled: false,
        phases: [
          {
            name: 'worker-start',
            argv: ['orca', 'orchestration', 'worker-start', '--task', 'task_1'],
            receipt: {
              ok: true,
              result: {
                dispatchId: dispatch,
                effects: [{ kind: 'worktree', id: `repo::${wt.path}` }],
              },
            },
            exit: 0,
          },
        ],
      },
    ],
  };
  writeFileSync(join(store, 'wired-work.json'), JSON.stringify(rec));

  const previous = process.env.ORCA_DISPATCH_STORE_DIR;
  process.env.ORCA_DISPATCH_STORE_DIR = store;
  resetDispatchNames();
  try {
    const block = completionReport({
      id: 'm1',
      type: 'worker_done',
      body: 'Opened PR #99.',
      from_handle: `dispatch:${dispatch}`,
    });

    expect(block).toContain('- Defaults: MET, read through the store.');
    expect(block).toContain(wt.derived);
    // No `--on` on the recorded argv, so the worktree is here and the read ran.
    expect(block).not.toContain('inaccessible from this host');
  } finally {
    if (previous === undefined) delete process.env.ORCA_DISPATCH_STORE_DIR;
    else process.env.ORCA_DISPATCH_STORE_DIR = previous;
    resetDispatchNames();
  }
});
